### ISSUE TITLE
No name was provided for external module for global packages

### ISSUE THREAD

**Issue by schettn** [developit/microbundle#1004]
Encountering this issue I have been wondering why with scoped npm packages this warning appears and  with non-scoped npm packages not.
I found that scoped packages don't pass the following check:
https://github.com/developit/microbundle/blob/fa3eac6f491288ff3b8cfd2812eecd350c7a2316/src/index.js#L337

Curious if this is intented.

_Originally posted by @namjul in https://github.com/developit/microbundle/issues/223#issuecomment-788889113_

**Comment by rschristian** [comment]
Scoped packages are harder to guess. For instance:

- `@rschristian/twind`
  - `@rschristian/twind` is a fork of a library called `twind`, so it should be exposed as `twind`.
- `@preact/signals`
  - `signals` is not the name of another library (or at least not one we're basing off of). It should be exposed as `preactSignals`.

Both use cases are very popular, so I tend to think there's too much ambiguity there to "take a side" and set one as the default behavior. Just my 2¢

**Comment by rschristian** [comment]
Going to close this out, hopefully its been answered.
