### ISSUE TITLE
When will the new version of this be published?

### ISSUE THREAD

**Issue by skanapata** [developit/microbundle#1006]
Hello. i see that this PR(https://github.com/developit/microbundle/pull/738) has been merged long time back , but there has not been any new release since then.  May i know when will this be released and available?

**Comment by rschristian** [comment]
Last release was August 12th: https://github.com/developit/microbundle/releases

https://www.npmjs.com/package/microbundle

Not sure what gives you the impression there haven't been any new releases?

**Comment by skanapata** [comment]
@rschristian  i was referring to this. https://www.npmjs.com/package/microbundle-crl. Am i am supposed to use microbundle directly?

**Comment by rschristian** [comment]
`microbundle-crl` is a fork of this project. You can find its repo here: https://github.com/transitive-bullshit/microbundle

**Comment by skanapata** [comment]
@rschristian  Got it, thanks. Will raise the query with that author.

**Comment by rschristian** [comment]
It's been long-since unmaintained, fwiw. You might want to switch to `microbundle` proper, though some of the feature set is different as are some of the defaults.
