### ISSUE TITLE
Inlining CSS doesn't work with Typescript files

### ISSUE THREAD

**Issue by sapientia-sp** [developit/microbundle#1014]
Hi,

I have a simple preact habitat widget app that imports styles using the line `import "./style.css";`
I am also importing the styles in `component.tsx`

*full exmaple*
```
import habitat from 'preact-habitat';
import Widget from './component';

import "./style.css";

const _habitat = habitat(Widget);

_habitat.render({
  selector: '[data-widget-host="habitat"]',
  clean: true
});

```

My build command: `microbundle -i src/index.ts -o dist/bundle.js  --css inline --no-pkg-main -f umd --external none`

# ISSUE: 
Inlining css as shown in the build command doesn't add any css to generated `bundle.js`

**Comment by rschristian** [comment]
This is correct behavior, see the docs: https://github.com/developit/microbundle#css-and-css-modules

You're importing that CSS file with a side-effectful import -- this doesn't really make sense if your goal is to inline.

To copy the example from the docs:

```js
// with `microbundle --css inline`:
import css from './foo.css';
console.log(css); // the generated minified stylesheet
```

**Comment by rschristian** [comment]
Closing this out as the question has hopefully been answered. Feel free to reply and we can continue to talk or I can reopen if there is indeed an issue.
