### ISSUE TITLE
Cannot alias react and react-dom

### ISSUE THREAD

**Issue by imaitland** [developit/microbundle#1020]
I'm using microbundle to build a preact app for distribution. Inside my preact app I am using a react library. To do this I need to alias react to preact/compat.

This is working:
```
microbundle build --alias react=preact/compat
```

But having more than one alias throws an error:
```
microbundle build --alias react=preact/compat react-dom=preact/compat
```

> Error: No entry module found for "my-app-name"

**Comment by rschristian** [comment]
```
$ microbundle build --alias react=preact/compat,react-dom=preact/compat
```

Spaces in any CLI, not just Microbundle, signify separate arguments or flags.

**Comment by imaitland** [comment]
Thanks, yep that was it, closing.
