### ISSUE TITLE
Is microbundle-crl still maintained?

### ISSUE THREAD

**Issue by jruales** [developit/microbundle#1026]
The [npm page for microbundle-crl](https://www.npmjs.com/package/microbundle-crl) points to this GitHub repo. I saw that `microbundle` has been regularly updated but the latest version of `microbundle-crl` is from 3 years ago. I'm also noticing that it depends on some old libraries that are triggering a Dependabot alert due to vulnerabilities in nth-check <2.0.1. Is `microbundle-crl` still being maintained? Or is it recommended to move to use `microbundle` instead? If so, is there some sort of guide for that transition?

**Comment by rschristian** [comment]
[`microbundle-crl` can be found here](https://github.com/transitive-bullshit/microbundle). Indeed, the package meta data was never updated and it's been long unmaintained.

It's probably better to migrate to Microbundle proper, but there is a bit of a gap in behaviors supported by each. In general, `microbundle` is a JS bundler and tries to avoid supporting different asset types. There is _some_ support, just less than `microbundle-crl`. A few flags will probably need to be set to, as `microbundle` defaults to Preact's JSX pragma rather than React's.

AFAIK there's no guide, as the author behind the fork never wrote one or officially archived the project.

**Comment by jruales** [comment]
Thanks @rschristian!

Also tagging @transitive-bullshit from microbundle-crl as FYI, since there's no way of adding GitHub Issues in that repo so I can't add it there

**Comment by rschristian** [comment]
FWIW, there is this thread: https://github.com/transitive-bullshit/create-react-library/issues/284

It's a few years old, so some of the advice might not be accurate anymore, but some people have contributed migration steps.

**Comment by transitive-bullshit** [comment]
Please don't use `microbundle-crl`. It was a fork of `microbundle` and is no longer maintained.

**Comment by jruales** [comment]
Thanks for the update @transitive-bullshit! Since it's no longer maintained, may I suggest, to avoid confusion of future users, that you:
* [deprecate the npm package](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions)
* update the README so that it informs users to move to `microbundle`
* [archive the GitHub repo](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories), and
* point the npm page to the archived repo so that people see the README with those instructions when they click on the link, instead of being directed to the current repo without further instructions?

**Comment by rschristian** [comment]
I'm going to close this out, as there isn't anything actionable for this repo.

If you do try to migrate and get stuck, feel free to ask here or open a new issue and we can take a look and give advice. Thanks!

**Comment by Stan-Stani** [comment]
Advice for those who run into the issue of `microbundle-crl` not supporting TS template literal types like: `${number}`, use yarn resolutions to force the typescript version higher.

```json
"resolutions": {
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "@fluentui/react-portal-compat-context": "9.0.6",
    "react-number-format": "5.3.0",
    "@emotion/react": "^11.11.1",
    "typescript": "^5.3.3"
  },
```
