### ISSUE TITLE
in compress mode, micro bundle causing to trim the code.

### ISSUE THREAD

**Issue by Code-Crash** [developit/microbundle#1029]
In one of my builds, when I'm using the compress flag, it's causing the issue which is trimming the value from `window.parent.document` to `window` only, which is causing a failure in expected behavior. 

Please see the attached images for reference.

Below this image, we can see `window.parent.document` getting changed to `window` only, please see line number 3835 in the first image and in the second 2259.

<img width="1064" alt="uncompress" src="https://user-images.githubusercontent.com/5871757/221486793-bf6c5b44-900b-4152-9144-88ce19434069.png">

Please see the `window`

<img width="1047" alt="compress" src="https://user-images.githubusercontent.com/5871757/221486810-5b339a52-c2f6-46e4-91db-007606b9e883.png">

**Comment by rschristian** [comment]
This is an intentional effect of Terser's `pure_getters` compression option:

> `pure_getters` (default: `"strict"`) -- If you pass `true` for this, Terser will assume that object property access (e.g. `foo.bar` or `foo["bar"]`) doesn't have any side effects. Specify `"strict"` to treat foo.bar as side-effect-free only when `foo` is certain to not throw, i.e. not `null` or `undefined`.

https://github.com/developit/microbundle/blob/bb8713c74706f466672b3109552c7d3e675b5325/src/index.js#L597-L601

Is there any particular reason you're relying on side effects (throwing) rather than just doing the following?

```js
passEmitsToParent = window.parent.document ? false : true;
```

**Comment by Code-Crash** [comment]
Yes @rschristian, I was relying on the catch block if I'm not able to access `window.parent.document`, however as you said adding `if statement` or `ternary operator`, it's working. 

so if it's expected behavior, then we are good.

Thanks for clarification.

**Comment by rschristian** [comment]
Would really recommend against that `try ... catch` pattern you had there. Simple `if` statement is far fewer bytes, is likely to be faster, and just more idiomatic.

**Comment by pravin-tiwari** [comment]
Agree @rschristian, Thanks.
