### ISSUE TITLE
Error: Invalid value "umd" for option "output.format"

### ISSUE THREAD

**Issue by DVitaliy** [developit/microbundle#1032]
I'm getting error:

> Error: Invalid value "umd" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.

if inside method of class has `import`

```js
class Test {
  json = "";
  async load() {
    const json = await import("./json.json");
    this.json = json.default.find((item) => item.name === "name 2")?.name ?? "";
  }
}
```

The source code here https://codesandbox.io/s/focused-sun-igsymq

PS: If change output format (for ex. `esm` or `cjs`) then OK

**Comment by rschristian** [comment]
I think I'd label this as "Working as intended". Dynamic imports make little sense inside of UMD and would need to be translated into another form, hence why Rollup does not support doing this out-of-the-box.

There are some Babel plugins that will transform this, just depends on what your targets are. I don't think this is something we should handle, personally.

**Comment by rschristian** [comment]
@LeoVS09 Your method of changing the targets is correct -- you implicitly request a UMD output if you haven't set your targets so failing the build would be the correct behavior if it cannot be built.
