### ISSUE TITLE
microbundle-crl missing static assets

### ISSUE THREAD

**Issue by guptaashwanee** [developit/microbundle#1033]
As microbundle-crl is fork with few more functionality, but I found few issues with microbundle-crl with missing images as "background-image:url(fullscreen.png);" there are no folders for static assets.

Is there any configuration that I need to update.

**Comment by rschristian** [comment]
`microbundle-crl` is an unmaintained fork that can be [found here](https://github.com/transitive-bullshit/microbundle). 

---

However, in `microbundle` proper, handling images (and other non-JS assets) is something we try to avoid. You can easily still handle this case yourself though with a post-build copy script.

Say we have the following directory structure:

```
src/
--assets/
----fullscreen.png
--index.css
```

And `index.css` contains the following:

```css
background-image: url('./assets/fullscreen.png');
```

To support this, simply add a copy step for common assets:

```sh
$ microbundle ... && cp -r src/assets dist/
```

**Comment by rschristian** [comment]
Closing this out as there's been no response.

Feel free to reply and we can reopen if need be.
