### ISSUE TITLE
After building a file, I get "Permission denied" when call it

### ISSUE THREAD

**Issue by dmaklygin** [developit/microbundle#1035]
I use microbundle to build nodeJS file that will be used in node_modules/.bin folder.

But on linux, when I call:

```
yarn my-script 
```

I get `/bin/sh: 1: my-script: Permission denied`

I think, it's not intentional.

**Comment by rschristian** [comment]
This is unrelated to Microbundle. When files are created, they'll lack execution permissions (but will have when your module is installed normally from NPM). You can set the correct permissions with `chmod +x ./my-script.js`
