### ISSUE TITLE
how to  set "drop console.log"   in code ?

### ISSUE THREAD

**Issue by tonyload** [developit/microbundle#1038]
how to  set "drop console.log"   in code ?

**Comment by rschristian** [comment]
Do you mean for Microbundle to remove all `console.log()` statements from your built code?

If so, that's not something we support.

**Comment by tonyload** [comment]
Why not consider to add this feature…

发自我的iPad

**Comment by rschristian** [comment]
Because I don't think it's particularly compelling. If you want to remove `console.log()` statements, you can remove or comment them out yourself.

**Comment by tonyload** [comment]
ok ~got it  thanks for response
