### ISSUE TITLE
brotli-size

### ISSUE THREAD

**Issue by oteoe** [developit/microbundle#1046]
Brotli-size uses g++ or binary preinstalls, this makes this project harder to deploy to legacy systems

**Comment by rschristian** [comment]
Does it? I'm hardly familiar with it, or the native system in general when it comes to Node, but `binary-size` looks to just be leveraging `node:zlib`, a built-in? I'm not sure where preinstall would come into play.

But in any case, I'm not sure there's much we can do about that. Providing Brotli size is rather important as it is becoming the de facto compression algo for the web.

**Comment by rschristian** [comment]
Going to close this out, I don't think there's anything actionable for us here.
