### ISSUE TITLE
Install only necessary bundling dependencies

### ISSUE THREAD

**Issue by ksenginew** [developit/microbundle#1048]
currently microbundle installs a lot of dependencies with it.

https://github.com/developit/microbundle/blob/105a09b9aa686ac46dc728e774d7ae3aef00aed8/package.json#L70-L113

but some of these are not useful for some users as they don't use that things in their package.
As an example:- for a JavaScript library without any typescript code doesn't require typescript tslib of any other typescript related build tools. so it would be bedder if you can mark these dependencies as optional with [peerDependenciesMeta](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#peerdependenciesmeta) option. this would make small install times and faster builds.

Thank you for this great project. I would be like to make a pr for this improvement.

**Comment by rschristian** [comment]
> this would make small install times and faster builds

Any benefit from fewer deps is almost certainly offset by the poor DX that is users needing to wrangle peerDeps if they want Microbundle to build CSS or TS.

Build times shouldn't be affected in any way.

**Comment by ksenginew** [comment]
@rschristian I think installing packages like typescript is useless for a pure js codebase. Anyway thanks for the clarification. 😸

**Comment by rschristian** [comment]
I'm going to close this out as I don't think it's something worth pursuing.
