### ISSUE TITLE
Alias API

### ISSUE THREAD

**Issue by jaredpalmer** [developit/microbundle#105]
Working on a `react-native-web` component that I'd love to build with microbundle. Would you be open to a PR allowing an `alias.json` file that looked like: 

```
{
   'react-native': 'react-native-web'
}
```

**Comment by Andarist** [comment]
Is `alias.json` used by any other tool? webpack supports [`aliasFields`](https://webpack.js.org/configuration/resolve/#resolve-aliasfields) which is supposed to adhere to browser field specification. 

There is a high chance that it would already work if you setup `browser` field in your package.json and make `microbundle` to use that field based on [this condition](https://github.com/developit/microbundle/blob/e58b82b6816dde28e2402fffcec47c6958361818/src/index.js#L251).

**Comment by jaredpalmer** [comment]
Can you give me an example snippet of package.json / npm script that would do this?

**Comment by Andarist** [comment]
Ok, it seems that this is not possible from the project level (I thought it is) - this alias field can only be specified in the package that is imported.

We need to figure out an alias format then, have you seen your proposed `alias.json` anywhere?

**Comment by developit** [comment]
I'm thinking maybe we could support an `"aliases"` key in the package.json that follows the format @jaredpalmer described.

**Comment by Andarist** [comment]
Slight problem with that is that we might want to support outputting bundles targeting different platforms - like node, browser, react-native and unfortunately a single/simple `aliases` field in package.json would make that hard, because the proposed format is flat and global for the project (because it's in package.json).

**Comment by jviide** [comment]
Does #315 ("Add support for --alias") that was released as a part of v0.10.1 address this?

**Comment by developit** [comment]
@jviide yup!
