### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by artooras** [developit/microbundle#1055]
Hi. This may be a silly question, but why doesn't microbundle resolve `process.env.MY_VAR` that I place in my `.env.local` file during the build process? In the build files it remains as `process.env.MY_VAR`.

**Comment by rschristian** [comment]
It's not replaced as we do not read any of your `.env` files. Instead, check out the docs for the `--define` flag:

**Comment by artooras** [comment]
I see, thanks for the pointer @rschristian!

**Comment by rschristian** [comment]
Going to close this out, nothing actionable for Microbundle. Feel free to respond if you have any further questions though
