### ISSUE TITLE
Build for React Server Components

### ISSUE THREAD

**Issue by tats-u** [developit/microbundle#1060]
https://github.com/reactjs/rfcs/blob/main/text/0227-server-module-conventions.md#react-server-conditional-exports

React Server Components seem to require independent source (e.g. `useState` is not allowed) and requires `"react-servers"` in `"exports"` in `package.json`.

Microbundle doesn't seem to support this currently.

**Comment by rschristian** [comment]
- You can simply map `"react-servers"` to Microbundle's (existing) output, I don't think we should do anything different for arbitrary export conditions, personally.

**Comment by tats-u** [comment]
> Not quite sure why you brought this up though, what do you expect Microbundle to do about this? Seems to be a user-code issue?

The project I want to add the RSC support uses this project. It uses `useState` as of now.

**Comment by rschristian** [comment]
Then remove the `useState`?

**Comment by tats-u** [comment]
@rschristian It's bad. It does not render anything at first, but generates what should be rendered in useEffect and then rewrites the content. This is ideal in the client side.
And it's not my project.
As far as your response, this doesn't seem to be the use case you're envisioning.

**Comment by tats-u** [comment]
> I don't follow -- what's bad?

From the client-side perspective, `useEffect` and `useState` are necessary, so we have to split source.

Microbundle seems not to be for the project now. Thanks.

**Comment by rschristian** [comment]
Indeed, but we're not the ones who wrote the RSC spec, not sure what you'd like us to do about it.

Again, a Babel plugin to strip out hooks could be another approach (then you'd just run Microbundle twice, once for the client component output and another time for the server) though I'm not sure if anyone's made that. Might be worth looking at other projects to see how they handle it.

I'll close this out as I don't think there's anything for us to address but if you do have any Microbundle-specific questions in the future feel free to ask.
