### ISSUE TITLE
Wrong "import" in UMD bundle of UMD package 

### ISSUE THREAD

**Issue by stereobooster** [developit/microbundle#1064]
I converted `itemsjs` to ES modules and use microbundle to bundle it for npm. ES bundle works ok. But umd bundle throws an error

```
Uncaught TypeError: u.default is not a function
```

I checked generated UMD, it seems `u.default` is referring to `lunr`. [lunr](https://www.npmjs.com/package/lunr/v/1.0.0?activeTab=code) itself is published as UMD. I guess this is an issue, but hard to tell

```
git clone https://github.com/stereobooster/itemsjs
git checkout js
npm ci
npm run build
```

Related: https://github.com/itemsapi/itemsjs/pull/135

**Comment by rschristian** [comment]
That shouldn't be an issue, so long as `lunr` is distributed/attached to the window with that name.

Are you importing `lunr` before `itemsjs`? You've seem to leave out the actual reproduction of the issue.

**Comment by stereobooster** [comment]
Sorry, my bad. I should have posted it right away.

```
git clone https://github.com/stereobooster/itemsjs
git checkout js-umd-bug
npm ci
npm run build
open bug.html
```

**Comment by stereobooster** [comment]
Oh. I didn't realized that. Thank you. I will try it

**Comment by rschristian** [comment]
Just to clarify, in UMD, dependencies are expected to exist on the global -- `window.lunr` and the like. Without inlining, this means that script needs to be loaded first, like this:

```html
<script src="./lunr.js"></script>
<script src="./my-lib.js"></script>
```

And so on for every dep. this allows them to attach to the global, and your script to access them after they've done so.

`lunr` is simply the one that gets accessed first, from the sounds of it. They'd all fall over in the same way.

**Comment by stereobooster** [comment]
Yeah I got it. Thanks. As soon as you wrote, about dependencies it all clicked. It totally makes sense, I just haven't thought of it earlier

**Comment by stereobooster** [comment]
Everything works as expected. Thank you for the help

**Comment by rschristian** [comment]
Glad to hear it! Let me know if you run into any further issues.
