### ISSUE TITLE
打包后的产物 x.moduel.mjs 存在箭头函数，导致IE 无法兼容

### ISSUE THREAD

**Issue by hduhdc** [developit/microbundle#1065]
打包后的产物 x.moduel.mjs 存在箭头函数，导致IE 无法兼容
Object.keys({name:1}).forEach(key => {
     console.log(key)
  });
打包后结果
`Object.keys({name:1}).forEach(e=>{console.log(e)});
//# sourceMappingURL=test-microbundle.modern.mjs.map`

**Comment by rschristian** [comment]
This is correct behavior. The modern output is ES2017: https://github.com/developit/microbundle#-modern-mode-

**Comment by hduhdc** [comment]
> This is correct behavior. The modern output is ES2017: https://github.com/developit/microbundle#-modern-mode-
> 
> If you really need IE support, use CJS, ESM, or UMD outputs. Modern is specifically for dropping the baggage those formats ship with.

当存在 index.mjs 和 index.js 这种同名不同后缀的文件时，import  './index' 或者 require('./index') 是会优先加载 index.mjs 文件的。那就会直接使用了modern 产物

**Comment by rschristian** [comment]
Please use English, I don't understand what you're trying to say.

**Comment by hduhdc** [comment]
> Please use English, I don't understand what you're trying to say.
I know my mistake，if my packge is foo，when i use `import foo from 'foo '`  
 If the configuration of my package. json is as follows
"exports": {
    
    "default": "./lib/foo.js" 
  },
Is it possible to avoid using it by default `./lib/modern.mjs`
