### ISSUE TITLE
prevent export merge

### ISSUE THREAD

**Issue by orangebokov** [developit/microbundle#1075]
Good afternoon, i'm asking for a little help.

If i have `index.ts` like this:

    export { Monoid } from 'fp-ts/string'
    export function sum(a: number, b: number) {
      return a + b;
    }

Then bundle `index.esm.js` will be something like this:

    var Monoid = {
        concat: Semigroup.concat,
        empty: empty
    };
    function sum(a, b) {
      return a + b;
    }
    export { Monoid, sum };

How to keep exports individual in bundle like this:

    export var Monoid = {
        concat: Semigroup.concat,
        empty: empty
    };
    export function sum(a, b) {
      return a + b;
    }

Thank you very much in advance!

**Comment by rschristian** [comment]
Sorry, what are you after? The last two code blocks are functionally identical.

**Comment by orangebokov** [comment]
Thanks for the answer. 

Then when you import this library into the main project and build the main project using `rollup`,  tree shaking will not work. 
Because all functions will be stored in one variable.
If they are exported separately, tree shaking will remove the unused ones. 

P.S. There will be many functions in this library. many of them will not be used. I wish rollup didn't export them.

**Comment by rschristian** [comment]
> Because all functions will be stored in one variable.

That's not what this is.

`export { foo, bar }` is the exact same thing as `export foo ... export bar`, but it's just shorter and saves a few bytes. It's exporting a list of values, not merging them together. MDN is a good resource for this sort of thing: https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export

This isn't an issue here. If treeshaking isn't working, it's for other reasons.

**Comment by orangebokov** [comment]
Thank you for paying attention to this.
All the best to you.

**Comment by rschristian** [comment]
No problem, and if you do find an issue w/ Microbundle's output I'd be happy to reopen this & look at it.
