### ISSUE TITLE
How to bundle public folder to dist

### ISSUE THREAD

**Issue by yenle16** [developit/microbundle#1080]
I am developing a preact widget project, in my publice/assets folder there are svg files to use in the project, when I run build, how can this public folder be in the dist folder?
  `  "build:widget": "cross-env PREACT_APP_API_URL=$PREACT_APP_API_URL microbundle build --no-sourcemap --external none --define process.env.PREACT_APP_API_URL=$PREACT_APP_API_URL"`

**Comment by rschristian** [comment]
Microbundle does not support this, you'll need to add in a copy step yourself:

`"build:widget": "cross-env PREACT_APP_API_URL=$PREACT_APP_API_URL microbundle build --no-sourcemap --external none --define process.env.PREACT_APP_API_URL=$PREACT_APP_API_URL && cp public/assets dist/"`

**Comment by yenle16** [comment]
So that's it. Thank you
