### ISSUE TITLE
watch mode stops without watching

### ISSUE THREAD

**Issue by tleunen** [developit/microbundle#111]
While `microbundle build` works perfectly fine, I'm not sure what to expect from the `watch` mode.

Currently, it gives me this, and then stops and goes back to the terminal input.
```sh
> microbundle watch
Watching source, compiling to dist:
[object Object]
```

**Comment by cvan** [comment]
I have encountered the same error. whenever I see that message, I run `microbundle build` and I see some `SyntaxError` that gets printed out.

I assume this is a bug and the `[object Object]` probably contains an error whose message and stack could be printed to the console.

I will file a separate issue for a feature request to expose these errors in a JSON-readable format so they can be logged (and perhaps passed to an active local page served by a local-dev server like `microenvi` in the browser, à la [`budo`](https://github.com/mattdesl/budo/blob/master/README.md)).

**Comment by developit** [comment]
The culprit:
https://github.com/developit/microbundle/blob/master/src/cli.js#L12

**Comment by mattdesl** [comment]
+1 Also hit by this.

(By the way, this tool is great. I'm using it alongside budo as well for now to create browser modules.)
