### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by thiamsantos** [developit/microbundle#116]
Would be great to add option to prepend a banner on the bundle, maybe using [rollup-plugin-license](https://github.com/mjeanroy/rollup-plugin-license) on something similar.

**Comment by ForsakenHarmony** [comment]
Can I ask why you'd need this?

**Comment by thiamsantos** [comment]
I usually don't use this feature. But, some library authors like to use it. I think that may be useful to make easy the migration from others tools to microbundle, not requiring to stop using a banner to do the migration.

**Comment by developit** [comment]
Problem would be that it conflates the filesize.  I think if we do this and the resulting banner'd file is measured for size, we should strip the comment when calculating.

**Comment by ForsakenHarmony** [comment]
I think we should remove minification in the bundle by default anyways

maybe run uglify in memory

**Comment by Andarist** [comment]
@ForsakenHarmony :+1: minification makes it harder to debug minified dependencies. Most common use case is to uglify with a bundler later - when building application. IMHO the only format that could be minified by default is UMD.

Minifying "in memory" just to report size is IMHO also a good idea.

I hope to prepare a PR for this (& more) soon-ish, planning to do it for so long already :s just not having enough time lately.

**Comment by developit** [comment]
seems a shame to minify in-memory just to report size though. Why not write the files to disk as `.min.js`?  That way the library author can choose when they are specifying their package.json main fields.

**Comment by ForsakenHarmony** [comment]
It's already a flag, but I think off would be the better default but we'd still want the size Output

**Comment by developit** [comment]
tbh that depends whether you're using microbundle for web or node. we have the --target option, so we already know the answer in most cases. I use it a lot more for web, where optimize should be on by default.

**Comment by xavierfoucrier** [comment]
Hi everyone,

How about implementing this feature?
Thanks for the feedback :wink:
