### ISSUE TITLE
Allow fully customizable output file name or omitting format suffix

### ISSUE THREAD

**Issue by amio** [developit/microbundle#122]
Thanks for this cute bundler!

I'm using it for bundling a userscript, userscripts has a naming convention to end file name with `*.user.js`, as it‘s supposed to running in browser, so I use `umd` format, but that would add a `.umd` suffix to filename, finally I got a `script-name.user.umd.js`.

Is there a way to omit format suffix when only output a single format? Or let user choose filename format?

**Comment by developit** [comment]
I believe you can specify `"umdMain"` in the package.json for this.

**Comment by amio** [comment]
Oops I just realize it's just sit in the README.md 😅
Thanks!
