### ISSUE TITLE
Error: Plugin 'dynamicImport' not found

### ISSUE THREAD

**Issue by developerdizzle** [developit/microbundle#123]
```
PS C:\Users\Dizzle\Documents\GitHub\stata> microbundle
Error: Plugin 'dynamicImport' not found
```

This is happening to me on https://github.com/developerdizzle/stata

Some details:
 - Windows 10 x64
 - npm@4.0.5
 - node 9.4.0

I noticed https://github.com/developit/microbundle/issues/74 was somewhat similar so I tried using yarn but it still doesn't seem to work.  Any ideas?

**Comment by developit** [comment]
Hmm.  Might be an issue with the latest rollip version.

**Comment by developerdizzle** [comment]
I tried installing `rollup@0.55.1` (exact version) as a devDependency, but it didn't seem to change anything.

**Comment by fiedler** [comment]
I'm experiencing the same issue with a clean project with only microbundle installed.

MacOS 10.13.4
npm 5.6.0
node 9.9.0

By downgrading to `microbundle@0.4.2` I can build again. It seems to be related to `rollup-plugin-nodent`.

**Comment by fiedler** [comment]
It seems to be caused by the `onParserInstallation` hook being removed in version 3.2.0 of `nodent-compiler` which `rollup-plugin-nodent` is using to patch acorn to support dynamic imports.

I guess an issue should be created for either `nodent-compiler` or `rollup-plugin-nodent`. I'm not sure which package a change should be performed in though. Happy to help out though.

Ping @oligot and @MatAtBread

**Comment by MatAtBread** [comment]
That's a bug. I'll patch and re-publish this afternoon. If it's breaking production stick to 3.1.x

**Comment by matAtWork** [comment]
Apologies. This is now (hopefully) fixed in nodent-compiler@3.2.1. The cause was a dodgy merge from a branch I'd been working a while back

**Comment by fiedler** [comment]
Works for me now. Thanks :+1:

**Comment by developerdizzle** [comment]
Same here; thank you @matAtWork (or wherever you currently are) !

**Comment by developerdizzle** [comment]
@matAtWork @MatAtBread any chance a regression happened?  I'm seeing this again.  https://github.com/developerdizzle/react-virtual-list/blob/microbundle/package.json

`nodent-compiler@3.2.6` is being installed

**Comment by matAtWork** [comment]
Apologies for the delay - I've been away.

Short answer - if it is it's subtle. The `onParserInstallation` is present in 3.2.6 at https://github.com/MatAtBread/nodent-compiler/blob/657bc9794818e477a9b4a2d1e1a08742c4d02ae1/compiler.js#L30

Do you know if it's being called?
