### ISSUE TITLE
Possible bug with transforming static class properties

### ISSUE THREAD

**Issue by developerdizzle** [developit/microbundle#125]
This works in parcel via babel, but not here:
```
SyntaxError: Unexpected token (10:19) C:\Users\Dizzle\Documents\GitHub\react-virtual-list\src\VirtualList.js (nodent)
  static propTypes = {
-------------------^
```

Is this a buble or nodent issue, or something else I might be missing?

Using `microbundle@0.4.4`

**Comment by thiamsantos** [comment]
That's probably happening because [buble](https://github.com/Rich-Harris/buble) doesn't support class properties.

**Comment by developerdizzle** [comment]
> That's probably happening because buble doesn't support class properties.

Welp... you got me buble

![](https://i.imgur.com/terjMnH.jpg)

Guessing this will be addressed in the future by the [switch to babel](https://github.com/developit/microbundle/pull/39) ?

**Comment by developit** [comment]
Yup! (also +1 for art reference haha)

**Comment by zzswang** [comment]
any update now ?

still not support class-properties?

**Comment by zzswang** [comment]
fixed in version ^0.11

**Comment by marvinhagemeister** [comment]
@zzswang transformation of class properties should be supported in the latest release

**Comment by zzswang** [comment]
@marvinhagemeister 

Thank you, yes it is fixed in the latest version.
