### ISSUE TITLE
--sourcemap option can't be disabled?

### ISSUE THREAD

**Issue by developit** [developit/microbundle#138]
There doesn't seem to be a way to disable sourcemaps using the existing option. None of these work:

```
--sourcemap=false
--sourcemap false
--sourcemap 0
--sourcemap=0
```

/cc @lukeed

**Comment by lukeed** [comment]
Sorry to ask, but are you on latest? 😆 

Just re-built Sockette on `0.4.4` and the following options work:

```
$ yarn build --no-sourcemap
$ yarn build --sourcemap false
```

**Comment by developit** [comment]
Never did, but I just rolled with the sourcemaps lol

**Comment by developit** [comment]
This is working for me now.
