### ISSUE TITLE
Behavior with scoped packages

### ISSUE THREAD

**Issue by bebraw** [developit/microbundle#14]
Suppose I have

```json
{
  "name": "@bebraw/schnitzel",
  "version": "0.0.0",
  "description": "",
  "main": "src",
  "scripts": {
    "build": "microbundle",
    "dev": "microbundle watch"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "microbundle": "^0.2.3"
  }
}
```

and **src/index.js**.

If I run `npm run build`, it generates `src/@bebraw`.

Is that expected?

**Comment by developit** [comment]
Ack! Need to basename the `name` value [here](https://github.com/developit/microbundle/blob/master/src/index.js#L157).

**Comment by wcastand** [comment]
it's resolve with the last update no ?
https://github.com/developit/microbundle/releases/tag/0.2.4

**Comment by developit** [comment]
No.

**Comment by developit** [comment]
@bebraw ah - it looks like it messed up because your `main` field was pointed at src.  `main` should point to the commonjs bundle target filename in dist:

```js
{
  "main": "dist/schnitzel.js"
}
```

I've verified this locally.

**Comment by bebraw** [comment]
Ok, makes sense. 👍
