### ISSUE TITLE
Reason support

### ISSUE THREAD

**Issue by geoffreydhuyvetters** [developit/microbundle#141]
Would it make sense to support Reason (.re files) via https://www.npmjs.com/package/rollup-plugin-bucklescript? 
Analog to how we handle TypeScript now.

I think I could create a PR for this.

If not I'm more then happy to do this in a fork, I want to create a small module with Reason as an experiment.

**Comment by Andarist** [comment]
I guess it would make some sense, I have 0 experience with Reason though. Keeping bucklescript compiler as dependency would probably increate the installation size quite a bit, right? Would keeping it as optional dependency work for u? 

If you plan to work on this, please send up a PR and we'll be able to discuss further under it seeing what changes were required to the codebase.

**Comment by duivvv** [comment]
The rollup plugin handles it in the same way, you have to install bsb-platform yourself.

I do think we should provide a default `bsconfig.json` see (https://github.com/shrynx/rollup-plugin-bucklescript#rollup-plugin-bucklescript)

**Comment by Andarist** [comment]
The only thing that I would suggest at this point is to:
- check if there are any reason files in the project directory and use the plugin conditionally
- validate if there is `bsb-platform` installed & throw with a helpful error message if it is not

**Comment by developit** [comment]
That seems like a nice approach.

**Comment by texastoland** [comment]
🤞🏽 I'll take a shot this weekend.

**Comment by marvinhagemeister** [comment]
Closing, looks like there hasn't been much interest in getting this into `microbundle`. We're happy to review PRs if somebody wants to add it :+1:
