### ISSUE TITLE
Support for different output directories

### ISSUE THREAD

**Issue by alexkrolick** [developit/microbundle#157]
For example

```
"main": "dist/index.js", <- dist directory
"umd:main": "dist/index.umd.js", <- dist directory
"module": "lib/index.js", <- lib directory
"js:next": "es/index.js", <- es directory
"source": "src/index.js",
```

Right now it seems to put all the files in whatever folder `main` is pointing to

**Comment by developit** [comment]
would be good, yup. I think I proposed a mapping structure a while back, but then there's also the (nicer?) option of producing directories containing nested `package.json` to disambiguate.
