### ISSUE TITLE
Empty output and no error message

### ISSUE THREAD

**Issue by weslleyaraujo** [developit/microbundle#158]
Hi folks! 👋

I am trying to setup microbundle for my project, but looks like I am missing something 😅

Nothing comes out of the output for `microbundle build`, as for `microbundle watch` the process just dies (with no error message either)

```bash
⟩ yarn run start
yarn run v1.5.1
$ microbundle watch
Watching source, compiling to dist:
✨  Done in 1.35s.


⟩ yarn run build
yarn run v1.5.1
$ microbundle
Build output to dist:

✨  Done in 1.14s.
```

I have the following setup in my `package.json` :

```json
{
  "main": "dist/index.js",
  "umd:main": "dist/index.umd.js",
  "module": "dist/index.m.js",
  "source": "src/index.js",
}
```

btw, this project uses `// @flow`, not sure if its related at all

**Comment by developit** [comment]
Hi there - skip `build`, it's just `microbundle`. I think adding build there is looking for `build.js`.

**Comment by ForsakenHarmony** [comment]
might want to try again with the new version, has some fixes with error reporting

**Comment by weslleyaraujo** [comment]
Nice! I will give it a try with the latest version 😃

**Comment by developit** [comment]
It might be worth us adding a `build` command just to catch this case and report a friendly error. Definitely some weird output.  Or we could detect the case where no input files are matched and print something saying "no entry files matched".

**Comment by ForsakenHarmony** [comment]
Nice :+1:
