### ISSUE TITLE
Only works with es module dependencies?

### ISSUE THREAD

**Issue by jescalan** [developit/microbundle#17]
It looks like an option is explicitly set to make only es module dependencies included. In practice, it assumes any non-es-module dependency is "external" and doesn't bundle it. Just curious about the rationale behind this choice? It really limits the utility of this tool, as most libraries still don't export an es module version at this point.

https://github.com/developit/microbundle/blob/master/src/index.js#L195

**Comment by caiogondim** [comment]
Same for me.
Most of my libraries are node/browser compatible.
Would like to have `require` for Node, and a compiled build for the browser.

**Comment by developit** [comment]
That was done in order to prevent bundling in already-bundled dependencies from node_modules.  Seems like we might need to revisit.

**Comment by jescalan** [comment]
Happy to help out with a PR with your approval!

**Comment by caiogondim** [comment]
Same here

**Comment by developit** [comment]
Yup, PR would be great!
