### ISSUE TITLE
Handling for..of with Sets and Maps

### ISSUE THREAD

**Issue by pshihn** [developit/microbundle#172]
`for..of` in a Set gets transformed to use the `length` property which is not defined.

e.g:
```javascript
const set = new Set(['a', 'b', 'c']);
for (const s of set) {
  console.log(s);
}
```

Gets transformed into:
```javascript
for (var i = 0, list = set; i < list.length; i += 1) {
  console.log(list[i]);
}
```

(This is likely a babel bug)

**Comment by ForsakenHarmony** [comment]
https://buble.surge.sh/guide/#-dangerousforof-

it's not supported by buble, but we might switch to babel at some point

**Comment by developit** [comment]
FWIW I recall the transpiled code for this is hideous

**Comment by ForsakenHarmony** [comment]
probably less with loose transforms
