### ISSUE TITLE
Strange build output

### ISSUE THREAD

**Issue by alexlafroscia** [developit/microbundle#18]
I happened to hear about `microbundle` a day or so ago so I decided to try it on a tiny library I was hacking on. The output seems really weird, though:

```javascript
function t(t){return new Proxy(t,{get:function(t,r){return r in t?t[r]:e.lookup(r)}})}var r=function(){this.reset()};r.prototype.register=function(t,r){this._registry.set(t,r)},r.prototype.lookup=function(t){return this._registry.get(t)},r.prototype.reset=function(){this._registry=new Map};var e=new r,n=function(){return t(this)};n.extend=function(r){return function(r){function e(){return r.call(this),t(this)}return r&&(e.__proto__=r),e.prototype=Object.create(r&&r.prototype),e.prototype.constructor=e,e}(r)},exports.registry=e,exports.RegistryAccess=n;
//# sourceMappingURL=index.js.map
kup(prop);
        }
    });
}

var RegistryAccess = function RegistryAccess() {
    return registerForAccess(this);
};
RegistryAccess.extend = function (Klass) {
    return (function (Klass) {
        function anonymous() {
            Klass.call(this);
            return registerForAccess(this);
        }

        if ( Klass ) anonymous.__proto__ = Klass;
        anonymous.prototype = Object.create( Klass && Klass.prototype );
        anonymous.prototype.constructor = anonymous;

        return anonymous;
    }(Klass));
};

export { registry, RegistryAccess };
//# sourceMappingURL=index.js.map
```

That's the contents of the `dist/index.js` file that is output. It doesn't even seem like valid JS syntax after the first `sourceMappingURL` comment. 

You can clone and try it yourself here:

https://github.com/alexlafroscia/service-locator

**Comment by alexlafroscia** [comment]
Additionally, I'm getting `index.js` in the build output twice? Maybe that's related?

<img width="203" alt="screen shot 2017-12-13 at 4 06 17 pm" src="https://user-images.githubusercontent.com/1645881/33968954-a3e430ea-e01f-11e7-9739-40b22619f00e.png">

Kinda seems like `index.js` is written once, and then a second time where the second time overwrites some number of initial bytes but doesn't actually blow away the whole file.

**Comment by alexlafroscia** [comment]
If I turn off compression, I still get two `index.js` outputs. The second one is actually slightly larger (?) but the output in the file is at least valid

<img width="223" alt="screen shot 2017-12-13 at 4 09 29 pm" src="https://user-images.githubusercontent.com/1645881/33969048-14b4fa66-e020-11e7-9934-2e3bf4b4ba6f.png">

**Comment by developit** [comment]
Hmm - can you post your `package.json` with scripts and dependencies stripped out?

**Comment by alexlafroscia** [comment]
```json
{
  "name": "service-locator",
  "version": "1.0.0",
  "description": "Serice locator pattern for ES6 classes",
  "main": "lib/index.js",
  "license": "MIT",
  "module": "lib/index.js",
  "main": "dist/index.js"
}
```

**Comment by alexlafroscia** [comment]
Here's the relevant commit -- since that commit, I switched over to `rollup` which isn't having any issues (but also doesn't minify or anything).

https://github.com/alexlafroscia/service-locator/tree/eb56fee3cbd0299ad528c09763d951b495fd3a2e

**Comment by developit** [comment]
Hmm - `module` should point to `dist/index.es.js`.

**Comment by alexlafroscia** [comment]
Alright, I'll try that out.

Out of curiosity, is the right way to configure `main` and `module` documented somewhere? I just kind of guessed as to what their values were supposed to be 😅

**Comment by alexlafroscia** [comment]
I updated the `package.json` to this:

```json
{
  "name": "@alexlafroscia/service-locator",
  "version": "1.1.0",
  "description": "Serice locator pattern for ES6 classes",
  "main": "dist/index.js",
  "license": "MIT",
  "module": "dist/index.es.js",
  "files": [
    "dist",
    "lib"
  ]
}
```

But now I get the error:

> Error: ENOENT: no such file or directory, open '/Users/alexlafroscia/Code/javascript/service-locator/dist/index.es.js'

**Comment by alexlafroscia** [comment]
I took a look at the `package.json` for this repo and noticed you had set the `source` property. I added that to mine and, lo and behold, it works now 🎉 

Unfortunately, I think the way that Buble transpiles my ES6 classes breaks some of my tests, so I'll have to stick with `rollup`. Would you be interested in a PR that makes the documentation on project setup a little more clear?

**Comment by alexlafroscia** [comment]
I've run into weird issues with tools that transpile ES6 classes. As you may have come across yourself, either everything has to leave them be, or everything has to transpile them the same way. My test runner (`ava`), for example, does not transpile them. `microbundle` does, by default, meaning that anything looking to consume them as regular ES6 classes gets tripped up because they're no longer compatible with each other.  An example of what that looks like can be found here (this test fails when build with `microbundle` but passes with `rollup`.

https://travis-ci.org/alexlafroscia/service-locator/jobs/316777539#L500-L502

I'd actually love to get your take on this, as someone that publishes lots of micro-libs: what are your thoughts on transpilation of dependencies? I kind of feel like as much as possible, dependencies should really provide their `dist` as close to the original source as possible (in my case, leaving ES6 classes alone) and allow the consumer to transpile them if they so choose.

**Comment by developit** [comment]
I think #24 may address your thoughts on this, since it'll bundle in things from node_modules.

**Comment by alexlafroscia** [comment]
Cool. We can close this issue since we got to the bottom of the problem.

Regarding the PR I offered to make, I was a bit intimidated by the code. It seems like some assumptions are made if there isn't `main/module/source` supplied. Would you rather throw an error in those cases?

**Comment by developit** [comment]
I think missing we already handle gracefully - we should just add sanity checks for when those properties are supplied but the values are problematic.  I'm thinking something like if `module` or `main` point to the same directory as the resolved source (entry).
