### ISSUE TITLE
Feature Request:  replace/define constants

### ISSUE THREAD

**Issue by developit** [developit/microbundle#181]
#### Usage:

```
microbundle --define NODE_ENV=production
```

#### Result:

input:

```js
if (NODE_ENV==='production') {
  console.log('prod');
}
else {
  console.log('dev');
}
```

output with `--define NODE_ENV=production`:

```js
console.log('prod')
```

All we have to do is use [rollup-plugin-replace](https://github.com/rollup/rollup-plugin-replace) to injec the value. Uglify handles the rest.

**Comment by ForsakenHarmony** [comment]
creator makes a feature request 👀

**Comment by Andarist** [comment]
Not sure if you like the idea but ive written this - https://github.com/Andarist/rollup-plugin-dotenv . Inspired by CRA which uses .env files to keep env vars organised

**Comment by developit** [comment]
@Andarist looks nice - it also supports inlining regular env vars?  Could always have both.

**Comment by developit** [comment]
lol @ForsakenHarmony it was more of a "what do y'all think of this?" :P

**Comment by Andarist** [comment]
> @Andarist looks nice - it also supports inlining regular env vars? Could always have both.

It doesn't - mainly because:
- without special casing (like ur `--define` proposal) it's hard to tell which env vars should be used and I didnt want to include everything that can be found on `process.env`
- when bundling libraries I don't want to have `NODE_ENV` replaced (leaving that to consumers, so a library can differentiate between dev/prod code paths)

It does support overriding with env vars what is specified in .env files though.

**Comment by developit** [comment]
Makes sense. That being said, rollup's syntax is pretty much what I'm in need of - I have 2 builds from the same source, but want to define a variable that changes the output.  Basically something like `#ifdef`:

```js
// a bunch of these
if (PRETTY) {
  // whitespace handling stuff here
}
```

```js
microbundle --define PRETTY=true && microbundle --define PRETTY=false
```

**Comment by Andarist** [comment]
if u have bunch of such variables (btw what they are? if thats not a mystery) it's imho good to gather them in .env files (which can act like a presets of different sets of those vars)

in the future i'd like to add special env vars to microbundle (need to rethink how it should work exactly) - such as REACT, PREACT, SERVER, NATIVE, BROWSER - multiple bundles could be outputted based on used `package.json` keys or smth.

I understand though that for other use cases than those from last paragraph and when having just 1 or 2 variables it's easier to use `--define` than creating .env files. Although I don't like rollup's syntax I'd prefer using it just to align to it as microbundle is built on top of rollup anyway and should be easier to explain this option (we could link to rollup's docs).

**Comment by balloob** [comment]
I came here to see if this feature existed 👍 Would love it. 

To keep it simple, you could use `--replace` instead of `--define` to indicate that we're doing variable replacement and that it's not related to environment variables. Otherwise people might also expect that they can check against `process.env.NODE_ENV`.

**Comment by developit** [comment]
I'm fine with the `.env` files, just it seems like it would make sense to support both. Presumably there's already a way to hydrate environment variables from a `.env` file like `load-from-env .env microbundle`?

**Comment by kutuluk** [comment]
In my opinion this should have been done in the initial release. Tell me, please, how can I implement this manually, until this feature is implemented?

**Comment by kutuluk** [comment]
Can define through a .js file:

config.env
```
HOST=localhost
```

defines.js
```javascript
import dotenv from 'dotenv';

dotenv.config();

export default defines => {
	defines.PRETTY = true;
	defines.HOST = process.env.HOST;
	defines.DEVELOPMENT = process.env.NODE_ENV === 'development';
};
```

**Comment by balloob** [comment]
One thing to be cautious of is that if you expose all environment variables, one could accidentally leak credentials if they have just `process.env` in their code. Create React App requires env variables to be prefixed with `REACT_APP_` for this reason.

**Comment by CrashyBang** [comment]
Hey @developit I notice `--define` has been added, is it possible to define these values from an `.env` file?

**Comment by developit** [comment]
Not currently, no.
