### ISSUE TITLE
UMD dependencies

### ISSUE THREAD

**Issue by Ayc0** [developit/microbundle#184]
When you're working on UMD build, if you're using an external module, the name microbundle uses to import this module can be different from the one the module truly uses.

For instance, React exports window.React but microbundle wants to use window.react.

Can we change it?

**Comment by Ayc0** [comment]
(for now, I'm fixing it with `sed -i -- 's/t.react/t.React/g' $npm_package_umd_main` after the build command)

**Comment by ForsakenHarmony** [comment]
wait why would you use global react

**Comment by Ayc0** [comment]
If you're using a script tag, you need to have a global react package

But it was only an example

**Comment by developit** [comment]
yup yup. I had thought for some reason that Rollup had mappings for common names like `react:React`.  I hate to add configuration, but it's probably the only way forward here. Thanks for your PR!
