### ISSUE TITLE
Question: Differences from Parcel

### ISSUE THREAD

**Issue by anurbol** [developit/microbundle#185]
Hi there! Thank you for another great library. I honestly can't wait for the time when webpack and similar old frankensteins die and modern bundlers arise. Is there any guide on pros and cons of Microbundle against Parcel? If not, could anyone tell? Thanks!

**Comment by ForsakenHarmony** [comment]
microbundle is for libraries and probably has a lot less features

I wouldn't call webpack an "old frankenstein" or microbundle a "modern bundler", it's rollup with a nice preset

**Comment by anurbol** [comment]
@ForsakenHarmony Oh, "rollup with a nice preset" is a very short and on-point description. I didn't knew that. Know that I looked to package.json I can see it :smile: Thank you for the answer! I am also agree that Webpack is not a Frankenstein. It's really worse than than (Shitstein?). But that's another story :-)
