### ISSUE TITLE
Support TypeScript 3

### ISSUE THREAD

**Issue by texastoland** [developit/microbundle#191]
I've been using it no problems with a [Yarn selective resolution](https://yarnpkg.com/en/docs/selective-version-resolutions/). At some point I think `package.json` should be updated to `"typescript": "^2.8.3 || ^3.0.0"`. Would @ezolenko need to update rollup-plugin-typescript2's peer dependency first? I patched https://github.com/eslint/typescript-eslint-parser/commit/f1d7de30492183574cd9376953b2cadcaf9add86 and can confirm none of the snapshots in their integration tests needed to change at all.

**Comment by ezolenko** [comment]
My stuff seem to be fine with ts 3.0.1, self builds at least. Peer dependency is set as `"typescript": ">=2.4.0"` so shouldn't produce any warnings.

**Comment by texastoland** [comment]
That's a smarter range thank you @ezolenko!

**Comment by ForsakenHarmony** [comment]
Feel free to create a pr
