### ISSUE TITLE
Error compiling index.ts

### ISSUE THREAD

**Issue by texastoland** [developit/microbundle#193]
```
Error: Could not load .../src/index.ts.js 
(imported by .../node_modules/microbundle/src/lib/__entry__.js): 
ENOENT: no such file or directory, open '.../src/index.ts.js'
```

1. TS is detected.
2. `./lib/__entry__.js` requires `index.ts`.
3. Node resolution rules add `.js`.
4. Latest `rollup-plugin-typescript2` gives same error.

I traced it to using named exports in TypeScript.

**Comment by chocolateboy** [comment]
<table>
    <tr><th align="right">microbundle</th><td>0.6.0</td></tr>
    <tr><th align="right">node</th><td>v10.11.0</td></tr>
    <tr><th align="right">OS</th><td>Linux (Arch)</td></tr>
</table>

I'm still getting this error (in [this repo](https://github.com/chocolateboy/jquery-sync-table-column-widths)). I haven't found a way to make the error go away if a default export is used, either on its own or in conjunction with a named export (named exports work fine on their own):

**Command**:

```sh
$ yarn run microbundle --no-sourcemap --format es,cjs --strict src/index.ts
```

**Output**:

> Error: Could not load src/index.ts.js (imported by node_modules/microbundle/src/lib/\_\_entry\_\_.js): ENOENT: no such file or directory, open 'src/index.ts.js'

**Comment by Fxlr8** [comment]
Still having this issue on v`0.7.0`

**Comment by chocolateboy** [comment]
https://github.com/developit/microbundle/issues/264
