### ISSUE TITLE
Wrong build name (Double .min)

### ISSUE THREAD

**Issue by ndelvalle** [developit/microbundle#205]
For some reason the bundle name is generated using doubles `.min` example:

`v-click-outside.min.min.umd.js` and `v-click-outside.min.min.umd.js.map`

npm script: `microbundle --entry lib/index.js --target browser --format umd --name v-click-outside`

**Comment by developit** [comment]
@ndelvalle what does your package.json look like? (in particular, any `main` fields like `umd:main`).

**Comment by ndelvalle** [comment]
Yep:

```
"main": "dist/v-click-outside.min.umd.js",
"umd:main": "dist/v-click-outside.min.umd.js",
```

You can take a look [here](https://github.com/ndelvalle/v-click-outside/blob/master/package.json)
Thanks for the help! 👍

**Comment by developit** [comment]
Does it work if you remove the `--name` CLI argument?

**Comment by ndelvalle** [comment]
Nop :(
Where does the build output name come from? I changed the package name, files name etc and the output is always de same.

**Comment by gaui** [comment]
Yup, same here. `--name` doesn't change output name.

```
$ foobar\node_modules\.bin\microbundle --entry src/index.tsx --output dist --target browser --format es --name barfoo
Build "barfoo" to dist:
        802 B: foobar.mjs
Done in 3.02s.
```

**Comment by ndelvalle** [comment]
Sometimes it gets worse, not sure if it is something related to my setup

<img width="611" alt="screen shot 2018-12-07 at 16 40 58" src="https://user-images.githubusercontent.com/6719053/49640069-28408200-fa3f-11e8-9846-59be1b209b12.png">

**Comment by LordotU** [comment]
@ndelvalle oh, man... seems you need to manualy review `dist/` output, cause files in current release `@next/@2.1.0-0` has double `.min` extension and cannot be resolved with simple:

```javascript
import vClickOutside from 'v-click-outside'
```

**Comment by ndelvalle** [comment]
Yeah @LordotU I'm still fighting with this issue :( A new release was deployed `v-click-outside@2.1.0-1`

**Comment by LordotU** [comment]
@ndelvalle I think, it is not your fight. :-) The Devil, I guess, somewhere here: between https://github.com/developit/microbundle/blob/f6ebebb1f81dfec9367e65f1448e5aba5777bcbc/src/index.js#L387 and https://github.com/developit/microbundle/blob/f6ebebb1f81dfec9367e65f1448e5aba5777bcbc/src/index.js#L410
