### ISSUE TITLE
How to specify the name of the generated output file?

### ISSUE THREAD

**Issue by warpdesign** [developit/microbundle#212]
I'm using microbundle this way:

```
microbundle build --entry js/mod-processor.js -o dist
```

It works but generates a file called `dist/modplayer-js.js`, modplayer-js being the name of my package/directory.

Is there a way to specify the name of the output file?

**Comment by ianwalter** [comment]
@warpdesign I think you're supposed to specify the names in the `package.json` like so: https://github.com/developit/microbundle#specifying-builds-in-packagejson

**Comment by warpdesign** [comment]
Sure, but what if I want to build only a single file that's part of my build but isn't the name of the whole package?

**Comment by warpdesign** [comment]
How about adding an option to specify the name/prefix of the output file?

**Comment by rzkhosroshahi** [comment]
@warpdesign I have the same issue.  Did you find a solution?

**Comment by ForsakenHarmony** [comment]
You can currently set the output name as x.js which will make it take the name of the input file

**Comment by mikeerickson** [comment]
I am wondering the same thing, but can’t figure out how to define these in the package.json file. Are these named output values added to root of package.json, or should they be under another property. The information in the readme is not clear?

**Comment by Kikobeats** [comment]
Specifying the filename as part of output commands works to me

```
❯ npx microbundle build -o dist/index.js --no-compress --no-sourcemap --name "@microlink/react"

Build "@microlink/react" to dist:
      15.4 kB: index.js.gz
      13.4 kB: index.js.br
      15.3 kB: index.mjs.gz
      13.4 kB: index.mjs.br
      15.5 kB: index.umd.js.gz
      13.6 kB: index.umd.js.br
```
