### ISSUE TITLE
Typescript needs config for sourcemaps to work by default

### ISSUE THREAD

**Issue by SleeplessByte** [developit/microbundle#216]
Probably analogous to #43, given the same files as in #215, the default output returns "empty source maps" just like in issue 43, with no warnings or errors, even when sourcemaps are explicitely turned on.

```json
// package.json
"main": "dist/package.js",
"umd:main": "dist/package.umd.js",
"module": "dist/package.mjs",
"source": "src/package.ts",
"devDependencies": {
  "microbundle": "^0.6.0",
  "typescript": "^3.0.3"
}
```

```Typescript
// src/package.ts
class MyPackage {
  test() { return 42 }
}

export default MyPackage
```

Building outputs empty sourcemaps:
```json
{"version":3,"file":"package.js","sources":[],"sourcesContent":[],"names":[],"mappings":""}
```

## Workaround
The minimal configuration to make this work with #215 is adding a `tsconfig.json`:
```json
// tsconfig.json
{
    "compilerOptions": {
        "sourceMap": true
    }
}
```

**Comment by developit** [comment]
Hmm, interesting.  I'd love to find a way to invert this behaviour, having typescript's sourcemaps be enabled/disabled based solely on `microbundle --no-sourcemap`.

**Comment by SleeplessByte** [comment]
Agreed with that. I expected it to work exactly like your propose right now.
