### ISSUE TITLE
Analyzing final bundle

### ISSUE THREAD

**Issue by weslleyaraujo** [developit/microbundle#219]
Hey there 👋

is there a way analyze the final bundle?
as far as I remember in webpack it only requires sourcemaps via webpack-bundle-analyzer... I could not find anything like that related to rollup.

If so, is this something worth to add to the README file?

**Comment by developit** [comment]
you should be able to use source-map-explorer:
https://github.com/danvk/source-map-explorer

**Comment by weslleyaraujo** [comment]
oh nice, that works

Thanks! 👍
