### ISSUE TITLE
React component library

### ISSUE THREAD

**Issue by knipferrc** [developit/microbundle#22]
Does this support creating a react component library and importing a global stylesheet like `import tailwindcss/dist/tailwind.min.css`?

**Comment by developit** [comment]
No - CSS should really not be bundled into JS in any case.

**Comment by knipferrc** [comment]
That makes sense, I need to reconfigure my lib to not include it in the JS bundle. Thanks again, awesome looking tool by the way. Going to start using it!!

**Comment by knipferrc** [comment]
@developit Another quick question regarding this, are we able to import css files into a component? For instance, I have a main.css file i'd like to import and use postcss to extract it to its own file. For instance im using the rollup-postcss-plugin with extract: true to create the css file.

**Comment by developit** [comment]
I'd be open to having Microbundle handle that if we can do it in a fairly unopinionated way.

**Comment by knipferrc** [comment]
Could we just add the `rollup-plugin-postcss` plugin and then in the config just do 
```js
postcss({
  extract: true
})```

this way we can import css files and it will generate the output as a css file

**Comment by developit** [comment]
yup, that sounds good.

**Comment by knipferrc** [comment]
Awesome. I can create a PR for this.

**Comment by developit** [comment]
That'd be *stellar*

**Comment by knipferrc** [comment]
#30

**Comment by developit** [comment]
awesome, merged and we'll release shortly!
