### ISSUE TITLE
node native module resolved as undefined in umd build

### ISSUE THREAD

**Issue by YerkoPalma** [developit/microbundle#224]
Hi 👋 
I'm trying to build a library with microbundle but I can't seem to get the umd build right. I'm using this command for build

```bash
$ microbundle -o dist --name RouterSingleton --external assert
```

As you can see, I'm using the node `assert` module. The cjs build works fine, but when using the umd build in a script I get assert as `undefined`.

How should I get this working?
Thanks

**Comment by ForsakenHarmony** [comment]
Do you need the umd build?

You'll probably want cjs for node anyways

**Comment by YerkoPalma** [comment]
I actually only need the umd and es module build as I'm building a library only for browsers

**Comment by ForsakenHarmony** [comment]
then why are you using the node assert module?

**Comment by YerkoPalma** [comment]
Why I shouldn't? Is really common to use some node modules that can be bundled in the browser. The assert module is particullary simple, browserify, webpack or any bundler handle it without a problem.

Does microbundle handle those modules? if not, how can I specify a npm module to use in that case?

**Comment by developit** [comment]
`npm install --save assert` will get you [browserify/commonjs-assert](https://github.com/browserify/commonjs-assert) and microbundle should pick it up automatically.

**Comment by rmilejcz** [comment]
I'm having the same problem, and I've written an extremely simple React component with the intent of bundling it as a UMD, but React is undefined for some reason.

index.jsx

```javascript
import React from "react";

export const root = {
  notReact: React
};
```

Bundle command

    microbundle -o dist/ --name TestApp --compress false --sourcemap false

index.html:

```
<!DOCTYPE html>
<html lang="en">
  <body>
    <div id="root"></div>
  </body>
  <script src="../dist/test-app.umd.js"></script>
  <script>
    try {
      console.log(TestApp); // <-- { root: { notReact: undefined } }
    } catch (err) {
      console.log(err);
    }
    console.log(window);
  </script>
</html>
```

I'm not really sure what I could be doing wrong, I've looked at a few other react libraries utilizing microbundle and I can't find any differences
