### ISSUE TITLE
'default' is imported from external module 'react' but never used

### ISSUE THREAD

**Issue by karl-run** [developit/microbundle#225]
What does this warning mean for me, and what should I to to "fix it?"

Run target:
`"build": "microbundle build --external react",`

Do I have to pass `--external react` when it is defined in peerDependencies?

Component:
```jsx
import React from 'react';

import style from './index.css';

const Example = ({ className }) => (
  <div>Hello</div>
);

export default Example;
```

I can "fix" the problem by making it a statefull component that uses `React.Component`.

**Comment by ForsakenHarmony** [comment]
you'll probably want to pass `--jsx React.createElement` instead

**Comment by karl-run** [comment]
That fixed it.
