### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by kesla** [developit/microbundle#226]
Hey,

Thanks for a great project!

Seem like a few great additions have been added to the project recently (typescript 3 etc), so perhaps it could make sense to make a new release?

**Comment by developit** [comment]
Yup! I'm going to give publish permissions to @Andarist and @ForsakenHarmony.

**Comment by NateRadebaugh** [comment]
Any updates on this front? I'd like to get my team moved over from rollup to microbundle once the new typescript features are available.

**Comment by developit** [comment]
current master is available as `npm install microbundle@beta`.

**Comment by ForsakenHarmony** [comment]
https://github.com/developit/microbundle/releases/tag/0.7.0
