### ISSUE TITLE
support  microbundle config file

### ISSUE THREAD

**Issue by xiaoxiangmoe** [developit/microbundle#249]
`microbundle.config.json` `microbundle.config.yaml` ,etc.

**Comment by ForsakenHarmony** [comment]
What are you looking to configure? It's supposed to be minimal and zero config

**Comment by xiaoxiangmoe** [comment]
@ForsakenHarmony compress，strict，format

**Comment by ForsakenHarmony** [comment]
you can do that with cli

**Comment by paulmelnikow** [comment]
Good defaults and minimal config is great and I'm all for that. 👍 Though, wanted to lend a voice of support for config files when there are necessary options, especially yml which lends itself to human readability.

Breathing room makes the configuration more understandable and maintainable. You can leave comments, and more easily transfer settings across projects. It also avoids using negative options (like no-compress), which are harder to understand than positive ones (compress, defaulting to true).

**Comment by adjohnston** [comment]
> What are you looking to configure? It's supposed to be minimal and zero config

I would like the chance to configure some of what PostCSS is doing. Specifically, whether to use modules, extract true or false and change the generated scope names.

**Comment by treshugart** [comment]
It would be much easier to specify names for external packages and other options using the [`cosmiconfig`](https://github.com/davidtheclark/cosmiconfig) conventions. While something can be targeted as zero config, I think it's pragmatic to provide an ergonomic way to do this. I'd be happy to provide a PR for it.
