### ISSUE TITLE
--no-sourcemap is ignored in some cases

### ISSUE THREAD

**Issue by mathiasbynens** [developit/microbundle#251]
[minimal repro gist](https://gist.github.com/mathiasbynens/029deab8a506a73534b3fa595381665c)

The relevant command is: `microbundle index.mjs -f es,cjs --target node --no-sourcemap`

Repro steps:

1. `git clone git@gist.github.com:029deab8a506a73534b3fa595381665c.git lolwhoops && cd lolwhoops`
1. `npm i`
1. `npm run repro`

Output:

```
Build "test" to dist:
         41 B: test.js.gz
         25 B: test.js.br
        273 B: test.mjs.gz
        237 B: test.mjs.br
```

From the above, you can already tell that something’s wrong with `test.mjs`. To confirm:

```
$ tail -n1 dist/test.mjs
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImluZGV4Lm1qcyhvcmlnaW5hbCkiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsT0FBQSxDQUFRLEdBQVIsQ0FBWTtBQUFaIiwiZmlsZSI6ImluZGV4Lm1qcyhvcmlnaW5hbCkiLCJzb3VyY2VzQ29udGVudCI6WyJjb25zb2xlLmxvZygndGVzdCcpOyJdfQ==
```

**Comment by mathiasbynens** [comment]
For completeness’ sake:

```
$ node -v
v10.4.0

$ npm -v
6.4.1
```

**Comment by developit** [comment]
Possibly a regression in `0.7`

**Comment by chrstntdd** [comment]
Getting this same issue only with the `.mjs` variants using `--no-compress`

Also tried `microbundle --sourcemap false` but got the same results — inlined sourcemapping. Commonjs output does not contain the inlined sourcemapping.

```
$ node -v
v11.1.0

$ npm -v
6.4.1

$ rm -rf dist && microbundle -o dist/index.js -f es,cjs --external react,scheduler --sourcemap false --no-compress
Build "project" to dist:
      5.89 kB: index.js.gz
       5.1 kB: index.js.br
      24.3 kB: index.mjs.gz
      20.8 kB: index.mjs.br
```
