### ISSUE TITLE
Throw Error when using styled-components

### ISSUE THREAD

**Issue by rzkhosroshahi** [developit/microbundle#257]
I used styled-components and this makes an error that is: `Error: Could not load stream (imported by ../node_modules/styled-components/dist/styled-components.cjs.js): ENOENT: no such file or directory, open 'stream'`.
This error makes an issue for `microbundle watch` and this not working.

**Comment by developit** [comment]
Can you provide some more details on how to reproduce this?

**Comment by rzkhosroshahi** [comment]
> Can you provide some more details on how to reproduce this?
In [this repository](https://github.com/Kamva/kamva-ui-kit/tree/replace_rollup) in `replace_rollup` **branch**, you can see what happens when running `npm run build:watch`. after the second change I got the above error.

**Comment by developit** [comment]
I think we need to have microbundle inspect the [browser field](https://github.com/styled-components/styled-components/blob/master/package.json#L9-L12).

**Comment by rzkhosroshahi** [comment]
> I think we need to have microbundle inspect the [browser field](https://github.com/styled-components/styled-components/blob/master/package.json#L9-L12).
Yes also rollup has the same issue. I got the same error in rollup.

**Comment by developit** [comment]
This was fixed at some point.
