### ISSUE TITLE
TypeScript - Unexpected token v0.8.3

### ISSUE THREAD

**Issue by scttcper** [developit/microbundle#259]
example file
```ts
export class MyClass {
    async foo() {}
}
```

error
```
> microbundle build --target node --format cjs,es -o dist

Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)

at /index.ts:2:10

1: export class MyClass {
2:     async foo() {}
             ^
3: }
```

repo: https://github.com/scttcper/microbundleunexpected

**Comment by jpzwarte** [comment]
Just ran into this myself. This is a regression in 0.8. 0.7 works fine.

**Comment by marvinhagemeister** [comment]
Thanks for the repo to reproduce it. This helps a lot👍 I'll look into it

**Comment by jpzwarte** [comment]
My issue is slightly different: in 0.8 the output still contains `async` and `await` keywords. In 0.7 it doesn't.

**Comment by jpzwarte** [comment]
The command i'm using is: `microbundle -i src/index/index.ts -o dist/index/index.js -f cjs --sourcemap false`

**Comment by jpzwarte** [comment]
No, but you can reproduce with an IIFE:

```
(async function () {
  console.log('foo');
})();
```

The above code will not cause an error when microbundle runs (if you remove the IIFFE it will cause an error).

**Comment by marvinhagemeister** [comment]
Briefly digged into it and it doesn't seem to be related to TS specifically. For the class based code rollup will end up with something like this, which is invalid:

```js
// Source
class Foo {
  async bar() {}
}

// Output
function Foo() {}
Foo.prototype.async bar() {}
```

Still need to find the source as to what is causing this.


```

**Comment by marvinhagemeister** [comment]
I think I know why this is happening (still need to find a fix). `rollup-plugin-babel` has a check in place that checks if the given path of a file/module matches this regex `(\.js|\.jsx|\.es6|\.es|\.mjs)$`. The regex is created during runtime and not static. Additionally the TS plugin doesn't change the extension from `.ts` to `.js`. Because of that the above regex check fails and babel compilation is skipped.

**Comment by marvinhagemeister** [comment]
Fix is basically ready, but I ran into a bug in TypeScript itself when external helpers are used: https://github.com/Microsoft/TypeScript/issues/28849

**Comment by developit** [comment]
@marvinhagemeister could we circumvent that by disabling `externalHelpers`?

**Comment by marvinhagemeister** [comment]
@rpetrich Implemented support for non-hoisted `var`-keywords in his babel plugin. That's cleaner imo than disabling `externalHelpers`. The next version of that will likely be released soon.
