### ISSUE TITLE
Formats?

### ISSUE THREAD

**Issue by mrmartineau** [developit/microbundle#27]
How can I specify multiple formats? e.g. `cjs` and `es`. I thought I would so something like this:

```
microbundle src/*.js --format 'cjs,es'
```

But it doesn't work. I get this error:

```
$ microbundle src/*.js --formats 'cjs, es'
Error: Invalid format: cjs, es - valid options are amd, cjs, es, iife, umd
```

Any ideas?

**Comment by developit** [comment]
I think you need to pass it like this:

```
microbundle --format cjs es
# or
microbundle --format cjs --format es
```

**Comment by mrmartineau** [comment]
@developit your second suggestion works as expected. The first does not.

Thanks

**Comment by developit** [comment]
for anyone who finds this, I've updated my answer so both work.

**Comment by mrmartineau** [comment]
awesome, thanks @developit
