### ISSUE TITLE
Not working with hoisted packages

### ISSUE THREAD

**Issue by FezVrasta** [developit/microbundle#270]
I was having a problem with my `babel-plugin-macros` branch, one of the packages of my monorepo didn't compile with the error:

    Error: 'default' is not exported by ../../node_modules/object-assign/index.js

after a bit of tinkering I found out that the problem is this line:

https://github.com/developit/microbundle/blob/master/src/index.js#L359

basically, this line tells `rollup-plugin-commonjs` to include the local `node_modules` folder of the current package, but it will not include any hoisted packages (stored at the root `node_modules` folder).

I tried to change that to `**/node_modules/**` but it still doesn't work, for now the only working attempt is:

```
commonjs({
  include: '../../**/node_modules/**',
})
```

which obviously is not optimal.

I'm quite sure my error could be reproduced even without the additional `babel-plugin-macros` but I can't figure out how.

Do you think it's worth addressing this issue already?

**Comment by Andarist** [comment]
`include` should support regexps, so maybe that would just be simpler to use here?

**Comment by FezVrasta** [comment]
Oh right! I'll send a PR
