### ISSUE TITLE
including dependencies

### ISSUE THREAD

**Issue by Kikobeats** [developit/microbundle#28]
Hello,

I'm interested in add support for include all the dependencies in the final bundle.

This conversation started on Twitter:
https://twitter.com/_developit/status/940937797589983235

After check the code, I only seeing a way to excluding, not including:
https://github.com/developit/microbundle/blob/e2bf50b1b5fce002d46b9bf9c1f7c37a74ddd82a/src/index.js#L140

**Comment by developit** [comment]
I believe passing `--inline all` will include all resolvable dependencies from node_modules.

**Comment by ColinRTaylor** [comment]
This PR seems to fix this issue for me: https://github.com/developit/microbundle/pull/33
