### ISSUE TITLE
`--compress` option is broken since v0.7.0

### ISSUE THREAD

**Issue by adriengibrat** [developit/microbundle#286]
`--compress` option is parsed as a string but [checked as a boolean](https://github.com/developit/microbundle/blob/master/src/index.js#L430), so it's not working anymore: everything is always minified.

**Comment by marvinhagemeister** [comment]
Seems to be related to https://github.com/lukeed/sade/issues/21 . Sade doesn't seem to forward the required type information to the cli parser `mri`.

**Comment by marvinhagemeister** [comment]
Fixed in `0.9.0`. As suspected this issue was downstream in the dependency we use to parse the cli arguments. Note: you may need to clear `node_modules` and run `npm install` again because npm may have cached an older version of `mri`.

**Comment by thierrymichel** [comment]
Hi here,

It seems broken again (for the same reason)…
I am using version `0.10.1`.

`option.compress` is returning a `string` (`'false'`).
Then, on line #538, `options.compress !== false` is always returning `true`…

Changing it to `options.compress !== 'false'`, makes the build not compressed.

**Comment by ForsakenHarmony** [comment]
yeah, you're supposed to use `--no-compress`
