### ISSUE TITLE
Add Rollup plugin with support for Node built-in modules

### ISSUE THREAD

**Issue by gaui** [developit/microbundle#288]
When importing `child_process` and targeting node, I still get this error from #238 :

```
'child_process' is imported by src\command.ts, but could not be resolved – treating it as an external dependency
Error: Could not load child_process (imported by src/command.ts): ENOENT: no such file or directory, open 'child_process'
```

This can be bypassed by adding `--external child_process` argument. Still I get this message:

> Creating a browser bundle that depends on Node.js built-in modules ('path', 'assert', 'util' and 'events'). You might need to include https://www.npmjs.com/package/rollup-plugin-node-builtins

So please add package `rollup-plugin-node-builtins` so Rollup knows how to detect Node built-in modules and resolve them appropriately.

**Comment by marvinhagemeister** [comment]
Good catch, can you make a PR?

**Comment by lukeed** [comment]
I think we can skip the plugin & do a special case for `--external natives` that adds them:

```js
require('module').builtinModules || Object.keys(process.binding('natives'))
```

**Comment by gaui** [comment]
@lukeed Spot on. But wouldn't that resolution logic belong in Rollup?

**Comment by lukeed** [comment]
@gaui Personally, I would vote yes, but realistically it's not something Rollup can/wants to do because you may have shims/custom modules that share the same names, and the above would likely (have to) override anything non-native with the native version.

**Comment by gaui** [comment]
If you're naming your modules the same as the natives, you're doing something wrong. 😄

**Comment by gaui** [comment]
@Rich-Harris what do you think?

**Comment by gaui** [comment]
@lukeed Is it possible to mark those modules returned from the above function, as external so Rollup knows? Not familiar with microbundle internals.

**Comment by z0al** [comment]
@lukeed 
> I think we can skip the plugin & do a special case for `--external natives` that adds them

I don't get it. How this would add necessary shims when, for example, bundling targeting the browser?
