### ISSUE TITLE
Refactor | Divide the code into functions

### ISSUE THREAD

**Issue by MatiasOlivera** [developit/microbundle#289]
**Is your feature request related to a problem?**
I was reading the source code and I think is a little difficult to follow for newcomers because it follows an imperative way instead of a declarative approach. The` index.js` file has 500 lines of code, it could be more manageable if it will be smaller.

**Describe the solution you'd like**
- Move the code into different functions
- Avoid changing the options object directly
- Move related functions to new files (maybe)
- Move plugins to its own directory (maybe)

It will be necessary making several pull requests to make it more easily to review and discuss the changes.

What do you think?

**Comment by marvinhagemeister** [comment]
That's a great idea! Feel free to make a PR 👍

**Comment by MatiasOlivera** [comment]
I want to move the plugins to a directory:
1. Move `createConfig()` to its own file because it has +250 lines. The filename could be `create-config.js`
1. Create the `plugins` directory
1. Move each plugin config and its imports to its own file. IMHO I think this will allow managing the dependencies more easily. The filename could be the language name instead of the transpiler name to hide the implementation. Eg: `javascript` instead of `babel`.
1. Import the plugins from `createConfig()`

The project stucture could be:
```js
/src
  index.js
  create-config.js
  /plugins
      javascript.js
      typescript.js
```

Thoughts?

@developit @marvinhagemeister @ForsakenHarmony @Andarist

**Comment by Andarist** [comment]
1. sounds good
2-4. would like to see how it would look like first, so preferably would be done in separate PR (truth to be told I don't like this, but I'm open minded 😉 )

Rollup plugins configs are rather short, so I don't quite see the value of moving them out from the `createConfig`. IMHO it would just require more file jumping to see what is happening and how things are configured.

**Comment by marvinhagemeister** [comment]
1. sound good for me too 👍 
2.-4. Agree with @Andarist here. I think we won't gain much by moving it into functions for the same reason @Andarist listed.

**Comment by MatiasOlivera** [comment]
I will make a PR for the first. And about the other changes, the reasons both of you said are good ones and make sense to me.
