### ISSUE TITLE
Tests are not passing

### ISSUE THREAD

**Issue by MatiasOlivera** [developit/microbundle#299]
**Describe the bug**
- The snapshot tests fail because it compares the wrong directories.
- There are 150 new snapshots. I don't know if this is the expected behavior. _(See additional context)_
- Create the `async-ts` folder in these fixtures: `basic-tsx` and `ts-mixed-exports`
- Create the `esnext-ts` folder in fixture `esnext-ts`

**To Reproduce**
1. Fork the repo
2. Install the dependencies (`npm install`)
3. Run the tests (`npm run test`)

**Actual behavior**

    C:\path\to\microbundle (master) (microbundle@0.9.0)
    $ npm run test

    RUNS  test/index.test.js
    
    ...

    Test Suites: 1 failed, 1 total
    Tests:       4 failed, 21 passed, 25 total
    Snapshots:   10 failed, 161 passed, 171 total
    Time:        140.519s, estimated 194s
    Ran all test suites.

There are 171 snapshots.

**Expected behavior**
That the tests passed without errors.

**Environment**
- OS: Windows 10
- Node.js: v8.11.3

**Additional context**

Go to the previous commit in the `master `branch

    $ git checkout HEAD~

Run the tests

    C:\path\to\microbundle (HEAD detached at fcfd408) (microbundle@0.8.4)
    $ npm run test
   
    RUNS  test/index.test.js

    ...

    Test Suites: 1 failed, 1 total
    Tests:       5 failed, 20 passed, 25 total
    Snapshots:   2 failed, 6 obsolete, 19 passed, 21 total
    Time:        216.544s, estimated 299s
    Ran all test suites.

There are only 21 snapshots.

**Update**

I updated Node.js to v11.6.0, tried again and still have the same problem.

**Comment by ForsakenHarmony** [comment]
https://travis-ci.org/developit/microbundle/builds/472362834

yes, the new snapshots are intentional, I don't know why you are getting different result

**Comment by MatiasOlivera** [comment]
The problem was that some tests were taking more to run than the default timeout for each test. 

` Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.`
