### ISSUE TITLE
0.0.7+ TypeScript target options from tsconfig.json ignored

### ISSUE THREAD

**Issue by chrstntdd** [developit/microbundle#300]
This seems to be the offending line in the source: https://github.com/developit/microbundle/blob/master/src/index.js#L411
and the commit: https://github.com/developit/microbundle/commit/cebff34d415b00d424876f25f1a700fd4b17e21c

I assume, based on the commit, that this was added since typescript is compiled before additional transforms are added.

I'm not quite sure what direction this library is headed in, so I'd love some feedback. Would it make sense to have the `tsconfig.json` of the user be the source of truth for setting the target output or have it configurable via microbundle itself? I assumed that the `--target` flag could be used, but it only appears to modify the module resolution.

Either way, I think microbundle can stand to have the output be configurable.

Cheers!

**Comment by developit** [comment]
Interesting, I assumed that'd merge it into the config.
It looks like we could fix this by changing `tsConfigOverride` to `tsconfigDefaults`.

**Comment by ForsakenHarmony** [comment]
that won't change anything

we run babel and buble after typescript, so that override is just there to get the least transpiled output from typescript for the next steps

**Comment by ForsakenHarmony** [comment]
@chrstntdd did this answer your question, #413 is in the works to get more modern output

**Comment by chrstntdd** [comment]
@ForsakenHarmony Yes indeed!
