### ISSUE TITLE
Mixed default and named exports

### ISSUE THREAD

**Issue by pascalduez** [developit/microbundle#306]
Hi,

I have a hard time figuring out a solution for having both a default and named export [in a package](https://github.com/cr0cK/superpathjoin). (Yes, that sounds like a bad idea, but if we could prevent a breaking change...). It's using TypeScript.

```js
// package index.ts
function foo() {}
export { foo };
export default foo;
```
Get compiled into:
```js
function e() {}
;(exports.foo = e), (exports.default = e)
```

Then trying to import the package in a Babel environment:

```js
// consumer index.js
import foo from 'foo';
foo();
```

```
$ babel-node index.js --presets @babel/env
```

```
(0, foo.default)();     
TypeError: (0 , foo.default) is not a function 
```

So it basically lacks the interop thing: 

```js
Object.defineProperty(exports, "__esModule", {
  value: true
});

;(exports.foo = e), (exports.default = e)
```

**Comment by pascalduez** [comment]
@developit Thanks!

We decided to only keep a default export.

**Comment by ForsakenHarmony** [comment]
just always use named exports, default is overrated :^)

**Comment by luisherranz** [comment]
I run into this as well. I'm using the workaround proposed although I hope there's a better solution in the future!

**Comment by pascalduez** [comment]
@luisherranz Well, now it works well with Babel and node, but apparently still no with TS... :( 
Still need to investigate.

**Comment by FezVrasta** [comment]
I'm sorry, I started having this problem recently (for some reason), @developit are you saying you are not willing to support mixed `default` and `named` exports with Microbundle?

**Comment by DaniAkash** [comment]
@developit I'm trying to use microbundle for my project [Rex State](https://github.com/DaniAkash/rex-state/blob/master/src/index.tsx#L47) and i'm unable to get both default & named exports to work following your workaround... Babel can only detect the default export

**Comment by ForsakenHarmony** [comment]
Do you really need a default export?

**Comment by DaniAkash** [comment]
> Do you really need a default export?

I do 😅

**Comment by ForsakenHarmony** [comment]
You can just use a named export, would probably also help with auto import

**Comment by itsmichaeldiego** [comment]
Hey everyone! I am having the same issue, if I export like this:

```javascript
import GoogleMap from './google_map';

export default GoogleMap;
```

It will build:
```javascript
module.exports = GoogleMap;
```

However, when including named exports, it changes to:

```javascript
exports.namedExport = namedExport;
...
exports.default = GoogleMap;
```

**Comment by aureooms** [comment]
> Microbundle really tries to prevent this exact scenario

Do I understand correctly that having a default AND named exports is not supported?

**Comment by aureooms** [comment]
PS: I am hitting my toe on the same stone with a library that is supposed to be consumed as
```js
import deque, {Deque} from '@aureooms/js-collections-deque';
```
After a bit of debugging I ended up on this thread... It seems microbundle does not rely on the `__esModule` property but instead on the presence of a `default` property as seen in the main output for instance (simplified):
```js
var e=require("@aureooms/js-collections-deque");
function n(e){return e&&"object"==typeof e&&"default"in e?e:{default:e}}
var t=n(e)
```

While the babel tooling (I am using `ava` and `@babel/require`) uses the following definition:
```js
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```
