### ISSUE TITLE
Allow the add transform options to bublé

### ISSUE THREAD

**Issue by wcastand** [developit/microbundle#31]
Hi,
bublé supports some transform out of the box : https://buble.surge.sh/guide/#command-line-options
maybe we could add an options to let the user add transforms he needs without adding babel to the mix.

**Comment by developit** [comment]
We may need to switch to Babel anyway, people want class property initializers.

**Comment by wcastand** [comment]
Yeah and an other problem right now is that even if i pass transforms to bublé, `nodent` is not happy x)

**Comment by developit** [comment]
Yup yup. I think we will have to switch to running Nodent after the ES6->ES5 transform.

**Comment by developit** [comment]
Update: we've enabled all of them for now.
