### ISSUE TITLE
Failing to use dynamic import

### ISSUE THREAD

**Issue by dkundel** [developit/microbundle#314]
Hey there!

I'm trying to use dynamic imports in a library that I'm bundling with `microbundle@0.9.0`. However, it's failing both with TypeScript and JavaScript at the moment with the following error:

```bash
> microbundle --target=browser --format=es src/DynamicImportLoader.js

(babel plugin) SyntaxError: /Users/dkundel/dev/flight-runtime/packages/flig
ht-browser/src/DynamicImportLoader.js: Support for the experimental syntax
'dynamicImport' isn't currently enabled (24:34):

  22 |     try {
  23 |       log('Loading "%s"', nextFunctionPath);
> 24 |       const loadedModule = await import(nextFunctionPath);
     |                                  ^
  25 |       if (loadedModule.comlink) {
  26 |         this.counter = this.counter + 1;
  27 |         const info = stripIndent`

Add @babel/plugin-syntax-dynamic-import (https://git.io/vb4Sv) to the 'plug
ins' section of your Babel config to enable parsing.

at undefined:24:33
SyntaxError: /Users/dkundel/dev/flight-runtime/packages/flight-browser/src/
DynamicImportLoader.js: Support for the experimental syntax 'dynamicImport'
 isn't currently enabled (24:34):

  22 |     try {
  23 |       log('Loading "%s"', nextFunctionPath);
> 24 |       const loadedModule = await import(nextFunctionPath);
     |                                  ^
  25 |       if (loadedModule.comlink) {
  26 |         this.counter = this.counter + 1;
  27 |         const info = stripIndent`
```

I did some digging and found #123 but it seems like that was related to nodent which has been removed and replaced by Babel in November (https://github.com/developit/microbundle/commit/71cb427dbddb42c15224b09a7df1f86b9547dfca). 

I'm surprised that nobody else raised this issue so I'm wondering if I'm doing something wrong here.

**Comment by ForsakenHarmony** [comment]
Well it kinda says what we need to fix it, but not entirely sure how well rollup supports it 

`Add @babel/plugin-syntax-dynamic-import (https://git.io/vb4Sv) to the 'plug
ins' section of your Babel config to enable parsing.`

**Comment by dkundel** [comment]
True but microbundle turns `.babelrc` off so I can't really add it just for my project. So really I'm wondering if:
a) This is by design and microbundle is not intending to support dynamic imports
b) This is not by design and nobody found it but it should be supported by `microbundle` and therefore the plugin should be included on the `microbundle` level
c) This is not by design but it was introduced by another dependency and needs to be fixed there.

**Comment by ForsakenHarmony** [comment]
I think it was an oversight, we're currently using both babel and buble

The plan is to transition to babel, but we want it to not output more code than buble currently does

So for now it should probably be added to `microbundle`

**Comment by developit** [comment]
We'd need to enable Rollup's code splitting as well. 

This may be problematic because it may or may not work with current bundler configurations. In general, code splitting in node_modules is kinda broken.

**Comment by dkundel** [comment]
My use case is a pretty edge case one where I'm building a project where I want to be able to actually use the `import` function and not actually transpile it or use code-splitting. But thanks for the insight :)

**Comment by ForsakenHarmony** [comment]
Yeah, that's what I was guessing

I'm not entirely sure how it's handled in rollup, but you could try editing in `node_modules` by installing `@babel/plugin-syntax-dynamic-import` as a dev dependency and adding it to the plugins array

it's here in the source file, probably somewhere different when it's transpiled
https://github.com/developit/microbundle/blob/master/src/index.js#L428

**Comment by Xiphe** [comment]
Im currently using microbundle to create consumable dist files of a library written in typescript. I'm also not entirely sure how this should be aproached but i would really like support for code-splitting.

**Comment by katywings** [comment]
FYI: #674 adds rollup 2 dynamic import support by using the required outputOptions :tada:
