### ISSUE TITLE
Override single parameter passed format's default output file suffix

### ISSUE THREAD

**Issue by rdmurphy** [developit/microbundle#333]
Hello! 👋 

Apologies if I am missing it, but is it possible to not have the format suffix automatically applied to the output file?

What I'm currently trying to run:

```sh
microbundle src/auto.mjs --format umd --target web --output auto/index.js
```

But it seems to ignore the file path I pass to `--output` and turns it into `auto/index.umd.js`. I can see why you'd wanna do this if you are producing multiple formats, but in the case of producing a single one would it make sense if `microbundle` accepted whatever was passed to `--output`?

**Comment by rdmurphy** [comment]
(Some background — this is an additional build I'm doing on top of the bread and butter typical one that leans on the fields in `package.json`. So I'm trying to include a variation of the package that someone can import via `name-of-package/auto`. The `umd` suffix however breaks the expectation of having `index.js` auto resolve, but ideally I'd be exporting a `umd` version.)

**Comment by developit** [comment]
@rdmurphy I think right now the only way to do this is to add a "umd:main" field to your package.json pointing to "index-umd.js", which should trick Microbundle into removing its automatic umd extension.

I think it would be nice if, when passing a single --format/-f value, we allowed preserved any explicit filename provided in `--output`.

**Comment by developit** [comment]
In the meantime, you should be able to drop a package.json into your `auto` directory that points to the UMD bundle:

```js
// auto/package.json
{
  "main": "index.umd.js"
}
```

This will cause bundlers to resolve `import 'name-of-package/auto'` to `auto/index.umd.js`.

**Comment by rdmurphy** [comment]
Huh! Didn't know it worked that way with a local `package.json` file! 🤔 Is that, err, documented anywhere?

**Comment by developit** [comment]
It's documented here - any folder that is the target of a require() can contain a package.json:

https://nodejs.org/api/modules.html#modules_folders_as_modules

Webpack copies this behaviour.

**Comment by developit** [comment]
We're going to use Export Maps for this: #749.
