### ISSUE TITLE
Does microbundle utilize rollup tree shaking when using --external none?

### ISSUE THREAD

**Issue by pmkroeker** [developit/microbundle#341]
I'm mostly curious as I was test bundling a package and it was giving me messages saying that I had some circular dependencies (dang d3). Anyways, some of the dependencies it was showing were things that I'm not actually using in my package, and it made me wonder if microbundle uses rollups tree shaking when bundling a package using --external none?

**Comment by marvinhagemeister** [comment]
Rollup will always try to tree-shake as much as possible. There is no option or flag in rollup that could turn this off 👍

**Comment by pmkroeker** [comment]
Perfect, that's what I thought. Thanks!

**Comment by Andarist** [comment]
Actually there is a flag to disable treeshaking 😉 https://rollupjs.org/guide/en#big-list-of-options#treeshake . We don't plan to support configuring this though and rollup's default will stay as true forever

**Comment by marvinhagemeister** [comment]
@Andarist I stand corrected! Thanks for chiming in :+1:
