### ISSUE TITLE
Document recipe for angular component builds

### ISSUE THREAD

**Issue by NateRadebaugh** [developit/microbundle#342]
My team uses microbundle to bundle our vanilla JS and our react components. We'd also like to standardize on microbundle for angular components but do not see explicit documentation for this.

A standard recipe/configuration should be documented for Angular builds

**Comment by marvinhagemeister** [comment]
Building angular applications is very involved as they have a non-standard build pipeline. As angular code needs the angular compiler anyway, this is out of scope.
