### ISSUE TITLE
Error: EACCES: permission denied, open '/usr/local/lib/node_modules/microbundle/node_modules/nodent-runtime/dist/index.js'

### ISSUE THREAD

**Issue by lopugit** [developit/microbundle#37]
When trying to install globaly via ```sudo npm i -g microbundle``` I get this error

```Error: EACCES: permission denied, open '/usr/local/lib/node_modules/microbundle/node_modules/nodent-runtime/dist/index.js'```

Is it an issue with ```nodent-runtime``` or ```microbundle```?

**Comment by developit** [comment]
[Do not install using sudo](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md).
