### ISSUE TITLE
How to name the types file?

### ISSUE THREAD

**Issue by Chersquwn** [developit/microbundle#387]
package.json like that

```json
// package.json

  "source": "./index.ts",
  "main": "dist/foo.js",
  "umd:main": "dist/foo.js",
  "module": "dist/foo.mjs",
  "types": "dist/foo.d.ts",
```

but the compiled file is index.d.ts.

It seems that the name of the types file is named after the file name of the source. How to name the types file?

**Comment by ForsakenHarmony** [comment]
any particular reason you need that?

**Comment by Chersquwn** [comment]
@ForsakenHarmony I write some examples for the library ,which import the library from dist,but editor can not intellisense

**Comment by Chersquwn** [comment]
I know , but just because the file name of `index.d.ts` and the file name of the library `foo.js` are inconsistent, vscode can not intellisense.

Now i am modifying the name of source `index.ts` to `foo.ts`. 
Thanks
