### ISSUE TITLE
Logo fix?

### ISSUE THREAD

**Issue by Pr0x1m4** [developit/microbundle#4]
That slant tape is driving me insane :sweat_smile: 
Mind if I fix?
<img width="521" alt="microfix_transparent" src="https://user-images.githubusercontent.com/4820517/33868880-918b3f44-ded3-11e7-843c-c2b15e9442f7.png">

**Comment by jukben** [comment]
Haha! I'd sign it.

**Comment by ledap288** [comment]
Much better ^^

**Comment by developit** [comment]
lol I liked the slant tape but it's causing a stir - do you have the SVG source for your modification?
Here's the original SVG source:
https://gist.github.com/developit/de05e4e17963ce2a714c61ccc4fd3d97

**Comment by Pr0x1m4** [comment]
Sure thing, right here
https://gist.github.com/Pr0x1m4/0d82be5ab56e35cc5486e72193d21a52

**Comment by developit** [comment]
Need to tweak some things so it doesn't require a white background, will be a bit.
