### ISSUE TITLE
How to use TSLint?

### ISSUE THREAD

**Issue by gustavopch** [developit/microbundle#403]
The TSLint CLI needs to point to `tsconfig.json` in order to work. Is there any way to use TSLint with microbundle?

**Comment by ForsakenHarmony** [comment]
create a `tsconfig.json` according to your likings, not sure microbundle will check it during transpilation, but it should work if you call it externally

**Comment by brodybits** [comment]
FYI it looks like TSLint will be migrating to using ESLint with support from typescript-eslint project:

- https://github.com/palantir/tslint/issues/4534
- https://eslint.org/blog/2019/01/future-typescript-eslint

**Comment by developit** [comment]
I'm tempted to close this as unrelated - microbundle isn't a linter.

**Comment by gustavopch** [comment]
> I'm tempted to close this as unrelated - microbundle isn't a linter.

Don't think it's unrelated. I'm not asking "how to lint the project with microbundle", but rather how to have TSLint and microbundle in the same project given that TSLint needs to point to some `tsconfig.json` while microbundle doesn't expose such file.

I think @ForsakenHarmony 's suggestion is more of a workaround than a proper solution, but as TSLint is going to be deprecated, a workaround is enough.
