### ISSUE TITLE
Microbundle should throw an error when no entrypoint is found

### ISSUE THREAD

**Issue by lostfictions** [developit/microbundle#404]
When an entrypoint for microbundle isn't found, it happily states that it's completed its job successfully. This is pretty confusing -- it would be great if it printed out some kind of error!

Simple repro:

Put this `package.json` in an empty folder:
```json
{
  "name": "microbundle-repro",
  "version": "1.0.0",
  "source": "foo.ts",
  "main": "dist/foo.js",
  "module": "dist/foo.mjs",
  "unpkg": "dist/foo.umd.js",
  "types": "dist/foo.d.ts",
  "dependencies": {
    "microbundle": "^0.11.0"
  }
}
```

`yarn install && yarn microbundle`:
```
Build "(foldername)" to dist:
Done in 0.98s.
```

**Comment by developit** [comment]
That seems like a very reasonable thing to do!
