### ISSUE TITLE
Empty source map 

### ISSUE THREAD

**Issue by eLeontev** [developit/microbundle#43]
`.map` file has empty sourse map 
`
{"version":3,"file":"bundle.m.js","sources":[],"sourcesContent":[],"names":[],"mappings":";;;;;;;;;;;;;;;;;"}
`

used version 0.2.4

**Comment by dontgoplastic** [comment]
FWIW, reverting to v0.2.3 fixes the issue for my project. Using v0.2.4+ results in similarly empty sourcemaps.

**Comment by developit** [comment]
It's likely due to replace plugin.  Were either of you able to verify this is still happening on `0.3.x`?

**Comment by dontgoplastic** [comment]
Yes, I noticed it using `0.3.1`

**Comment by developit** [comment]
I think `npm update` should pull down new versions of `rollup-plugin-postprocess` and `rollup-plugin-preserve-shebang`, which should fix Source Maps.  Let me know if you have a chance to check!

**Comment by dontgoplastic** [comment]
Hmm, no dice. `npm update` didn't pull down `rollup-plugin-preserve-shebang@0.1.5` or `rollup-plugin-postprocess@1.0.2`. In fact, I don't see where postprocess is referenced. What is that a dependency of?

I tried manually installing the two packages at the above versions but it still didn't seem to work.

I can try to get my project up on github a bit later tonight if that will help with debugging. Let me know!

**Comment by dontgoplastic** [comment]
You can view my project here. It's a very small amount of code, so hopefully it's easy to parse through: https://github.com/dontgoplastic/tab-nav

Fingers crossed that this is helpful and that I'm not just doing something completely bone-headed! :)

**Comment by developit** [comment]
This is fixed in [0.4.1](https://github.com/developit/microbundle/releases/tag/0.4.1).
(rollup-plugin-flow doesn't emit proper sourcemaps so I've patched it)
