### ISSUE TITLE
Absolute imports with babel module-resolver plugin

### ISSUE THREAD

**Issue by breadadams** [developit/microbundle#439]
Hi, I'm using `microbundle@0.11.0` for a react component library, and recently trying to use `babel-plugin-module-resolver` for absolute imports. However on build I'm seeing the following error:

```
'components/Button' is imported by src/index.js, but could not be resolved – treating it as an external dependency
'components/Icon' is imported by src/index.js, but could not be resolved – treating it as an external dependency
Error: Could not load components/Button (imported by /Users/breadadams/dev/ui-components/src/index.js): ENOENT: no such file or directory, open 'components/Button'
```

The config in `.babelrc` seems to be correct as my IDE resolves the paths correctly, but microbundle doesn't appear to be able to locate the imports.

#### Folder structure
```
ui-components/
├── src/
│   ├── index.js
│   └── components/
│      ├── Button/
│         └──  index.js
│      └── Icon/
│         └──  index.js
└── .babelrc
```

#### `.babelrc`
```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "entry"
      }
    ],
    "@babel/preset-react",
    "@babel/preset-flow"
  ],
  "plugins": [
    ["module-resolver", {
      "root": ["./src"]
    }]
  ]
}
```

#### `src/index.js`:
```
export { default as Button } from 'components/Button';
export { default as Icon } from 'components/Icon';
```

#### `src/Button/index.js`:
```
import Icon from 'components/Icon';
```

___

I also gave the `--alias` parameter a try with something like `components=./components` but it always adds a `.js` extension, and mangles the import paths, throwing an error like this:

```
Error: Could not load /Users/breadadams/dev/ui-components/src/components/Button/components/Icon.js (imported by /Users/breadadams/dev/ui-components/src/components/Button/index.js): ENOENT: no such file or directory, open '/Users/breadadams/dev/ui-components/src/components/Button/components/Icon.js'
```

Maybe I'm going about it wrong and there's a more "rollup focused" solution for absolute imports? Thanks.

**Comment by developit** [comment]
I think you might be able to pass `--alias components=$pwd/src/components`.

Personally I find this type of configuration-only path changes confusing since the source isn't runnable code (just my 2¢).

**Comment by breadadams** [comment]
Thanks for the response @developit, gave that a try but it tries to resolve `components/Button.js`, when we want it to look for `components/Button/index.js`.

Looking through the rollup alias plugin repo I came across [this issue](https://github.com/rollup/rollup-plugin-alias/issues/26) which seems to cover it. The options are to pass `/index.js` to the `resolve` parameter - which doesn't seem to be an option with microbundle - or just typing out the full path (including `index.js`).

I gave the 2nd option a try but _still_ get an error:

```bash
microbundle --jsx React.createElement --format cjs,umd --alias components=$pwd/src/components

[...]

Error: Could not load /src/components/Button/index.js (imported by /Users/breadadams/dev/ui-components/src/index.js): ENOENT: no such file or directory, open '/src/components/Button/index.js'
```

Given how troublesome it appears to be to get this working, and that this is on a rather small project, we're going to just go with relative imports. If it ever becomes a _feature_ of microbundle we'll look into re-implementing.

Feel free to close this if you don't believe it's an issue, thanks again.

**Comment by developit** [comment]
Sounds like a plan. I think my concern with supporting this as a feature would be that we move away from source being executable JavaScript, and into a particularly bundler-specific input format. Right now Microbundle has decent tradeoffs here, where it doesn't provide configuration that breaks this equivalence. Would have to be a pretty big payoff to give that up.

**Comment by Szwarceneger16** [comment]
Hi
so after 2 years, are there any solution for this?
I also use absolute imports and babel to convert it
