### ISSUE TITLE
default config for development mode

### ISSUE THREAD

**Issue by eLeontev** [developit/microbundle#44]
According your docs dev mode should be run via `watch` command. In this case I expect that bundle should not have minification (--compress=false). It's more conveniently to debug code by default.

Is it possible to change it to mentioned flag?

**Comment by developit** [comment]
I'm not sure - personally, I use watch mode to monitor build sizes. Sourcemaps fix the development hassle of minification, right?

**Comment by eLeontev** [comment]
Actually soursemap is not working on version: 0.2.4 (is installed on `yarn microbundle` or `npm install microbundle`). How can it help in the develop mode?
