### ISSUE TITLE
CLI output dirname/filename misleading

### ISSUE THREAD

**Issue by ianstormtaylor** [developit/microbundle#441]
If you want to have two formats in different directories but with the same file name, for example:

```js
"main": "lib/library.js",
"umd:main": "dist/library.js",
```

The CLI output will be misleading:

```
Build "library" to lib:
      2.69 kB: library.js.gz
      2.33 kB: library.js.br
      2.85 kB: library.js.gz
      2.49 kB: library.js.br
```

I think it shouldn't try to be so smart and should instead just include the full path:

```
Built "library":
      2.69 kB: lib/library.js.gz
      2.33 kB: lib/library.js.br
      2.85 kB: dist/library.js.gz
      2.49 kB: dist/library.js.br
```

(Even in the 90% where they are in the same directory it will be either `lib/` or `dist/`, which are super small prefixes to have to add for the added clarity.)

**Comment by ianstormtaylor** [comment]
Actually, an even bigger issue... if you run:

```
microbundle --format umd
```

With the above configuration, it will end up writing to `lib/library.js` for some reason, instead of `dist/*`. Seems like a bug?

**Comment by developit** [comment]
@ianstormtaylor that seems like a bug, but I don't see where you're specifying the input file. Are you using package.source, or passing an argument to microbundle?

**Comment by ianstormtaylor** [comment]
@developit ah sorry, yes I'm using `package.source`, it was:

```js
"source": "./src/index.js",
```

**Comment by developit** [comment]
I've run into this a couple times now when tailoring output formats. Seems like we should at least have a self-test to ensure no files will collide on output.

Regarding the naming, I'd love to do parent directory disambiguation similar to how tabs work in VSCode. If that's too weird though, just showing full paths relative to cwd would be fine.

**Comment by ianstormtaylor** [comment]
Disambiguation seems like a nice approach for the simple cases.

**Comment by marvinhagemeister** [comment]
We're going to support package exports like node in `package.json`
