### ISSUE TITLE
Missing Flow support on `0.12.0-next.*` versions?

### ISSUE THREAD

**Issue by FezVrasta** [developit/microbundle#443]
I see the Flow babel plugins are in `package.json` but they are not referenced anywhere in the code.

If I try to build my code with `0.12.0-next.3` it throws a syntax error on the first `import { type Smth } from '...'`.

**Comment by FezVrasta** [comment]
@ForsakenHarmony may we get a `0.12.0-next.4` release with this fix please?

**Comment by ForsakenHarmony** [comment]
Done 👌
