### ISSUE TITLE
ESM namespaces cannot be tree-shaked

### ISSUE THREAD

**Issue by Conaclos** [developit/microbundle#457]
*Microbundle* makes tree-shaking impossible for namesapced exports.

## Example

Consider a project with two files: `sub.js` and its source entry `index.js`.
`index.js` imports the stuff of `sub.js` using a namespace and exports this namespace:

```js
import * as sub from "./sub"
export { sub }
```

*Microbundle* transpiles this code in somethings like:

```js
export const sub = { ... }
```

By transpiling the ESM namespace syntax, *Microbundle* disables tree-shaking for the exports of `sub.js`.

## Possible solution

Change the output for the `module` entry. The source-code should not be bundled into a single file. The structure of the source-code directory should be preserved for the "module entry".

In the previous example we could get the following directory hierarchy:

```
dist/
  module/
    index.modern.mjs
    sub.modern.mjs
src/
  index.js
  sub.js
```

**Comment by ForsakenHarmony** [comment]
Uhh how would that treeshake?

You merge all the exports of sub into a single export

**Comment by Andarist** [comment]
According to [this](https://github.com/facebook/react/issues/11503#issuecomment-514179050) both webpack and rollup can tree-shake reexported namespaces (ofc to some extent, if they are not passed to a function as argument etc)

**Comment by ForsakenHarmony** [comment]
oh, interesting

**Comment by Conaclos** [comment]
@ForsakenHarmony 
I rely on that in one of my library. *Rollup* perfectly handles this case.
In my experience, *Webpack 4* does not. However, *Webpack 5* could handle this case. See [this issue][1] and the [project task list][2].

[1]: https://github.com/webpack/webpack/issues/8057
[2]: https://github.com/webpack/webpack/projects/5

**Comment by Andarist** [comment]
That’s an interesting problem - seems that if rollup can treeshake namespace objects it should be able to do the same for simple objects too (ofc if such object wont get itself into a deoptimising situation).

Even if it doesnt handle regular objects it could at least make it easier for authors to keep namespaces in additional chunks (under a new flag ofc). It already does the heavy lifting and its the best suited for this job. WDYT @lukastaeger ?

**Comment by lukastaegert** [comment]
Tree-Shaking non-namespace objects is definitely something I have on my long term roadmap. The situation for namespace objects is slightly simpler as the logic is easily embedded into the rest of the exported variable handling. True objects have a lot of additional semantics that are to be taken into account, both to how they are created and the fact that they are inherently  mutable. But it is doable.

**Comment by developit** [comment]
If you want to produce multiple output files, pass multiple input files:

```
dist/
  module/
    index.modern.mjs
    sub.modern.mjs
src/
  index.js
  sub.js
```

Can be achieved today via the following:

```
microbundle -d dist/module src/index.js src/sub.js
```

The files will be linked to their corresponding minified output versions as they were in src.

**Comment by Conaclos** [comment]
@developit 
`index.modern.mjs` is still bundled. It does not import `sub.modern.mjs`...

**Comment by ForsakenHarmony** [comment]
can you try `microbundle -d dist/module src/{index,sub}.js`?

**Comment by Conaclos** [comment]
@ForsakenHarmony 

Given the following `sub.js` and `index.js`:
```js
export const A = 1
export const B = 2
```
```js
import * as sub from "./sub"
export { sub }
```
And performing the following commands:

```sh
npm install -D micronbundle@next
npx microbundle --no-compress --format modern -d dist/module src/{index,sub}.js
```

I get the following `sub.modern.mjs` and `index.modern.mjs`:
```js
var A = 1;
var B = 1;

export { A, B };
```
```js
var A = 1;
var B = 1;

var sub = ({
	A: A,
	B: B
});

export { sub };
```

**Comment by marvinhagemeister** [comment]
FYI: Microbundle is an opinionated wrapper around rollup. Any tree shaking issues should be filed there 👍

**Comment by Conaclos** [comment]
@marvinhagemeister

FYI: this is not related to rollup.
