### ISSUE TITLE
Include StandardJS

### ISSUE THREAD

**Issue by binarykitchen** [developit/microbundle#464]
Maybe a good idea to lint with StandardJS before bundling?

**Comment by marvinhagemeister** [comment]
-1 I think that would be to opinionated. Despite the name it's not standard at all in the JS community and many use a custom eslint preset.

The thing I like about microbundle the most is that it doesn't leak into other areas and just bundles things.

**Comment by ForsakenHarmony** [comment]
Yup you can use standard locally in your project, but a lot of people use other linting rules
