### ISSUE TITLE
Error when bundling styled components with preact project

### ISSUE THREAD

**Issue by Bobvantpadje** [developit/microbundle#466]
I'm trying to implement `styled components` in my Preact project. Locally everything works fine and the bundling also does not give any errors. When I try to include the bundled code (as an NPM module) in my project I get the following error: 
`Cannot add property __p, object is not extensible`

My bundle script looks like this:
`"dist": "microbundle --entry src/components/questionnaire/index.js"`

**Comment by developit** [comment]
Hi @Bobvantpadje - you need to move `preact` to your devDependencies - right now it seems like you have it as a dependency.

**package.json:**

```js
{
  "main": "dist/questionnaire.js",
  "module": "dist/questionnaire.module.js",
  "scripts": {
    "dist": "microbundle src/components/questionnaire/index.js"
  },
  "peerDependencies": {
    "preact: "7.x || 8.x"
  },
  "devDependencies": {
    "preact": "^8.5.2"
  }
}
```
