### ISSUE TITLE
/bin/sh: microbundle: command not found with microbundle@3.0.0

### ISSUE THREAD

**Issue by KatSick** [developit/microbundle#47]
After upgrading to 3.0.0 i can't run microbundle with npm scripts.

```
/bin/sh: microbundle: command not found
```

**Comment by developit** [comment]
Hmm - what versions of Node and npm are you running?  I'm using 3.0.0 in a few projects without issue.

**Comment by KatSick** [comment]
@developit sorry :( was my local problem when installing microbundle
