### ISSUE TITLE
Requires node >= 10.16

### ISSUE THREAD

**Issue by transitive-bullshit** [developit/microbundle#487]
`microbundle` fails to install on node 8 and some versions of node 10 due to its relatively minor dependency on [brotli-size](https://github.com/erwinmombay/brotli-size). (see this [PR](https://github.com/erwinmombay/brotli-size/pull/11) where the requirement was added)

I tracked this down due to an [error in CI](https://travis-ci.com/saasify-sh/saasify/jobs/240609522) where we need to support `node >= 8`.

Given that Node.js `v8` and minor versions of Node.js `v10` before `v10.16` are still in LTS, I'd propose making `brotli-size` an optional dependency until they're deprecated or at least less common.

At the very least, I'd suggest making this requirement explicit in the readme and/or package.json `engines` field.

Mucho gracias for this awesome package btw! 😄

**Comment by lizy0329** [comment]
嗯，here is nodejs version is <= 10.16 Error

![WeChat Work Screenshot_20191106095506.png](https://i.loli.net/2019/11/06/b7WB5XvCzSjEfRs.png)

**Comment by ForsakenHarmony** [comment]
Released in `0.12.0-next.7` sorry it took so long

**Comment by transitive-bullshit** [comment]
Thanks for all your OSS work @ForsakenHarmony 🙏
