### ISSUE TITLE
Example of react library with styled components?

### ISSUE THREAD

**Issue by jacobgranberry** [developit/microbundle#488]
Does anyone have any example repos that include react and styled components?  I have a test repo here: https://github.com/jacobgranberry/company-ui-microbundle

the TestComp component renders fine, the StyledTestComp tosses an error while using npm link

`TypeError: styled_components__WEBPACK_IMPORTED_MODULE_1__.div is not a function`

could use some help with this one!

**Comment by mjyoung** [comment]
@jacobgranberry did you ever figure this out?

**Comment by Mazuh** [comment]
anyone?

I'm having similar issue :-/

**Comment by developit** [comment]
I can't access the test repo, but FWIW this should "just work" in a valid configuration. My guess is that styled-components is being bundled into the output, which won't work because styled-components injects itself into React.

**Comment by nkint** [comment]
For anyone that read this issue, here there is a small paragraph in the main styled-component page: [https://styled-components.com/docs/faqs#with-microbundle](https://styled-components.com/docs/faqs#with-microbundle) and remember about `peerDependencies`, hope it helps!
