### ISSUE TITLE
Including 3rd Party CSS dependencies?

### ISSUE THREAD

**Issue by ericnkatz** [developit/microbundle#498]
Seem to have an issue where if I import css from a node_module dependency it isn't getting bundled into final .css dependency?

For example if my entry does something like `import 'bootstrap/dist/css/bootstrap.css';` it does not include this in microbundle compiled  css.

**Comment by gdenisov** [comment]
@ericnkatz Have you found a solution to this problem?

**Comment by MarkAPhillips** [comment]
Did anyone manage to resolve this issue ?

**Comment by ericnkatz** [comment]
@gdenisov / @MarkAPhillips I haven't been able to resolve the issue. 😭 

@developit is there a place where you could point me to help investigate?

**Comment by rafael-sotelo** [comment]
Hi, having the same problem, anyone found the solution for this ?

Thanks

**Comment by developit** [comment]
This shouldn't still be an issue in Microbundle 0.12. We are also considering removing support for CSS.
