### ISSUE TITLE
Plans to add Typescript support?

### ISSUE THREAD

**Issue by tymondesigns** [developit/microbundle#5]
Love the simplicity! 

Do you have any plans to add Typescript support at some point?

maybe something like 

```
microbundle --ts
// or
microbundle --transpile=typescript
```

**Comment by developit** [comment]
We could probably build that in by-default, based on file extension.
It looks like [rollup-plugin-typescript2](https://github.com/ezolenko/rollup-plugin-typescript2) would handle this perfectly out-of-the-box.

**Comment by jbaxleyiii** [comment]
I'm happy to take this one. @developit any details you have in mind?

**Comment by tymondesigns** [comment]
Awesome 😁 happy to add myself, if nobody beats me to it

**Comment by jonstuebe** [comment]
Would you be able to add flow support as well?

**Comment by jaredpalmer** [comment]
FWIW I end up using `tsc-watch --onSuccess` to a directory called `compiled`, and then I point rollup there.

**Comment by developit** [comment]
@jonstuebe yup, I'd love a PR to add [rollup-plugin-flow](https://github.com/leebyron/rollup-plugin-flow).

**Comment by tymondesigns** [comment]
Closing because merged :)
