### ISSUE TITLE
Using modern format forces ALL outputted bundles to be modern code

### ISSUE THREAD

**Issue by snapwich** [developit/microbundle#503]
I think this is a bug unless I'm misunderstanding the purpose of specifying multiple output formats.

If you run `microbundle --format modern,umd` then both the `modern.js` and `umd.js` files that are output will not polyfill code using `class`, `async/await`, etc.

If you run `microbundle --format umd` then the `umd.js` file will be polyfilled and remove modern code like `class` or `async/await`, as I would expect being a safe default.

If this is indeed buggy behavior then I think this is a big problem because `modern` is a default format, which means if you don't specify a format all of your output bundles will be expected to only run in modern browsers.

**Comment by developit** [comment]
This should be fixed by #570.
