### ISSUE TITLE
Build ignores tsconfig exclude option

### ISSUE THREAD

**Issue by jlkiri** [developit/microbundle#507]
The `exclude` option in `tsconfig.json` seems to be ignored by the bundler. I have the following file structure (subfolders of a `src` folder):
```
+---want_to_exclude
|       index.ts
|
\---want_to_include
        index.ts
        types.ts
```

My `tsconfig.json` include/exclude looks like this:
```
  "include": ["src"],
  "exclude": ["**/want_to_exclude/*.ts"]
```

Microbundle keeps compiling the `want-to-exclude` folder. On the other hand, building manually with `tsc --build` correctly excludes the folder.

**Comment by jlkiri** [comment]
Just in case it helps:
I tried to do the same but in `tsdx`, which is also based on Rollup, as far as I can see. So, either I am doing something wrong, or maybe it is a problem with Rollup?

**Comment by ForsakenHarmony** [comment]
Might be a problem with the typescript plugin 🤔

**Comment by Xiphe** [comment]
Just out of curiosity: What is your usecase? Do you expect `import foo from `../want_to_exclude/foo.ts` to stay present in the bundle? Similar to external dependencies?

A possible workaround could be my proposed extension of the `--external` flag https://github.com/developit/microbundle/pull/478

**Comment by jlkiri** [comment]
The usecase was to keep a subfolder of `src` only for local development (debugging etc.) and not include it into the distribution package.

However I noticed that for some reason I cannot reproduce the problem anymore. I guess I am going to close this issue for now.
