### ISSUE TITLE
some lib can not bundle into file？

### ISSUE THREAD

**Issue by lizy0329** [developit/microbundle#508]
when I `import Vue from 'vue';` It can not bundle vue code into file. But I `import color from 'color';` it work !

is this limit lib size?

**Comment by marvinhagemeister** [comment]
What's the error you're getting?

**Comment by lizy0329** [comment]
> What's the error you're getting?

I try to add `--external` for build, but get Error

In my project, use ES6 no preact/react/vue, just pure js

![WeChat Work Screenshot_20191105194634.png](https://i.loli.net/2019/11/05/jAyVGWpEx1IzvYc.png)

**Comment by marvinhagemeister** [comment]
Ah so the current stable version of `microbundle` doesn't support transpilation of class properties, which is still a proposal that is at stage 3 of the standards process (meaning it's not native in JS just yet).

In the upcoming version of `microbundle` we switched from `bublé` to `babel` which supports transpiling that syntax. You can tryout the upcoming version by installing it via `microbundle@next` which supports that.

**Comment by lizy0329** [comment]
> Ah so the current stable version of `microbundle` doesn't support transpilation of class properties, which is still a proposal that is at stage 3 of the standards process (meaning it's not native in JavaScript just yet).
> 
> In the upcoming version of `microbundle` we switched from `bublé` to `babel` which supports transpiling that syntax. You can tryout the upcoming version by installing it via `npm install microbundle@next` which supports that.

As you say, When I install microbundle@next (0.12.0-next.6) and `npm run build`, I got some Error like that:   zlib_1.brotliCompress is not a funciton

![WeChat Work Screenshot_20191106095506.png](https://i.loli.net/2019/11/06/b7WB5XvCzSjEfRs.png)

**Comment by lizy0329** [comment]
> > Ah so the current stable version of `microbundle` doesn't support transpilation of class properties, which is still a proposal that is at stage 3 of the standards process (meaning it's not native in JavaScript just yet).
> > In the upcoming version of `microbundle` we switched from `bublé` to `babel` which supports transpiling that syntax. You can tryout the upcoming version by installing it via `npm install microbundle@next` which supports that.
> 
> As you say, When I install microbundle@next (0.12.0-next.6) and `npm run build`, I got some Error like that: zlib_1.brotliCompress is not a funciton
> 
> ![WeChat Work Screenshot_20191106095506.png](https://camo.githubusercontent.com/783594758ec3157cd8ff0eb636af5b15da0287b5/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31312f30362f62375742355876437a536a456652732e706e67)

Ah, I update my nodejs to 13.0.1, this problem has resolve. And I think the microbundle documenation is very bad as “Zero-configuration bundler for tiny modules”
