### ISSUE TITLE
Bundle too slow

### ISSUE THREAD

**Issue by lizy0329** [developit/microbundle#513]
```
Version: microbundle@next 0.12.0-next.6
script: 'microbundle watch --external all --format umd --sourcemap false'
dependencies: : {
        "@uppy/core": "^1.6.0",
        "@uppy/dashboard": "^1.5.0",
        "@uppy/locales": "^1.9.0",
        "@uppy/xhr-upload": "^1.4.0",
        "qiniu-js": "^2.5.5"
    }
```

I have to wait 8s for my bundle code.
But I just want to dev my code. It there have some methods to be faster when bundle code?

![WeChat Work Screenshot_20191107184200.png](https://i.loli.net/2019/11/07/KG3sVZ1CEHg2Ino.png)

**Comment by marvinhagemeister** [comment]
You can use the `--no-compress` flag to skip the minification process. It should speed up compilation time noticeably at the cost of a larger bundle size.

**Comment by ericnkatz** [comment]
Slow bundle has been brutal taking ~ 212s to compile 5.5 kb application at the moment.

**Comment by prantlf** [comment]
You can disable gzipping by using the `--raw` switch. No need to slow down the build just to show-off your compressed bundle sizes :-)

**Comment by MarkLyck** [comment]
I wish my bundle time was 8s lol. Mine is more like 3 minutes :(

**Comment by TimDaub** [comment]
> You can use the `--no-compress` flag to skip the minification process.

I feel like even with this flag, the bundling is really slow.

> You can disable gzipping by using the `--raw` switch.

Are you sure that's the case? Docs say `Show raw byte size  (default false)`.
For `microbundle watch` it be really nice to know what costs so much time, to disable it for debugging...

**Comment by marvinhagemeister** [comment]
One area that could likely lead to speed improvements for `microbundle` would be to leverage the new output plugins feature by Rollup@2. That would only run the whole bundling process once instead of for each format (usually 3-5 times). The whole bundling process is what's costing the most time.

**Comment by ForsakenHarmony** [comment]
> Are you sure that's the case? Docs say `Show raw byte size (default false)`.
> For `microbundle watch` it be really nice to know what costs so much time, to disable it for debugging...

@TimDaub yes, it's gzipped in memory to show the size, it can improve build time to some degree

**Comment by developit** [comment]
We've done all that we can for this in Microbundle 0.13. The next major version will use output transpilation as Marvin described.
