### ISSUE TITLE
cjs option prevents modern file

### ISSUE THREAD

**Issue by ozum** [developit/microbundle#518]
Hi,

Using version 0.12.0-next.6,

`src/x.ts` file:
```ts
export async function x(a:number): Promise<number> {
  return a + 1;
}
```

`microbundle -f modern`: x.modern.js file contains `async`.
`microbundle`: Creates x.modern.js file among others, but it __does not__ contain `async`.
`microbundle -f modern,es,umd`: x.modern.js contains `async`.
`microbundle -f modern,es,cjs,umd`: x.modern.js __does not__ contain `async`.

According to last 2 examples, problem seems to related `cjs` option.

Thanks,

**Comment by ForsakenHarmony** [comment]
interesting issue

**Comment by developit** [comment]
Ah I hadn't noticed this issue - it's the same as #582.
