### ISSUE TITLE
Warning: node-resolve options.module is deprecated

### ISSUE THREAD

**Issue by danielkov** [developit/microbundle#521]
With `microbundle` set up according to README I receive the following deprecation warning from `node-resolve` (which I believe is a dependency of rollup in this case):

```sh
node-resolve: setting options.module is deprecated, please override options.mainFields instead
node-resolve: setting options.jsnext is deprecated, please override options.mainFields instead
node-resolve: setting options.module is deprecated, please override options.mainFields instead
```

On the documentation page of [`rollup-plugin-node-resolve`](https://github.com/rollup/rollup-plugin-node-resolve#user-content-usage) we can see what options should be used instead:

```js
// DEPRECATED: use "mainFields" instead
// use "module" field for ES6 module if possible
module: true, // Default: true

// DEPRECATED: use "mainFields" instead
// use "jsnext:main" if possible
// legacy field pointing to ES6 module in third-party libraries,
// deprecated in favor of "pkg.module":
// - see: https://github.com/rollup/rollup/wiki/pkg.module
jsnext: true,  // Default: false

// DEPRECATED: use "mainFields" instead
// use "main" field or index.js, even if it's not an ES6 module
// (needs to be converted from CommonJS to ES6)
// – see https://github.com/rollup/rollup-plugin-commonjs
main: true,  // Default: true
```

It does not (yet) break the build, but I assume after a while this will cause issues.

**Comment by skipjack** [comment]
Seems to be fixed in `microbundle@next` (v0.12.x)  🎉

**Comment by hbroer** [comment]
Yes. Nur In was thinking about to fix the current (legacy) version since month. 

A question for the Dev Team: If I would invest a little time to make some updates (warnings, dependencies) to the .11 would it bei merged, or ist the .11 range no longer maintained? @developit

**Comment by developit** [comment]
@hbroer I'm not against making patch updates to 0.11, though I really want to get 0.12 published as `@latest`. When that happens, it makes a bit less sense to update 0.11.

Btw was there a reason you were sticking with 0.11? 0.12 should be a non-breaking update.

**Comment by hbroer** [comment]
It changes the compilation output a lot and it produced a bigger bundle the last time I tested it (even with aggressive Browserlist settings If I remember right). My tought was to make a major version change of my projects with a microbundle update to .12, so I will stay with .11 until I get the features done for my majors.

**Comment by developit** [comment]
@hbroer apologies for the radio silence regarding 0.11. Were you able to upgrade to 0.12? We cut it over as the stable release in May because it actually produces smaller output than 0.11 in 100% of the tests now. If you have a case where the output is larger, that'd be a super useful thing for us to test against.

**Comment by hbroer** [comment]
yea we are on .12 now. Works pretty fine. Good job as always! :)

**Comment by marvinhagemeister** [comment]
Glad to here that this is resolved 🙌
