### ISSUE TITLE
'--visualize' flag to run rollup-plugin-visualizer?

### ISSUE THREAD

**Issue by AlexHayton** [developit/microbundle#526]
I would like to propose a PR for creating a new `--visualize` CLI flag, which will add the rollup-plugin-visualizer to the toolchain. But wanted to get some feedback before doing it.

This'll really help me, I want to confirm I got all my peerDependencies and externals correct. I wanted to get some feedback on the idea

* Is it worth doing?
* Any qualms about the naming of the CLI flag?
* Anyone already started doing it?

**Comment by marvinhagemeister** [comment]
That's a cool idea, I'd love to have something like that to inspect bundles 👍 Afaik there is nobody working on that, so your good to go! The cli flag name is fine, we can bikeshed later if someone is unhappy with that (doubt it) 🙂

**Comment by AlexHayton** [comment]
@marvinhagemeister I have created a PR, would you be able to give some feedback on it?

One thing I observed, a lot of snapshots changed which I wasn't expecting...

**Comment by AlexHayton** [comment]
Hmm, I really can't get my snapshots to match. Does anyone have any idea?
