### ISSUE TITLE
Investigate why core-js was inlined

### ISSUE THREAD

**Issue by ForsakenHarmony** [developit/microbundle#534]
https://github.com/developit/microbundle/commit/2fef1006914efa2ed9e86effdbdda4ef1b119a13

**Comment by developit** [comment]
ohh gross!

**Comment by developit** [comment]
This actually may be working as-designed. The custom-babelrc pulls in `preset-env`, which transforms async class methods to regenerator in order to work around a bug in Safari 11 (which supports esmodules).

**Comment by developit** [comment]
Turns out it's just the `corejs:3` option for `preset-env` being a bad idea. Fix:
https://github.com/developit/microbundle/pull/550
