### ISSUE TITLE
[Question] can build but not work with react app

### ISSUE THREAD

**Issue by alireza-mh** [developit/microbundle#535]
I am trying to bundle [react-responsive](https://github.com/contra/react-responsive) component with `micorbundle` it will build bundle files but when I'm replacing built code with the old one I face below error:

```
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `BootstrapMediaQuery`.
```

the command that I used  for the build: `npx microbundle --jsx React.createElement`

**Comment by developit** [comment]
@alireza-mh `react-responsive` ships a Webpack-only bundle. Instead, import their source code:

```js
import MediaQuery from 'react-responsive/blob/master/src';
```
