### ISSUE TITLE
`debugger` statements are stripped out of build.

### ISSUE THREAD

**Issue by calebporzio** [developit/microbundle#536]
This is a screenshot in dev-tools from the source map: 
![image](https://user-images.githubusercontent.com/3670578/71696822-015c9880-2d84-11ea-9b10-d1162954626d.png)

This is a screenshot of the actual output file:
![image](https://user-images.githubusercontent.com/3670578/71696851-1afde000-2d84-11ea-8c32-c84b8ce8893f.png)

As you'll notice, the "debugger" statement get's removed during the build.

I use `debugger` all the time when working on my project and testing in a browser or via Jest. Is there a way to disable this behavior?

perhaps an environment variable or something that I can set?

I appreciate the help, and love this project! Thanks!

**Comment by calebporzio** [comment]
Ok, I see it's either a terser or uglify thing.

There's a "drop_debugger" option that defaults to true for terser or uglify.

I dropped back down to using Rollup manually to set this option.

Would love to know if I could override this with microbundle, but not a huge deal.

Thanks!

**Comment by developit** [comment]
@calebporzio question - were you hoping to keep these in for a development build, or a production build?

I believe it's currently possible to preserve `debugger` statements by passing `--no-compress`, which is microbundles "dev" mode (also activated for `microbundle watch`).

**Comment by developit** [comment]
Closing as this seems to be solved. If you want to debug code, use `microbundle build --no-compress` (also works with `watch`).
