### ISSUE TITLE
Add package-lock.json

### ISSUE THREAD

**Issue by Xiphe** [developit/microbundle#542]
I'm having a hard time replicating two failing tests of https://github.com/developit/microbundle/pull/478 locally. I assume one of the reasons is instability of dependencies due to a missing lockfile. 

I assume that adding a package-lock might also cause less greenkeeper related issues (https://github.com/developit/microbundle/issues/520)

The [commit introducing the config without lock](https://github.com/developit/microbundle/commit/bf2d068dc646fcce976456359ee9c4689b74bea6) is two years old, I propose to try re-introducing the lockfile

**Comment by developit** [comment]
It's now been added!
