### ISSUE TITLE
Export Default From Error

### ISSUE THREAD

**Issue by skipjack** [developit/microbundle#546]
First off, thank you for this package. I'm seeing an issue with the `export default from '...'` syntax which surprised me a little as I figure this pattern would be pretty common with library authors. For example, when I try to do the following:

``` js
export Base from './components/base.jsx'
```

I get the following `babel` output:

```
SyntaxError: /Users/greg/Desktop/projects/foundation-utils/src/lib.js: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled
...
Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation.
```

This brings two questions to mind....

- Adding a `.babelrc` that specified that plugin didn't fix the issue. I'm guessing `microbundle` won't pick up a local babel config?
- Since this is a fairly useful/common pattern for library authors, could we just add that plugin to `microbundle` by default?

There is a workaround, but obviously not a super pretty one:

``` js
import $Base from './components/base.jsx'

export const Base = $Base
```

**Comment by Xiphe** [comment]
I don't think this is a `microbundle` problem.

If you want to re-export the default, you should use

```js
export { default } from './components/base.jsx';
```

What you're doing in the workaround is giving the default export a name. There is a shortcut for that:

```js
export { default as Base } from './components/base.jsx';
```

**Comment by skipjack** [comment]
@Xiphe that's definitely a cleaner workaround, thanks! I did a little more research and found that it's still just a stage 1 proposal, so I guess I can understand _not_ supporting it given that there's a fairly simple workaround.

https://github.com/tc39/proposal-export-default-from

**Comment by developit** [comment]
@Xiphe good suggestion.

@skipjack - adding a `.babelrc` should have worked - do you mind pasting what you had in there? Microbundle respects Babelrc for everything except node_modules.

**Comment by Xiphe** [comment]
I honestly was not aware of the export default from proposal. Thanks for letting me know 👍

**Comment by skipjack** [comment]
Sure, just basically followed the instructions [here][1]:

__.babelrc__

``` json
{
  "plugins": [
    "@babel/plugin-proposal-export-default-from"
  ]
}
```

[1]: https://babeljs.io/docs/en/babel-plugin-proposal-export-default-from

**Comment by ForsakenHarmony** [comment]
Are you on the latest microbundle version?

**Comment by skipjack** [comment]
I'm on the latest stable version -- `0.11.0` -- I haven't tried `microbundle@next` yet though.

**Comment by ForsakenHarmony** [comment]
That shouldn't even have babel at all, we used buble before

**Comment by skipjack** [comment]
I mean... it seems to be pulled from somewhere and I don't have it installed in this project. Meaning if I delete my `.babelrc` and the one babel dependency (`@babel/plugin-proposal-export-default-from`), I still get the following error (same as in my original question) which makes it seem like `babel` is being used somewhere under the hood of `microbundle`.

``` bash
SyntaxError: /Users/greg/Desktop/projects/foundation-utils/src/lib.js: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled
...
Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation.
```

**Comment by ForsakenHarmony** [comment]
right, we had babel for async to promises

**Comment by skipjack** [comment]
Closing given the workaround and responses.
