### ISSUE TITLE
Test infrastructure

### ISSUE THREAD

**Issue by Andarist** [developit/microbundle#56]
This tool need a test setup - for obvious reasons. I'd like to work on some features, but I'm totally not confident about making changes.

I'd like to work on this, but I'd like to establish what kind of tests should be written. I feel that snapshot testing might be a good for this - as primary testing solution. Additionally we could write some additional manual tests, but for a tool such as this such tests are often not obvious.

Beside setting up a testing infrastructure I'd appreciate coming up with good testing scenarios (especially for more convoluted options/combination of options etc) that I could not come up with without examinating the source code carefully.

**Comment by developit** [comment]
Definitely. Right now I'm having [issues running microbundle on Travis](https://travis-ci.org/developit/karmatic/builds/332436308). Ideally, a test setup would bypass the CLI trappings and instead invoke microbundle via its Node API on a collection of test projects, asserting over their output.  We do something similar in Preact CLI.

**Comment by developit** [comment]
@Andarist I set up 2 basic tests and a proper runner in #57.

**Comment by Andarist** [comment]
Cool!
