### ISSUE TITLE
How to compile htm to save runtime?

### ISSUE THREAD

**Issue by brielov** [developit/microbundle#572]
Hi, since you also develop `htm`, is there any way to compile it at build time?

**Comment by developit** [comment]
Yep, that's what [babel-plugin-htm](https://github.com/developit/htm/tree/master/packages/babel-plugin-htm) does. It compiles your `html` tags to the same output JSX would have given you.

`npm install babel-plugin-htm`

```
{
  "plugins": [
    ["babel-plugin-htm", {
      "pragma": "React.createElement"
    }]
  ]
}
```

<table><thead><tr><th>input</th><th>output:</th></tr></thead><tbody><tr><td>

```js
const foo = html`
  <div id="foo">
    hello ${you}
  </div>
`
```

</td><td>

```js
const foo = React.createElement(
  "div",
  { id: "foo" },
  "hello ", you
)
```

</td></tr></tbody></table>

**Comment by developit** [comment]
Closing since I would guess this counts as answered - feel free to re-open if it doesn't work!
