### ISSUE TITLE
Cannot create component library based on Material-UI

### ISSUE THREAD

**Issue by chatpongs** [developit/microbundle#575]
I would like to create a component library based on [Material-UI](https://material-ui.com/]) This is a simple exported component in my `index.js`
```
import React from 'react';
import Paper from '@material-ui/core/Paper';
export default () => <Paper>Example</Paper>;
```
Compiled component in .mjs is here
```
import e from"react";import r from"@material-ui/core/Paper";export default function(){return e.createElement(r,null,"Example")}
//# sourceMappingURL=index.mjs.map
```
When this component is imported and rendered in an CRA app, I get the error as in the picture

![error](https://user-images.githubusercontent.com/5669280/75876805-f5a35600-5e48-11ea-914d-c2fce9c6e475.jpg)

**Comment by chatpongs** [comment]
Thank you! Just remove the line below from `package.json` and the error goes away 😀
```
"module": "dist/index.mjs",
```

**Comment by ForsakenHarmony** [comment]
ideally you'd want to change it to

```
"module": "dist/index.module.js",
```
