### ISSUE TITLE
Custom paths with Typescript not properly exported

### ISSUE THREAD

**Issue by TheoSl93** [developit/microbundle#581]
Hi!
first, a little bit of context: I'm currently working on a a project that will make a lot of soap calls and I decided to make a wrapper to make my life easier. This wrapper has every methods and headers that I need, and it needs to be in a separate project/repo, that will be imported in the main project. Because of that, I need to be able to build the new library and import it. 

I've been having problems with the bundling of my files. I need the library self, but also the definition types in typescript to be in the good way exported/bundled. The problem I currently face is related to the routes that I use in the source code versus the routes that are exported in the definition files, because the use of aliases. I've tried without aliases and it doesn't work neither:

 - source file: `import { ResponseEnum } from '@/enums/ResponseEnum'`
- expected compiled: `import { ResponseEnum } from 'dist/types/enums/ResponseEnum'`
- actual compiled: `import { ResponseEnum } from '@/enums/ResponseEnum'`

I've made a [repo](https://github.com/TheoSl93/buildLibraryTest/tree/microbundle-test
) with a `readme.md` file with step by step explanation.

Given my explanation, I'm open to hear how this can be done without using a bundler or using any other method to get this done, just an export with types and source code that can be imported as any other library.

Thanks!

**Comment by ForsakenHarmony** [comment]
What's the issue when you don't use those aliases?

Also do they actually add much for you, auto import with relative exports seems more intuitive?

**Comment by TheoSl93** [comment]
Hi!

I think auto import is the solution to my problem here. Thanks a lot for the idea.

I proceed to close the issue.
