### ISSUE TITLE
Wrong modern output

### ISSUE THREAD

**Issue by jnordberg** [developit/microbundle#582]
When running `microbundle --compress false --format modern` on a typescript package containing async/await code the js still contains the async/await calls but when running with `microbundle --compress false --format cjs,modern` both the modern and commonjs bundle have the async calls converted to promises

**Comment by jnordberg** [comment]
Using 0.12.0-next.8

**Comment by developit** [comment]
This should be fixed by #570. I'll work on getting a release out this week.

**Comment by developit** [comment]
Note: this is a duplicate of #518 and #560.

**Comment by marvinhagemeister** [comment]
Let's continue discussion in #518 and #560 .
