### ISSUE TITLE
Hi I would like to know if is possible to customize webpack config you run adding babel-plugin-wildcard!

### ISSUE THREAD

**Issue by dmitrirussu** [developit/microbundle#593]
I would like to support babel-plugin-wildcard, into my library.. is that possible to create using microbundle?

**Comment by developit** [comment]
Hiya - Microbundle doesn't use Webpack, but it does use Babel and you can customize the config.
Just create a `.babelrc` in your project root:

```json
{
  "plugins": [
    "babel-plugin-wildcard"
  ]
}
```

FWIW Microbundle already supports file globs for entries, so it's not super clear to me why wildcard directory imports would be required.
