### ISSUE TITLE
Document iife format

### ISSUE THREAD

**Issue by hastebrot** [developit/microbundle#595]
The `README.md` could mention the `iife` format.

This works using microbundle `0.11.0` and `0.12.0-next.8`.

```console
$ microbundle build --format=iife --output=dist/
```

**Comment by mindplay-dk** [comment]
You might want to do something more here?

It's not at all obvious that microbundle can be used for applications - I've looked at it dozens of times, I've even used it a few times, and never realized until just now, after finding this issue, that `iife` is even supported.

Everything else in the README seems to point to the idea that microbundle is for libraries only.

> The zero-configuration bundler for tiny modules, powered by Rollup.

Seems to suggest this only works for modules. (Git project title says the same thing.)

> One dependency to *bundle your library* using only a package.json

Could mention "library/project" maybe?

> Creates multiple output formats for each entry (CJS, UMD & ESM)

Could mention IIFE here maybe?

> Microbundle produces esm, cjs, umd bundles with your code compiled to syntax that works pretty much everywhere.

Again, fails to mention IIFE being an option.

I've been torturing myself with custom builds, lengthy Babel configurations, failed attempts at configuring webpack or rollup, and so on... microbundle is really easy to use for libraries, and probably will be for my application too? I wish I had known sooner that this was possible. 😊
