### ISSUE TITLE
When using `cwd` flag with an absolute file path it fails to build.

### ISSUE THREAD

**Issue by CrashyBang** [developit/microbundle#598]
I am using the following command:
```
"build:module": "cross-env-shell CONFIG_PATH=$pwd microbundle build --raw --cwd ./module/sub --alias @=$CONFIG_PATH --jsx React.createElement",
```

And in `module/sub/package.json` I have:
```json
  "source": "index.js",
```

Now this all works as expected, however because of this [PR in parcel](https://github.com/parcel-bundler/parcel/pull/1101) `source` gets read in and parcel tries to compile from the source code which of course does not work because I am using the `@` alias in my code so I can reference all of my modules with absolute paths instead of relative (originally I was doing this in raw rollup, as you can see now it is a bit convoluted using environment variables, could be a good argument for #249). 

So in an attempt to alleviate this I tried removing the `source` entry and doing:
```
"build:module": "cross-env-shell CONFIG_PATH=$pwd microbundle build ./module/sub/index.js --raw --cwd ./module/sub --alias @=$CONFIG_PATH --jsx React.createElement",
```

Which gave me:
```
Error: Could not resolve entry module (module\sub\module\sub\index.js).
```

Which of course makes sense given I am using `--cwd` so I updated it to be:
```
"build:module": "cross-env-shell CONFIG_PATH=$pwd microbundle build ./index.js --raw --cwd ./module/sub --alias @=$CONFIG_PATH --jsx React.createElement",
```

This looked like it worked but it actually didn't generate any files and gave the following output:
```
Build "module" to dist:
```

Ideally I would be able to circumvent `source` where applicable in favor of absolute paths, I am going to open an issue on Parcel as well as it doesn't make sense to use the component source if parcel doesn't understand alias which are quite heavily used in the Vue world and other projects (the project I am working on is `React` for reference).

**Comment by CrashyBang** [comment]
Realted: #176

**Comment by CrashyBang** [comment]
Related Parcel Issue: https://github.com/parcel-bundler/parcel/issues/4549

**Comment by developit** [comment]
Your build command is using cross-env-shell incorrectly. The command passed to `cross-env-shell [KEY=VAL] command` needs to be escaped using quotes, otherwise it will be interpreted by the shell rather than by cross-env. This isn't specific to microbundle, it's just how `cross-env` gets around `cmd.exe` replacing your `$CONFIG_PATH` variable with an empty string.

Here's a working version - note the escaped quotes:

```js
"scripts": {
  "build": "cross-env-shell CONFIG_PATH=$PWD \"microbundle build ./module/sub/index.js --raw --cwd ./module/sub --alias @=$CONFIG_PATH --jsx React.createElement\""
}
```

**Comment by developit** [comment]
FWIW, I would advise against using convenience aliases like `@`. They make your application bundler-specific when it doesn't have to be.
