### ISSUE TITLE
prevent function arguments being renamed

### ISSUE THREAD

**Issue by skiv71** [developit/microbundle#599]
Hi, I'm looking to use microbundler to create a single dist file for my npm module, as vscode intellisense doesn't like too much depth within a project / npm module structure. I've managed to create a build, which appears to work... but I've noticed the output has renamed all the arguments for my functions. These arguments (in original format) are needed for my intellisense to be useful. Can i stop them being reduced to single letters?

**Comment by marvinhagemeister** [comment]
Try running microbundle with `--no-compress`.

**Comment by marvinhagemeister** [comment]
Closing as the question is answered.
