### ISSUE TITLE
tsconfig option does not work

### ISSUE THREAD

**Issue by AndyOGo** [developit/microbundle#600]
If I specifiy `microbundle --tsconfig tsconfig.foo.json`, it still uses `tsconfig.json`

**Comment by developit** [comment]
@AndyOGo are you using the latest Microbundle version (0.12.0-next.9)? By default running `npm install microbundle` will give you `0.11.0`, which doesn't support that option.

**Comment by AndyOGo** [comment]
@developit thanks for your quick answer.
Aright, that's it.
I use `"microbundle": "^0.11.0",`.
