### ISSUE TITLE
How to use compiled styles when they are not included in js bundle.

### ISSUE THREAD

**Issue by oziniak** [developit/microbundle#602]
When using microbundle with css-modules, I see compiled css file `dist/index.css`, and I see correct style names in the DOM (`_dialog-module__label__VCqOQ`). But the `<head>` element of example app doesn't have those styles.

**Comment by marvinhagemeister** [comment]
`microbundle` single purpose is to make packaging for npm easier by abstracting away all the different module formats that need to be created for npm. It's the underlying build tool for popular libraries like [Preact](https://github.com/preactjs/preact) for example.

Your use case doesn't sound like it matches that. That said you can still use `microbundle` for other things than npm packages, by including the necessary references in HTML files yourself.

I'm not sure to which example app you're referring to as we don't have one.

**Comment by oziniak** [comment]
This is weird, as you are still processing css. So why not injecting it? or giving a freedom to do it?
if my understanding is correct shouldn't it be [a simple change](https://github.com/developit/microbundle/blob/master/src/index.js#L527)?

**Comment by marvinhagemeister** [comment]
We have nothing to inject it to, so this setting does nothing. That said we're more than happy to review PRs adding a fully fledged HTML pipeline :tada:
