### ISSUE TITLE
Invalid format: modern

### ISSUE THREAD

**Issue by krutoo** [developit/microbundle#604]
Hi, i get error when run `microbundle -f modern` with `microbundle 0.11.0`

![image](https://user-images.githubusercontent.com/13140130/81332707-e943af80-90bc-11ea-9ff1-1b4c50ad3bb0.png)

How can i resolve this error?

**Comment by developit** [comment]
Hi there - the `modern` format is only supported in Microbundle 0.12+. Install it like this:

```sh
npm install microbundle@next
```
