### ISSUE TITLE
Property mangling breaks TypeScript decorators

### ISSUE THREAD

**Issue by donmccurdy** [developit/microbundle#607]
With a build configured to mangle any properties matching `/^_/`, as described by https://github.com/developit/microbundle/wiki/mangle.json, I have the following input:

```typescript
class Material extends Property {
  @GraphChild private _baseColorTexture: TextureLink = null;
  // ...
}
```

The decorator compiles to the following in uncompressed and compressed modes:

```typescript
// Uncompressed:
__decorate([GraphChild], Material.prototype, "_baseColorTexture", void 0);

// Compressed:
i([h],I.prototype,"_baseColorTexture",void 0)
```

But because the property was renamed, the property name received by the decorator function (`_baseColorTexture`) is not correct at runtime. See [TypeScript • Decorators](https://www.typescriptlang.org/docs/handbook/decorators.html). Decorators are considered an experimental feature, so I'm not entirely shocked that this breaks, but I would be curious if any workarounds are possible. The decorators are saving me a significant amount of boilerplate.

In the meantime, I'm avoiding mangling properties with decorators.

**Comment by developit** [comment]
This is basically working-as-designed - property mangling is only applied to property literals, and decorators aren't property literals. I do think there might be a way to have decorated properties be ignored when mangling, but it'll require switching to a Babel-based mangling solution (like preactjs/preact#2548).

**Comment by donmccurdy** [comment]
That makes sense, thanks —  won't ask you all to change tools just to ignore an experimental TS feature. Might be easier just to log a warning if these options (mangling and decorators) are both enabled at the same time? I would be interested in a property/method mangling solution that doesn't require me to prefix things (i.e. detect if the property is exported) but that's a different feature request for sure.

Feel free to close this if there's nothing else to do, thanks!
