### ISSUE TITLE
Including external library

### ISSUE THREAD

**Issue by alexcarpenter** [developit/microbundle#61]
I am trying to include a library at the top of my file via `import 'wicg-inert` and I get the following error? Is this not possible via microbundle?

![screen shot 2018-01-24 at 12 53 28 pm](https://user-images.githubusercontent.com/825855/35348286-a28a6046-0105-11e8-911d-0bdf4b985d34.jpg)

**Comment by developit** [comment]
what version of `microbundle` are you using?

**Comment by alexcarpenter** [comment]
0.4.1

**Comment by developit** [comment]
These errors should be emitted properly in [0.4.3](https://github.com/developit/microbundle/releases/tag/0.4.3) - can you check again after updating?

**Comment by alexcarpenter** [comment]
That worked, thanks!
