### ISSUE TITLE
Migrate to @rollup/plugin-babel

### ISSUE THREAD

**Issue by mxschmitt** [developit/microbundle#610]
When you try to install `microbundle` the following warning appears:

```
warning microbundle > rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
```

Could be solved by migrating to @rollup/plugin-babel: https://github.com/rollup/plugins/tree/master/packages/babel

**Comment by marvinhagemeister** [comment]
That sounds like an easy fix. Would you (or someone else) like to open a PR?

**Comment by mxschmitt** [comment]
thanks @marvinhagemeister, I was not that familiar with the setup, had tried it myself but was not fully working. 👍
