### ISSUE TITLE
Improve "Modern" description in Readme.

### ISSUE THREAD

**Issue by SeanBannister** [developit/microbundle#613]
As a new user trying to decide between using `--format modern` or `es` I had trouble understanding what "modern" did from reading the readme (at first it wasn't even clear it outputs an ES module). Issue #413 helped me understand it better. But I think the readme could benefit from a better description (happy to contribute). 

The line that's confusing is:

> Modern output still bundles and compresses your code, but it keeps useful syntax around that actually helps compression:

This made me think that modern was a compression algorithm or some way to improve compression algorithms. But I think what that line is trying to say is that modern makes babel ignore your browserslist and only transcompile for "modern" browsers, due to this code tends to be shorter as it doesn't need to add support for older browsers.

Is this correct or am I missing something?

**Comment by ForsakenHarmony** [comment]
Yes, `modern` transpiles for browsers that support `<script type=module>` (overriding the browserlist) which guarantees support for a lot of other features like fetch, arrow functions and promises

Could be more clear in the readme, I agree

**Comment by developit** [comment]
Should be much clearer now!
