### ISSUE TITLE
Specify the name for bundled files

### ISSUE THREAD

**Issue by SeanBannister** [developit/microbundle#615]
Does microbundle provide a way to specify the full file name of the bundled files, I'm trying to output something like: bundle.umd.min.js as these filenames are available on a CDN.

I tried specifying `--output ./dist/bundle.umd.min.js` but it outputs bundle.umd.js I also tried specifying the name in various parts of package.json such as "main", "umd:main", "unpkg".

If there isn't an obvious fix can anyone think of a work around? I considered moving the files in a package.json script but there isn't a consistent way to do that between windows and linux.

**Comment by marvinhagemeister** [comment]
Running `microbundle --help` prints the following description of the output command:

```txt
-o, --output     Directory to place build files into
```

So this flag doesn't specify the filename, but the target folder to place the generated files to.

Instead `microbundle` will take the filename that is chosen in the `"main"` field. Just tried it with the following `package.json` and it correctly generates only files starting with `foo*`.

```json
{
  "name": "foo",
  "main": "dist/foo.js",
  "module": "dist/foo.module.js",
  "source": "src/index.js",
  "scripts": {
    "build": "microbundle build"
  },
  "dependencies": {
    "microbundle": "^0.12.0"
  }
}
```

**Comment by SeanBannister** [comment]
It appears it's only possible to generate the start of the filename though, is there a way to specify the full filename? For example my use case of generating the filename: foo.umd.min.js

**Comment by marvinhagemeister** [comment]
No it's not possible and I'm not sure how that would work with multiple formats. Specifying the complete filename would only work with a single target file. You're best bet is to call a scripts afterwards to rename/move the files. You can use a node script if you're worried about portability. We use that approach in our [build for Preact](https://github.com/preactjs/preact/blob/da382e13d9377a53056e4cb0fd741f6e0aadf1c1/config/node-13-exports.js#L20-L27).

Open for ideas, if anybody has a good approach to solve that.

**Comment by developit** [comment]
Regarding the package.json script, [ncp](https://npm.im/ncp) works on all operating systems: `ncp dist/bundle.umd.js dist/bundle.umd.min.js `
