### ISSUE TITLE
Ability to disable CSS minification if needed

### ISSUE THREAD

**Issue by chopfitzroy** [developit/microbundle#617]
Looking at #121 if compress is true then CSS is minified by default (which includes minification of class names.

This can prove and issue if you want to export the CSS and use it somewhere else, would it be possible to have a separate flag to explicitly toggle CSS minification?

Cheers.

**Comment by maraisr** [comment]
I think the minification of class names is a side effect issue with the work i did to add css-modules.

Think fundamentally it was a problem with rollup postcss.

See: https://github.com/developit/microbundle/pull/370#issuecomment-583174062

I can see its affecting people; Ill push a PR their way to fix this.

**Comment by katywings** [comment]
This is actually related to css modules, not cssnano :).

Its a bug in rollup-plugin-postcss: egoist/rollup-plugin-postcss#281

As a workaround you can just disable css-modules if you don't use them: `--css-modules false`

**Comment by BadMask121** [comment]
This helped fix the issue of css minification changing classname but css file still dont get imported when js file built

**Comment by katywings** [comment]
@BadMask121 This issue here is related to css minification / css modules. What you are describing sounds like a different problem, therefore I recommend you to open up a seperate issue. If you do create another issue, please also add a reproduction repository! (:

**Comment by developit** [comment]
`--compress false` and `--no-compress` will now disable CSS minification in Microbundle 0.13.

**Comment by midzer** [comment]
CSS gets minified for me with `--no-compress `using `"microbundle": "^0.15.1"`.

JavaScript is not minified though.
