### ISSUE TITLE
Typescript : should use rollup-plugin-typescript2 instead of rollup-plugin-typescript

### ISSUE THREAD

**Issue by freeman** [developit/microbundle#63]
Great to see the progress on typescript integration !

However the current version uses [rollup-plugin-typescript](https://www.npmjs.com/package/rollup-plugin-typescript) which uses Typescript 1.8 which is very old.

I think switching to [rollup-plugin-typescript2](https://www.npmjs.com/package/rollup-plugin-typescript2) should bring better defaults. In addition I think this should help with #58

**Comment by developit** [comment]
Good catch!

**Comment by freeman** [comment]
Happy to do a PR soon if nobody is on it.

**Comment by developit** [comment]
That'd be awesome @freeman

**Comment by freeman** [comment]
For my use case, seems the rollup-plugin-typescript2 would be a better fit because it supports generating `.d.ts` files from the typescript sources which I consider an essential feature. 

I have tested it and it seems to work perfectly... I'll send a PR and we'll discuss around it ?
