### ISSUE TITLE
"type": "module"

### ISSUE THREAD

**Issue by web2033** [developit/microbundle#641]
Do I need it? How does it work with microbundle?
(I'm shipping ESM but need for it to work with SSR)
https://nodejs.org/api/esm.html#esm_package_json_type_field

**Comment by marvinhagemeister** [comment]
Those fields are new and introduced with Node 13+ . The official node documentation has an excellent page which describes in detail what they do and how they're supposed to be used.

https://nodejs.org/api/esm.html

We're curious about ways how microbundle can improve that workflow even more. Let's continue the discussion in #594 .
