### ISSUE TITLE
unpkg - cannot override name

### ISSUE THREAD

**Issue by web2033** [developit/microbundle#642]
I set
`"unpkg": "dist/foo.min.js"`
but output is always 
`dist/foo.umd.js`
not matter what name is in that field

**Comment by marvinhagemeister** [comment]
From a quick peek at the source it seems like we only support `umd:main` currently. Either the README is outdated or the feature to support the `unpkg` is missing in our code. Conceptually the `unpkg` bundle seems to be exactly the same as `umd:main`. How should we proceed @developit ?

**Comment by web2033** [comment]
`"build" : "microbundle --name min"`

doesn't have an effect either

**Comment by marvinhagemeister** [comment]
> "build" : "microbundle --name min"
>
> doesn't have an effect either

You're conflating the export name with the filename here. The `--name` cli flag ensures that the umd module uses the specified identifier as the global variable.

```bash
microbundle build --name foobar
```

will result in the code being available under the `foobar` variable:

```html
<script src="/my-umd-build.js"></script>
<script>
  console.log(foobar) // Logs out exports of my library
</script>
```

**Comment by web2033** [comment]
> You're conflating the `export` name with the file name here.

Got it. Thanks.

> From a quick peek at the source it seems like we only support umd:main currently. Either the README is outdated or the feature to support the unpkg is missing in our code.

Yes. 
`"umd:main": "dist/foo.min.js",` has worked for me, though docs are conflicting about that.
