### ISSUE TITLE
How about dts-bundle

### ISSUE THREAD

**Issue by yisar** [developit/microbundle#644]
https://www.npmjs.com/package/dts-bundle

Bundle `*.d.ts` to `name.d.ts`

**Comment by marvinhagemeister** [comment]
I'd love to know more about the advantage of bundling `.d.ts` files. Currently TypeScript is always able to resolve the unbundled typings correctly. Where you running into a specific issue?

**Comment by wardpeet** [comment]
Hi,

Since we didn't receive an answer I'm going to close this now. Feel free to re-open the issue or create a new one if you're ready to provide some more information.

Thanks for using Microbundle
