### ISSUE TITLE
[API] watch mode hook

### ISSUE THREAD

**Issue by bohdanbirdie** [developit/microbundle#645]
I opened this issue after checking the docs.

Is it possible to run a custom script after the build was executed in the `watch` mode?

I'm using a `yalc` to link react components lib to the main app and develop locally faster and looking into running `yalc push` command after the build was made.
I made a custom watcher with `nodemon`, but it appears to be 2x slower.

Thanks for the great tool!

**Comment by developit** [comment]
If you use microbundle as a module there's an onBuild hook:

```js
const microbundle = require('microbundle');

microbundle.watch({
    // Same as CLI args
    onBuild() {
        console.log('bundled')
    }
})
```

**Comment by bohdanbirdie** [comment]
Thanks!
Gonna dig into it!
