### ISSUE TITLE
comments stripped from output with --no-compress

### ISSUE THREAD

**Issue by cdaringe** [developit/microbundle#647]
# problem

hi, i'm using create-react-library, and found that even with `--no-compress` passed, my `/* inline-comments */` are stripped against expectation.  infact, i always want comments retained, but don't see any option to configure that. any tips?

thanks!

**Comment by developit** [comment]
Good catch, looks like an oversight. I've opened a PR with the fix.

**Comment by cdaringe** [comment]
:tada:
