### ISSUE TITLE
Add flag to add version comment. 

### ISSUE THREAD

**Issue by chiptoe** [developit/microbundle#654]
Add flag that will add version comment to start of each dist file based on version in package.json.

**Comment by developit** [comment]
What's the motivation for this feature?

**Comment by chiptoe** [comment]
Meanwhile I found related issue: https://github.com/developit/microbundle/issues/104#issuecomment-371969630

Sometimes I include dist files directly in my repo, so I don't need to publish npm package. In this case it is nice to have information that build version correspond to package version. 

More I think about it it should not be probably part of microbundle because version should be bumped after successful build and then I can prefix dist files. 

Or I will need flag like:
 --buildAndBumpVersionWithVersionCommentPrefixed 😀

Comment will be prefixed after minification. 
As mentioned in related issue I can do this using gulptask in postbuild script.

**Comment by chiptoe** [comment]
Ok it just complicates stuff, I will just not use it 😂. 

You will have to manage alpha,  beta, rc versions. And also you will need to bump, if there is error during build than rollback version back. Oh gosh, I think we can close this 😂. Anyways thanks.

**Comment by developit** [comment]
Yeah gulp or similar would be good for this. We could potentially expose Rollup's existing banner option, which would allow this. It's a bit gnarly to configure via CLI though.

**Comment by chiptoe** [comment]
Anyways I think version should be bumped after successful build. That means rollup at time of bundling doesn't know new version.

Workflow will be like:
Bundle code -> Bump version -> Simple task that just do prefixing so there is small chance to crash.

This workflow can be accomplished using gulp task.

**Comment by chiptoe** [comment]
I can't really imagine we can implement something like this as part of microbundle..

**Comment by chiptoe** [comment]
I will try to live without it, or use bundler independent gulp task solution. Now it does not make sense for me to implement feature like this directly into bundler. 

Thanks, for your time and keep rocking guys 🎸

**Comment by bhch** [comment]
> We could potentially expose Rollup's existing banner option, which would allow this.

@developit Hello, are there any plans to implement this?
