### ISSUE TITLE
Issues compiling when migrating from 0.11 to 0.12

### ISSUE THREAD

**Issue by CrashyBang** [developit/microbundle#659]
Heya,

I have a project that is using [Capacitor](https://github.com/ionic-team/capacitor) and while I can compile it in version `0.11.0` it falls over in `0.12.0`, given that it does work in `0.11.0` and not `0.12.0` I am guessing this is a bundling issue but please let me know if I need to redirect my query to capacitor.

I have also tried using `microbundle@next` to bundle and I am running into the same issue.

A shimmed down version of my capacitor code is as follows:

```js
import { Capacitor, Plugins } from "@capacitor/core";

const { Device } = Plugins;

const platform = Capacitor.getPlatform();

const resolveAndroidInformation = () =>
  new Promise((resolve) => {
    console.log("Attempting to connect to the Android device.");

    if (platform !== "android")
      return resolve({
        error: "Incorrect platform, Android resolver terminating.",
      });

    const deviceHandler = async () => {
      try {
        const info = await Device.getInfo();

        return resolve({
          info,
          // Additional info
        });
      } catch (error) {
        return resolve({
          error: `Failed to connect to Android device: ${error}.`,
        });
      }
    };

    deviceHandler();
  });

export { resolveAndroidInformation };
```

And when it successfully logs:

```
Attempting to connect to the Android device.
```

And then the promise it is meant to resolve, resolves as `undefined` before logging:

```
Incorrect platform, Android resolver terminating.
```

**NOTE** I am running in a web environment and expect this code to fail, `platform` does return `"web"` when logged.

The way this promise is called is as follows:

```js
const populateDeviceInfomation = () =>
  new Promise(async resolve => {
    const control = [resolveAndroidInformation(), resolveChromeInformation()];

    for await (const result of control) {
      const { error } = result || { error: 'Result in device provider appears to be `undefined`, moving to next resolver' };

      if (error) {
        console.log(error);
      } else {
        return resolve(result);
      }
    }

    return resolve({ error: 'Unable to resolve any infromation: All resolvers failed' });
  });
```

And basically what happens is the `'Result in device provider appears to be ``undefined``, moving to next resolver` message is logged infinitely (40,000+ then browser freezes).

Now I am aware this is a `for await` loop and looking at [previous commits](https://github.com/developit/microbundle/pull/596) I can see tweaking has been made here, additionally [Capacitor](https://github.com/ionic-team/capacitor) is written in Typescript which may or may not have an impact.

I tried to figure out what had changed between `0.11.0` and `0.12.0` but couldn't quite figure it out and was hoping it may be obvious to someone more involved with the project.

**Comment by developit** [comment]
Are you able to try the `--format modern` output? It doesn't transpile async/await. 

My guess is the same as the your's, that this is related to the async plugin. I believe it is currently possible to work around that by adding a `babel.config.js` containing:

```js
module.exports = {
  presets: [
    ['env', {
      loose: true
    }]
  ]
}
```

**Comment by CrashyBang** [comment]
Hey,

My resolutions seemed to break using `--format modern` (I will look into this further eventually, it was to do with not explicitly using `/index.js` and the end of some of my imports....).

I tried the mentioned `babel.config.js` to no avail, I also tried:

```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        exclude: ['transform-regenerator'],
      },
    ],
  ],
};
```

But no luck...

**Comment by developit** [comment]
Yes, the move from Bublé is the underlying cause here. Specifically, it is caused by this issue: rpetrich/babel-plugin-transform-async-to-promises#49.

**Comment by CrashyBang** [comment]
That worked perfectly, thank you!
