### ISSUE TITLE
How can i use less-loader

### ISSUE THREAD

**Issue by ranzhu123** [developit/microbundle#662]
i need use less-loader,but i found that the postcss config is fixed,and I could only use CSS configuration.

file: node_modules/microbundle-crl/src/index.js

![image](https://user-images.githubusercontent.com/12227617/84876075-664d4600-b0b9-11ea-8b8d-f81bba1d35f3.png)

**Comment by developit** [comment]
Hiya - this is not webpack, so less-loader is not available. However, `less` and `sass` are both supported by default, you simply need to install the relevant processor:

```sh
npm i -D less
```

Now you can import `.less` files.

**Comment by developit** [comment]
I'm going to close this out as wontfix since Microbundle is specifically not trying to be a general-purpose configurable bundler, and this falls into that territory. Please let me know though if the above doesn't work.

**Comment by namco1992** [comment]
Hello @developit , I tried with your approach but stuck with an error like below:
```bash
$ microbundle --no-compress --format modern,cjs
(postcss plugin) Error: Inline JavaScript is not enabled. Is it set in your options?
```
I understood that I need to set `javascriptEnabled: true` as what we usually do for webpack less-loader, but I can't find how to handle it with microbundle, can shed some light on this? Thank you very much!

**Comment by developit** [comment]
You'd have to find a dotfile used by rollup-plugin-postcss. Microbundle does not allow customization of CSS beyond filenames.
