### ISSUE TITLE
rollup-plugin-typescript2 does not support custom options

### ISSUE THREAD

**Issue by wulv** [developit/microbundle#670]
rollup-plugin-typescript2 does not support custom options，eg:
- check: Set to false to avoid doing any diagnostic checks on the code.
- verbosity: 1
- abortOnError

**Comment by marvinhagemeister** [comment]
Those options are all supported directly by TypeScript itself. Check the page about [compiler options](https://www.typescriptlang.org/docs/handbook/compiler-options.html) for how to enable those.

**Comment by wulv** [comment]
When an error occurs, rpt2 will exit directly
