### ISSUE TITLE
How to bundle everything into one file

### ISSUE THREAD

**Issue by PeterBurner** [developit/microbundle#677]
# Description  
I'm trying to bundle multiple JS source files into one single distribution file with `microbundle`. Unfortunately either the output file contains `require` statements which can't be resolved or I get multiple output files.  
Here is some sample code:  
  
**package.json**  
```
{
  "name": "test",
  "version": "1.0.0",
  "main": "dist/index.js",
  "source": "src/index.js",
  "devDependencies": {
    "microbundle": "^0.12.2"
  }
}
```  
  
**src/index.js**  
```
const x = require('./helper');

x.doStuff();
```  
  
**src/helper.js**  
```
exports.x = function() {
  console.log('test');
}
```  
  
  
If I run `microbundle build --strict --format cjs --target node` I get a `index.js` file with a `require` statement which I cant use on its own:  
  
**dist/index.js**  
```
require("./helper").doStuff();
//# sourceMappingURL=index.js.map
```  
  
If I run `microbundle build 'src/*.js' --strict --format cjs --target node` I get output files for `index.js` and `helper.js`.  
Instead I want one output file with all my source code bundled together.  
Did I miss some CLI parameter? Is what I'm trying to achieve even possible with `microbundle`? Or did I perhaps misunderstand the purpose of this library completely?

**Comment by marvinhagemeister** [comment]
`microbundle` works on the assumption that your code is authored with ES6 `import` statements. Authoring in `commonjs` is not supported as it is impossible to convert it to correct `import` statements in all cases.

So in short: Use `import` statements, not commonjs.

**Comment by PeterBurner** [comment]
ah  
thanks  
that wasn't made quiet clear in the readme
