### ISSUE TITLE
How can I include SVGs in a build?

### ISSUE THREAD

**Issue by bkiac** [developit/microbundle#679]
I import SVG files in my React project like this:
```js
import { ReactComponent as Icon } from "../../assets/bee-box-logo.svg";
```
but the build fails with this error message:
```bash
$ microbundle --jsx React.createElement
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)

at /home/bkiac/Repos/space-apps/honeycomb/src/assets/bee-box-logo.svg:1:0

1: <svg width="67" height="48" viewBox="0 0 67 48" fill="none" xmlns="http://www.w3.org/2000/svg">
```

How can I include SVGs in my microbundle build? Can I extend the microbundle config and add plugins to the underlying rollup config?

**Comment by marvinhagemeister** [comment]
Nope, for that we recommend going with `rollup` directly and writing a config for your needs. Another option is to paste the svg into your JavaScript files as a React component. That is usually beneficial if you need to colorize icons as you have now the additional option of using `currentColor`.

**Comment by katywings** [comment]
@bkiac An other alternative could be to pregenerate your svgs into react components with https://github.com/gregberge/svgr

**Comment by ForsakenHarmony** [comment]
I do something similar with https://github.com/ForsakenHarmony/preact-feather, but it's a bit more manual than i.e. svgr and I only use microbundle there for cjs and umd

**Comment by olance** [comment]
@marvinhagemeister I have the same need as @bkiac and so am wondering: any "easy" path from microbundle to rollup in that case? 
Any way to get a ready-to-use rollup config from microbundle for instance?

**Comment by marvinhagemeister** [comment]
@olance The rollup config from microbundle is declared here: https://github.com/developit/microbundle/blob/a6eb6e75b0bea09ddcb127689cde77b4e75f86f2/src/index.js#L405

**Comment by olance** [comment]
Thanks! Indeed I've taken the time to actually search and found that quite easily, sorry for asking before searching 🙈
