### ISSUE TITLE
Standalone interface files are not present in the output (v0.12.3)

### ISSUE THREAD

**Issue by discordelia** [developit/microbundle#690]
I have a fairly simple project that can be found here: https://github.com/ninohane/ts-collections (This github account also belongs to me).

When using the microbundle version 0.11.0, the standalone interface files are present in the output. But when using version 0.12.3, the build process does not produce those files anymore. 

You can test it by using the repository above. Build it normally and see the interface files are in the ouput. Then change the microbundle version in package.json to 0.12.3 and build it again. The interface files will not be there anymore.

What is the reason for this and how can I fix it? Any help is appreciated.

Thank you.

**Comment by developit** [comment]
This should be fixed as of #589, going out soon. Please re-open if it's not!

**Comment by JoePotentier** [comment]
@discordelia did you get his working? I upgraded to 0.13.0 from 12 and can't get my interface files to show up in the output.
