### ISSUE TITLE
Extend babel config

### ISSUE THREAD

**Issue by oemueller** [developit/microbundle#691]
Thanks for building this awesome tool. 
Currently I'm struggling to add a Babel plugin to the config of my project. Could not find the information in the docs.
I tried babel.config.js and .babelrc but it does not seem like the plugin gets called.

Any advice? 

Oliver

**Comment by developit** [comment]
As long as you're using Microbundle 0.12+, `.babelrc` should be respected:

```js
{
  "plugins": [
    [
      "your-plugin-name",
      {
        "option": "value"
      }
  ]
}
```

**Comment by developit** [comment]
Closing since we know this works based on the tests passing - you can see an example here:
https://github.com/developit/microbundle/tree/master/test/fixtures/basic-babelrc
