### ISSUE TITLE
destructuring string error

### ISSUE THREAD

**Issue by boenfu** [developit/microbundle#693]
input:
```ts
 {
    size: [...text].reduce(
      (size, char) => (char.charCodeAt(0) & 0xff00 ? size + 2 : size + 1),
      0,
    ),
 }

// text = 'abc' => ['a','b','c']
```

output:
```js
{size:[].concat(a).reduce(function(n,e){return 65280&e.charCodeAt(0)?n+2:n+1},0)}

// a = 'abc' => ['abc']
```

build scripts
```json
"scripts": {
    "build": "microbundle build --css-modules false --jsx React.createElement -f es --tsconfig tsconfig.json",
}
```

tsconfig
```json
{
  "compilerOptions": {
    "target": "ES5",
    "module": "ESNext",
    "lib": ["ESNext", "DOM"],
    "jsx": "react",
    "strict": true,
    "sourceMap": true,
    "allowJs": true,
    "moduleResolution": "Node",
    "outDir": "./lib",
    "baseUrl": "./src",
    "paths": {
      "~/*": ["./*"]
    },
    "declaration": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "downlevelIteration": true
  },
  "include": ["src/**/*"]
}
```

I'm not sure if it's the error of microbundle or rollup,so i create this issue.
When I just use tsc build , it`s seems normal.

Thanks

**Comment by wardpeet** [comment]
Thank you for reporting.

It seems to be an error with babel loose mode.
[babl repl](https://babeljs.io/repl#?browsers=defaults&build=&builtIns=false&spec=false&loose=true&code_lz=MYewdgzgLgBFCmAPWBeGByAhgI2Og3AFCiSyIxoDehMtMEAlgF7wBcMA2gHQ8LIC6XAE7wAJgFdg8ABQ06taYxYAaGMAAWmIQEoKAPhjSNWrsaEBhEKPgBBKNIAMugGQwHiAGYeHDmAH56ZngYAGoYACYYdiVgsIBGbWU5eQck-USaAF8iYnAIEAAbeC4CkABzaT4obXwgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=false&targets=&version=7.11.1&externalPlugins=)

I'm not sure we consider this a bug. I'll chat with the team what to do with this one.

**Comment by developit** [comment]
Yep, this is a loose mode thing. Microbundle favors output size over correctness, and in this case it's not possible to cater to both.  FWIW, you have TypeScript set to `downlevelIteration:true`, which also does not support using rest spread on strings.

I would suggest using `Array.from()` here anyway - performance of string spread is abysmal.

```diff
 {
-   size: [...text].reduce(
+   size: Array.from(text).reduce(
      (size, char) => (char.charCodeAt(0) & 0xff00 ? size + 2 : size + 1),
      0,
    ),
 }
```

**Comment by boenfu** [comment]
> Yep, this is a loose mode thing. Microbundle favors output size over correctness, and in this case it's not possible to cater to both. FWIW, you have TypeScript set to `downlevelIteration:true`, which also does not support using rest spread on strings.
> 
> I would suggest using `Array.from()` here anyway - performance of string spread is abysmal.
> 
> ```diff
>  {
> -   size: [...text].reduce(
> +   size: Array.from(text).reduce(
>       (size, char) => (char.charCodeAt(0) & 0xff00 ? size + 2 : size + 1),
>       0,
>     ),
>  }
> ```

Yes, I have replaced it with Array.from to solve it, thank you for your reply
