### ISSUE TITLE
Rollup and commonjs plugin

### ISSUE THREAD

**Issue by brettz9** [developit/microbundle#697]
The `@rollup/plugin-commonjs` (13.0.2) expects a peer of rollup@2.3.4 but the range given for rollup in micobundle is `^1.32.1`, not allowing a major bump, so warnings are being given about this.

**Comment by wardpeet** [comment]
Thanks for letting us know, you're correct. That's a miss by us when we upgraded our deps. We're currently waiting for an upstream fix so we can upgrade all our packages correctly https://github.com/developit/microbundle/pull/680
