### ISSUE TITLE
Specifing --output flag appends folder name to bundle files

### ISSUE THREAD

**Issue by BadMask121** [developit/microbundle#698]
**Without --output**
`$ microbundle-crl --no-compress --external @emotion/core,react-dom,@emotion/styled,emotion-theming,@styled-system/core,@chakra-ui/core --format modern,cjs --tsconfig ./tsconfig.json
Build "attachment" to dist:
      14.9 kB: index.js.gz
      12.8 kB: index.js.br
      14.9 kB: index.modern.js.gz
      12.8 kB: index.modern.js.br
✨  Done in 13.48s.

 `yarn build`

**With--output**
yarn run v1.22.4

$ microbundle-crl --no-compress --external @emotion/core,react-dom,@emotion/styled,emotion-theming,@styled-system/core,@chakra-ui/core --format modern,cjs --output lib --tsconfig ./tsconfig.json

Build "attachment" to lib:
      14.9 kB: attachment.js.gz
      12.8 kB: attachment.js.br
      14.9 kB: attachment.modern.js.gz
      12.8 kB: attachment.modern.js.br
✨  Done in 10.28s.`

**Comment by wardpeet** [comment]
Hey,

I it possible to create a small repro? What do you mean exactly with appends folder name?

Thank you for using microbundle! <3

**Comment by developit** [comment]
This repository is for Microbundle, you are using `microbundle-crl` which is a fork. I have no idea what they changed, and I don't think this bug exists in normal Microbundle.

**Comment by wardpeet** [comment]
Oh I thought it was an alias, thanks @developit 👍

**Comment by developit** [comment]
I may reach out to them and ask if there's a way to unfork, this is going to be a bit of a pain for maintenance.
