### ISSUE TITLE
AsyncFunction constructor converted to Function as part of bundling? 

### ISSUE THREAD

**Issue by stephenhandley** [developit/microbundle#721]
Was surprised by this and can't find any mention of it in issues.. 
```
console.log('hi microbundle', {
  fn: (function () {}).constructor,
  afn: (async function () { return 'lol'; }).constructor
});
```

after bundling... 
```
hi microbundle { fn: [Function: Function], afn: [Function: Function] }
```

I was assuming I'd see a parallel to what i've seen since at least node 10
```
hi microbundle { fn: [Function: Function], afn: [Function: AsyncFunction] }
```

**Comment by developit** [comment]
@stephenhandley - if you use `microbundle --target node`, native async functions will be used. The default output in Microbundle is browser code, where the main 3 bundles target IE11+ and a `.modern.js` bundle targets `<script type=module>`.

**Comment by stephenhandley** [comment]
@developit I am using `--target node` and still seeing the above. 
```
  "scripts": {
    "build": "microbundle --target node",
    "clean": "rm -rf node_modules && rm -rf dist",
    "dev": "microbundle watch --target node",
    "lint": "eslint ./src",
    "test": "yarn nyc mocha --ui bdd test.js"
  },
```

**Comment by developit** [comment]
@stephenhandley do you have a browserslist or engines.node configuration in this project? Or a custom Babel config?

**Comment by stephenhandley** [comment]
@developit nope of them. I tried adding 
```
  "engines" : {
    "node" : ">=10.16.0"
  }
```
and still seeing the above

**Comment by stephenhandley** [comment]
Here's the code for reference
The above snippet
https://github.com/Hello10/util/blob/is-function-issue/src/index.js#L1-L4

Implementation
https://github.com/Hello10/util/blob/is-function-issue/src/isFunction.js#L1-L9

Failing test
https://github.com/Hello10/util/blob/is-function-issue/test.js#L434

**Comment by developit** [comment]
Ah yeah, this is already fixed by #707. It's merged and will be released soon.

**Comment by marvinhagemeister** [comment]
Closing because it's fixed in master.

**Comment by stephenhandley** [comment]
@developit @marvinhagemeister any ETA on the release for this?
