### ISSUE TITLE
Keeping directory structure

### ISSUE THREAD

**Issue by hanselabreu** [developit/microbundle#724]
Hello, is there a way to preserve the directory paths when bundling instead of bundling everything into one file? Can't seem to find anything on the documentation on that. 

Basically `src/folder/index.js` -> `dist/folder/index.js`

**Comment by marvinhagemeister** [comment]
There is no way to preserve the directory structure per se, but you can specify where to put the generated files by setting the `main` and `module` fields in `package.json` accordingly:

```json
{
  "main": "dist/folder/index.js",
  "module": "dist/folder/index.module.js",
}
```
