### ISSUE TITLE
Svelte support

### ISSUE THREAD

**Issue by dmitrykurmanov** [developit/microbundle#728]
If I understood the idea of the **microbundle** correctly it would be great to use it for Svelte as well. Is it possible?

**Comment by ForsakenHarmony** [comment]
> "Zero-configuration` bundler for tiny modules (/libraries)."

Microbunde is kinda made for libraries, not for bundling applications, what we're you thinking of?

**Comment by dmitrykurmanov** [comment]
I am thinking about creating UI libraries (components) based on Svelte not applications.

For example grid component or calendar something like that :) 

Then we could package the component into UMD build and provide to use as standalone and crossframework component. In fact you could replace svelte with any other framework with tiny output bundle (preact, hyperapp, etc). I am just interested in Svelte.

**Comment by developit** [comment]
I love the idea, and I'm super interested in this type of compile-to-* setups. That being said, Microbundle really isn't the right thing to build this on - doing this requires low-level bundler integration (for things like subresources, css, etc) that we can't provide. Rollup is super awesome and far more configurable than Microbundle, it's certainly a better place to start.
