### ISSUE TITLE
Minification breaks build but using Prettier fixes it 🤔

### ISSUE THREAD

**Issue by brandonpittman** [developit/microbundle#729]
I've got a React Hook I'm making and the Babel output works fine. After running it through Microbundle, the minified file throws an error in the browser. If I format the code with Prettier, the error goes away. You can see the source code in the [repo](https://github.com/brandonpittman/use-idb-keyval/blob/master/src/idb.js), but I'll post the source here too.

Oddly, if you return a value in the Promise that includes the `args` param from `call` function, the error also goes away.

```javascript
const dbp = new Promise((resolve, reject) => {
  const openreq = window.indexedDB.open("use-idb-keyval", 1);
  openreq.onerror = () => reject(openreq.error);
  openreq.onsuccess = () => resolve(openreq.result);
  openreq.onupgradeneeded = () => openreq.result.createObjectStore("idb");
});

export const call = async (type, method, ...args) => {
  const db = await dbp;
  const transaction = db.transaction("idb", type);
  const store = transaction.objectStore("idb");

  return new Promise((resolve, reject) => {
    const req = store[method](...args);
    transaction.oncomplete = () => resolve(req);
    transaction.onabort = transaction.onerror = () => reject(transaction.error);
  });
};

export const get = async (key) => (await call("readonly", "get", key)).result;
export const set = (key, value) =>
  value === undefined
    ? call("readwrite", "delete", key)
    : call("readwrite", "put", value, key);
```

**Comment by developit** [comment]
Hi @brandonpittman - is the above code sample before or after prettier runs on it?

**Comment by brandonpittman** [comment]
@developit I meant that if I run Prettier in the output file, it works. Weird, I know. Something about the standard output when it’s minified.

**Comment by developit** [comment]
Right - re-reading, I'm assuming the code snippet you posted is the source (input to microbundle) then.

**Comment by developit** [comment]
One thing to consider here: IndexedDB does not work with transpiled promises, because they fall outside of transaction boundaries. It looks like you're using a custom Babel config, which is unnecessary for Microbundle and probably causing this issue.

**Comment by brandonpittman** [comment]
@developit Deleted the `.babelrc` but got a slightly different—but related—error about number of arguments. Thanks for trying to help! 🙇🏻

**Comment by developit** [comment]
Hi @brandonpittman - was the issue related to transpiled Promises?

**Comment by brandonpittman** [comment]
@developit Doesn't seem to be related to transpiled Promises because formatting the output code fixes the problem. Prettier isn't unminifying it or untranspiling it. And just running it through bare Babel, which would transpile it, works just fine. I gave up and went back to Babel since it just worked.

**Comment by developit** [comment]
Alright - I'm going to re-open this then, since it doesn't seem like a solved problem.
