### ISSUE TITLE
Better tree-shaking for React components

### ISSUE THREAD

**Issue by omgovich** [developit/microbundle#730]
Hi! Thanks for your work! Love **microbundle** and use it every day.

I'm the maintainer of an open-source React-components library and I recently noticed that when I use `React.forwardRef` or `React.memo` the components became un-tree-shakeable.

I dig into this problem and found out that Babel fixed that several months ago in their @babel/preset-react package:
https://babeljs.io/blog/2020/05/25/7.10.0#better-tree-shaking-for-react-components-11428httpsgithubcombabelbabelpull11428

Unfortunately, I couldn't find a way to use it with **microbundle**.

**Comment by developit** [comment]
I believe currently we remove `@__PURE__` annotations, which is affecting this.

**Comment by omgovich** [comment]
Hi, thanks for fast response)
There is no way to automatically mark things like `React.forwardRef` as pure annotations except using `@babel/plugin-transform-react-pure-annotations` (which is included to `@babel/preset-react`).

**Comment by omgovich** [comment]
See: https://github.com/babel/babel/pull/11428/files

**Comment by developit** [comment]
Have you tried using a custom babel configuration with Microbundle?  `.babelrc` / `"babel"` in package.json is supported, so you could add `{"presets":["@babel/preset-react"]}`.

**Comment by omgovich** [comment]
Hi @developit!
Started to dig deeper into my build output.

First thing I found out that if I set `--no-compress` my bundle has `/*#__PURE__*/`. If compression is enabled, all comments including PURE ones are gone.
I assume that Terser just cleans all comments. Probably we should find a way o ask him to ignore `/*#__PURE__*/`.

**Comment by omgovich** [comment]
Second thing:

`@babel/plugin-transform-react-pure-annotations` is a part of `@babel/preset-react` which already installed to my project with `microbundle`.  Besides that `@babel/preset-react` (tried to add this via `babelrc`) doesn't add `/*#__PURE__*/` to `React.memo` and `React.lazy`.

But If I add `@babel/plugin-transform-react-pure-annotations` to babel config, it works:

![image](https://user-images.githubusercontent.com/206567/98344439-4bf21580-2024-11eb-9718-8365cc5d95de.png)
<img width="1227" alt="Xnip2020-11-06_11-27-00" src="https://user-images.githubusercontent.com/206567/98344372-367ceb80-2024-11eb-8d34-ebc1aa50fb37.png">

**Comment by omgovich** [comment]
As far as I understand `@babel/preset-react` has to add `@babel/plugin-transform-react-pure-annotations` if `pure` option isn't `false`, but it doesn't work for some reason.

![image](https://user-images.githubusercontent.com/206567/98345490-cb341900-2025-11eb-9da6-f373221cad76.png)

**Comment by omgovich** [comment]
I found it:
`microbundle` enables `@babel/preset-react` only if we pass custom `--jsxImportSource` (see screenshot above).
But I don't have one on my CLI command.

**Comment by omgovich** [comment]
I'm not that it's the correct behavior. I mean shouldn't it use React setup if no `jsxImportSource` option present?

**Comment by omgovich** [comment]
So there are two things to solve:
1. Keeping `/*#__PURE__*/` after compression.
2. Enabling `@babel/preset-react` for React apps.

**Comment by omgovich** [comment]
Terser preserves PURE comments since 4.6.3:
https://github.com/terser/terser/commit/35b17232a24867ff3e788a667ebb0f1e8fbf70b4

![image](https://user-images.githubusercontent.com/206567/98348024-43e8a480-2029-11eb-8959-c285f699ea8c.png)

**Comment by omgovich** [comment]
I assume the rollup plugin you use doesn't support that:
![image](https://user-images.githubusercontent.com/206567/98348329-a5a90e80-2029-11eb-8b14-09daf78b6245.png)

**Comment by omgovich** [comment]
Since 4.6.3 Terser has `preserve_annotations` options (which is `false` by default). It should de all the magic.
https://github.com/terser/terser#format-options

**Comment by omgovich** [comment]
Next versions of `rollup-plugin-terser` require `rollup` v2, so probably that's not so easy to fix 😞

**Comment by developit** [comment]
There's a PR open that updates all of our dependencies. In Terser 4, the option is `output.preserveComments`.

**Comment by omgovich** [comment]
Hi! What about `@babel/preset-react`? What is the preferable way to use it with React?

**Comment by developit** [comment]
This should all be fixed as of #738.
