### ISSUE TITLE
Receiving "Failed to resolve module specifier" while loading bundled file via CDN

### ISSUE THREAD

**Issue by yaron14** [developit/microbundle#737]
I'm serving a cdn and I thought I'd use microbundle to bundle all the app components.
The issue is that after the build command is passed successfully I tried to load the bundled file via a cdn and received the following error: 
`Uncaught TypeError: Failed to resolve module specifier "haunted". Relative references must start with either "/", "./", or "../".`

It happens with every dependency I install and try to use.

Any ideas?

**Comment by marvinhagemeister** [comment]
By default microbundle won't inline `dependencies` or `peerDependencies`. It sounds like you're looking for a way to disable that and force it to bundle every dependency. You can do that by passing `--external none`.

For a full list of available CLI-flags, check out [the readme](https://github.com/developit/microbundle#all-cli-options-).

**Comment by yaron14** [comment]
Yep. It's working!
But the bundle size is very big (and I'm using just a single dependency). Is there any thing to do to reduce the size?

**Comment by developit** [comment]
If you want to leave dependencies as external while serving from a CDN, you'll need to convert the bare specifiers:

```js
import foo from 'haunted';  // syntax error

import foo from '/libs/haunted.js'; // valid
```

Microbundle doesn't provide a way to do this because it's not possible to determine what the URL for a module should be. It may be possible to configure them on a per-module basis by specifying URLs like `microbundle --alias haunted=/libs/haunted.js` (not sure).

**Comment by yaron14** [comment]
So, If I understand you correctly - I need to write the full path to the index (?) of the library in the import statement?
Or do it in the script in package.json with the alias flag?

**Comment by developit** [comment]
@yaron14 it depends whether you're using a CDN that transforms imports. Unpkg does this, for example - the URL below is a file that originally contained `import { h } from "preact"`, but the CDN transforms it to `import { h } from "/preact@10.5.4"` which is a valid specifier:
https://unpkg.com/htm@3.0.4/preact/index.mjs?module

Unfortunately this just isn't something any bundler can solve - ES Modules does not define how to load `"haunted"`, it's something each runtime (Node.js, Rollup, etc) decides for itself.
