### ISSUE TITLE
Aliasing module import

### ISSUE THREAD

**Issue by s-chillo** [developit/microbundle#742]
Hi all,

Is there a way to override webpack alias.

I'ld like to turn 
```
import React from 'react'   
import { someConstant } from '../../../config/constants'    
import MyComponent from '../../../../components/MyComponent'    
import { myActionCreator } from '../../../../ducks/someReducer' 
```
into 

```
import React from 'react'  
import { someConstant } from '@config/constants'  
import MyComponent from '@components/MyComponent'  
import { useHook } from '@hooks/useHook' 
```
thanks

**Comment by wardpeet** [comment]
you can use the `--alias` flag 

check 
https://github.com/developit/microbundle/blob/12668b993906a0267c53c3601ce89d1c0ddfbc27/test/fixtures/alias-external/package.json#L4

https://github.com/developit/microbundle/blob/12668b993906a0267c53c3601ce89d1c0ddfbc27/test/fixtures/alias/package.json#L4

So you're looking for something like this
```
microbundle --alias @config/constants=./src/config/constants
```

**Comment by developit** [comment]
Good summary @wardpeet. FWIW I'd strongly recommend _against_ using aliases like this, since they make code analysis and bundling tools have to work a lot harder. If you're just wanting to reduce typing, you could use a single re-export file to achieve far more compact imports:


```js
// all.js
export * from './config/constants'    
export { default as MyComponent } from './components/MyComponent'    
export * from './ducks/someReducer'
```

```js
// everywhere else
import { someConstant, MyComponent, useHook } from '../../all'
```

**Comment by imtheaman** [comment]
@developit  aliases are used in modern development and i think it makes code more readable. that approach of reexporting is definitely we all are using. but picture this instead of finding what's the relative path of enums directory from the current directory, ya'd have to shift your attention, whereas in case of aliases we'd simply do `import {XEnum} from '@enums'` without attention shift.
