### ISSUE TITLE
Babel error when trying to parse Typescript public variable

### ISSUE THREAD

**Issue by miltoncandelero** [developit/microbundle#743]
Babel says that the word after `public` is an unexpected token.
This is the simplest setup ever, the index.ts is a single class with a public variable.

![image](https://user-images.githubusercontent.com/15253010/96888079-9f2c6b80-145b-11eb-9469-7d8095fe69bb.png)

I attach the reproduction project
[microtest.zip](https://github.com/developit/microbundle/files/5423547/microtest.zip)

am I doing something wrong?

**Comment by developit** [comment]
You need to enable the class properties transform:

1. Install: `npm i @babel/plugin-proposal-class-properties`

2. Add a `.babelrc` (or your preferred config file):

```json
{
  "plugins": [
    ["@babel/plugin-proposal-class-properties", {
      "loose": true
    }]
  ]
}
```

**Comment by developit** [comment]
(fwiw I guess we could make this a default... might be a good idea)

**Comment by miltoncandelero** [comment]
@developit sorry to bother you again, I added the babelrc file and installed the dependency but nothing changed.
maybe I need to add something to the command line for microbundle to actually try to use my babelrc file?

**Comment by miltoncandelero** [comment]
WOW, crazy update:
my project folder is actually a symlink. I copied the test project folder directly to the root of my drive and tried again and worked. No babel required!

I've got no idea why this is happening but it is super crazy!

**Comment by developit** [comment]
Strange! How'd you create the project to end up with that?

**Comment by miltoncandelero** [comment]
See the screenshot, it says I am running it from a folder in my documents but then it says that the problem is a folder in another drive.
I have a symlink folder to my project folder in my documents. doing this also breaks rollup and many other libs :P
