### ISSUE TITLE
package.json `babel.presets` not working...

### ISSUE THREAD

**Issue by mikestopcontinues** [developit/microbundle#745]
I use a shared babel-preset across projects, which I reference from a third party repo. It typically works in package.json as:

```json
{
  "babel": {
    "presets": [
      "module:@namespace/babel-preset"
    ]
  },
}
```

However, microbundle seems to be silently ignoring it. I get an issue using the pipeline operator. In order for it to detect that plugin, I need to reference it explicitly. But I can't see how I can configure plugins in `package.json` but not presets unless microbundle is doing something strange under the hood:

```json
{
  "babel": {
    "presets": [
      "module:@sitearcade/babel-preset"
    ],
    "plugins": [
      ["@babel/plugin-proposal-pipeline-operator", {"proposal": "smart"}]
    ]
  },
}
```

I should add, when running jest (with babel-jest), my preset gets picked up fine.

Any idea what's going on here?

**Comment by developit** [comment]
What's the reason for using the `module:` prefix in your preset name?

**Comment by mikestopcontinues** [comment]
Because it's got a non-standard name (e.g. not `babel-preset-NAME`). I tried removing it, but it didn't change anything regarding the bug. It might not still be required as I can't find a docs reference (though here's an [issue](https://github.com/babel/babel/issues/8236) referencing the practice).

**Comment by mikestopcontinues** [comment]
Hey, any advice on this?

**Comment by developit** [comment]
Sorry about the delay - are you able to give a bit more information about your project's file structure? I'm curious if this is a package.json in the working directory, or if microbundle is being executed from another package.json (since it seems like you're in a monorepo). We don't crawl for Babel presets at all, they are only respected if they are defined in the working directory.

**Comment by mikestopcontinues** [comment]
Hey, I'm not in a monorepo. I've actually been migrating out of one. Regarding the babel preset, I use it across a handful of projects without a problem, sometimes in `babel.config.js` instead. It's [here](https://github.com/sitearcade/babel-preset), if you want to take a look. Here's the package.json for only of my microbundle repos. All of them have the same issue:

```json
{
  "name": "@sitearcade/request",
  "sideEffects": false,
  "source": "src/index.js",
  "main": "./dist/index.js",
  "jsnext:main": "./dist/index.modern.js",
  "module": "./dist/index.module.js",
  "syntax": {
    "esmodules": "./dist/index.modern.js"
  },
  "exports": {
    ".": {
      "browser": "./dist/index.module.js",
      "import": "./dist/index.module.js",
      "require": "./dist/index.js"
    }
  },
  "files": [
    "dist"
  ],
  "scripts": {
    "start": "microbundle watch --no-compress -f cjs,esm,modern",
    "build": "microbundle --no-compress -f cjs,esm,modern"
  },
  "dependencies": {},
  "devDependencies": {},
  "engines": {
    "node": ">=10"
  },
  "babel": {
    "presets": [
      "module:@sitearcade/babel-preset"
    ]
  }
}
```

**Comment by developit** [comment]
I don't see anything in that package.json that would cause Microbundle to ignore the babel config. Any chance you're on an older version of Microbundle?

**Comment by mikestopcontinues** [comment]
I finally got around to testing this again 0.13, and it works. I don't know what was going on before, but thanks for the help!
