### ISSUE TITLE
.d.ts files produced for files not explicitly imported

### ISSUE THREAD

**Issue by PascalPixel** [developit/microbundle#748]
Thanks for making microbundle, it saves us a lot of time!

We have an icon library generated with svgr, and we only import the icons we need in the entrypoint, as there are thousands of icons in total and it blows up bundle size.

The `--typescript` option however exports `.d.ts` type files for all the icons, even those not imported in the script. 

Aside from making a bash removal script, is this the intended behavior?

**Comment by developit** [comment]
@PascalPixel are you able to give an example of your Microbundle build command and the entry files? The d.ts creation is controlled by tsconfig, but I'm not 100% sure from your report whether you want the files at all, or just fewer of them.

**Comment by PascalPixel** [comment]
You're absolutely right @developit, I had to exclude the relevant folders and files in tsconfig! 💕
