### ISSUE TITLE
exclude storybook stories from build

### ISSUE THREAD

**Issue by schamane** [developit/microbundle#751]
Hi,
i am very new to microbundle, but maybe there is some way to exclude storebook stories from build ?

Thanks..

**Comment by marvinhagemeister** [comment]
Microbundle will build whatever you tell it to in your `package.json` file. The `main` field serves as the main entry file and microbundle will follow all import paths from there. If somehow you're stories show up in the bundle, than that is a strong indicator that you accidentally import them somewhere in your code.

Check out the [configuration section](https://github.com/developit/microbundle#-usage--configuration-) in the README for more information.
