### ISSUE TITLE
Building Modular Libraries - with sub direcotories

### ISSUE THREAD

**Issue by alfredosalzillo** [developit/microbundle#752]
Add a way to build modular libraries with multiple subs directories.

**For example:**
Multiple imports Right Now-
```javascript
import { A, B } from 'package';
```

With Modular Imports -
```javascript
import A from 'package/A/A'; 
import B from 'package/B/B';
```

as used in some react libraries like [material-ui](https://github.com/mui-org/material-ui).

**Comment by rschristian** [comment]
If I am understanding correct, you can already do this, though it has less to do with Microbundle and more to do with your package structure and setup. 

A good reference might be the [Preact repo, found here](https://github.com/preactjs/preact). Preact has numerous exports in the style you bring up, `preact/compat`, `preact/debug`, `preact/hooks`, etc. The way it does this is with the [`exports` field in the package file here](https://github.com/preactjs/preact/blob/f64f81193ed7ac51f471cb8cf8dcdf52d2bd124f/package.json#L19-L24). You can use this field to point at your output from Microbundle.

**Comment by developit** [comment]
Iam going to close this out since we have a duplicate we're using to track this feature in #726.
