### ISSUE TITLE
Less support

### ISSUE THREAD

**Issue by flavaud-traceone** [developit/microbundle#753]
Hello,

I discovered microbundle a few days ago, and I already love it, thanks!

I have few questions regarding Less and styling support. I'm building a UI kit over [Ant Design](https://ant.design/), and they required the enable inline JavaScript. I tried to have a look at your project, but I couldn't find where it could be activated. Would that make sense for you?

Moreover, I notice that microbundle does not support `~` when importing Less files from dependencies. Could it be considered?

I understand that microbundle is made for _tiny modules_, I'd understand if that's out of scope. If not, I'd be happy to help!

**Comment by developit** [comment]
Hmm - I'm not sure I understand what you mean by inline JavaScript in this context.

For `~`, I don't think Microbundle currently processes Less files at all, it's likely just treating them as CSS. Tbh you're right in thinking this is probably out of scope here 😬

**Comment by flavaud-traceone** [comment]
I'm talking about [that](http://lesscss.org/usage/#less-options-strict-units) . But it seems to be deprecated, so I guess it's more about Ant Design to be updated so they don't use this feature anymore 😁

About `~` support, it would be the same with CSS or Scss or Less, it's meant to target a style file within node modules. The question is about supporting styled dependencies. I'm just thinking about a work around, they could be imported from a JavaScript file, I haven't tried it. I'll have a look.

Thanks for the quick reply!

**Comment by rschristian** [comment]
> About `~` support, it would be the same with CSS or Scss or Less, it's meant to target a style file within node modules. The question is about supporting styled dependencies. I'm just thinking about a work around, they could be imported from a JavaScript file, I haven't tried it. I'll have a look.

The tilde (`~`) is actually [from Webpack's `css-loader`](https://webpack.js.org/loaders/css-loader/#import). Some other tools may implement this too, not entirely sure about the landscape there. 

I don't believe Microbundle will resolve imports already as-is (at least it won't from my tests) so I think you'll need a CSS-specific tool like PostCSS which would be better for this sort of thing anyways, given the abundance of plugins that it has.

**Comment by developit** [comment]
We're considering removing support for CSS from Microbundle, so adding an additional preprocessor like Less would be a hard sell. Microbundle isn't the right tool for bundling applications - it's for npm modules, which currently cannot reference CSS in any standardized or broadly-accepted way.

For applications though, definitely check out [WMR](https://github.com/preactjs/wmr) - it's built by this same team of folks, and infinitely better suited to delivering awesome applications. It has a proper development server too! And support for CSS, and Rollup plugins...
