### ISSUE TITLE
Error: 'useState' is not exported by node_modules/react/index.js

### ISSUE THREAD

**Issue by yinguangyao** [developit/microbundle#758]
when I use `import { useState } from 'react'`, this error occurred.

command: microbundle --external none
version: 0.11.0

**Comment by rschristian** [comment]
I can't reproduce. Can you provide a repo or maybe a sandbox?

**Comment by developit** [comment]
Indeed. FWIW, React does not export useState, so this error is correct. Most react usage relies on incorrect transpiled output for ES Modules.
