### ISSUE TITLE
0.13.0 overwrites my types/index.d.ts

### ISSUE THREAD

**Issue by StarpTech** [developit/microbundle#771]
Hi after upgrading to 0.13.0 my custom TS type definition file is overwritten.

Command: `microbundle --no-sourcemap --no-compress --jsx React.createElement`
Repository: https://github.com/StarpTech/next-localization

Previous:

```ts
interface I18n<T> {
    /** Get/Set the language key */
    locale(lang?: string): string;
    /** Define or extend the language table */
    set(lang: string, table: T): void;
    /** Get the table of translations for a language */
    table(lang: string): T | void;
    /** Retrieve a translation segment for the current language */
    t<X extends Record<string, any> | any[]>(
        key: string | (string | number)[],
        params?: X,
        lang?: string
    ): string;
    withPlural<T>(
        pluralOptions?: object
    ): <X extends Record<string, any> | any[]>(
        key: string | (string | number)[],
        params?: X,
        lang?: string
    ) => string;
}

export function useI18n<T>(): I18n<T>;
export function I18n<T>(table?: T): I18n<T>;
export function I18nProvider<T extends object>(props: ProviderProps<T>): React.ReactElement;

interface ProviderProps<T> {
    lngDict?: T;
    locale: string;
    i18nInstance?: I18n<T>;
    children: JSX.Element;
}
interface II18nProvider<T> extends React.FC<ProviderProps<T>> {}

```

After

```ts
export { default as useI18n } from "./hooks/use-i18n";
export { I18n, default as I18nProvider } from "./i18n";
```

**Comment by developit** [comment]
Can you paste the contents of your package.json? This would normally be caused by the package.json "types" field pointing to your source directory instead of the output directory.

**Comment by StarpTech** [comment]
https://github.com/StarpTech/next-localization/blob/master/package.json

**Comment by developit** [comment]
Can you try passing `--no-generate-types` to microbundle?

**Comment by andrewiggins** [comment]
I think we might be missing the definition of the `generate-types` flag in [prog.js](https://github.com/developit/microbundle/blob/master/src/prog.js)? Is that required for it be parsed as a command line flag?

**Comment by developit** [comment]
I'm not 100% sure if we disallow extra arguments (I think we do?), otherwise yeah it'd need to be added.

**Comment by StarpTech** [comment]
> Can you try passing --no-generate-types to microbundle?

Has no effect.

**Comment by donmccurdy** [comment]
I've got the same issue here — my source code is JavaScript, not TypeScript, and the types are hand-maintained, but microbundle is overwriting them. Using `--no-generate-types` has no effect. Here's my package.json:

<details>
<summary>package.json</summary>

```
{
  "name": "expression-eval",
  "version": "4.0.0",
  "description": "JavaScript expression parsing and evaluation.",
  "source": "index.js",
  "main": "dist/expression-eval.js",
  "module": "dist/expression-eval.module.js",
  "unpkg": "dist/expression-eval.umd.js",
  "types": "index.d.ts",
  "repository": {
    "type": "git",
    "url": "https://github.com/donmccurdy/expression-eval.git"
  },
  "scripts": {
    "dev": "microbundle watch",
    "build": "microbundle --no-generate-types",
    "test": "node test.js",
    "lint": "cp test.js index.test-d.ts && npx tsd; rm index.test-d.ts",
    "preversion": "npm run build && npm run lint && npm run test",
    "postversion": "git push && git push --tags && npm publish"
  },
  "keywords": [
    "expression",
    "eval",
    "evaluation",
    "parser",
    "ast",
    "abstract",
    "syntax",
    "tree",
    "math"
  ],
  "author": "Don McCurdy <dm@donmccurdy.com>",
  "license": "MIT",
  "dependencies": {
    "jsep": "^0.3.0"
  },
  "devDependencies": {
    "microbundle": "^0.13.0"
  },
  "files": [
    "dist/",
    "index.js",
    "index.d.ts",
    "README.md",
    "LICENSE",
    "package.json",
    "package-lock.json"
  ]
}

```

</details>

**Comment by ricokahler** [comment]
As an alternative to `--no-generate-types` would `declaration: false` in the `tsconfig.json` be a good alternative?

It seems to do the job but I get some warnings

```
rpt2: options error TS5069: Option 'declarationDir' cannot be specified without specifying option 'declaration' or option 'composite'.
```

**Comment by nicholasio** [comment]
I'm having the same issue, "declaration": false did the trick but I'm also getting those warning.

**Comment by rdmurphy** [comment]
I'm also getting this too. My inputs are all `.js` files and I don't have `tsconfig.json` file, just a `"types": "types/index.d.ts"` in my `package.json` that I've manually written that `microbundle` keeps overwriting for reasons I don't understand. 😬

**Comment by developit** [comment]
Would love a PR if anyone has an idea of what the fix would be.

**Comment by rdmurphy** [comment]
It's really tricky — I think it's the combination of this check for `pkg.types`:

https://github.com/developit/microbundle/blob/edcd777cfaedfdb436c62b5dcb3cff6291268e4c/src/index.js#L369

Which injects the TypeScript plugin:

https://github.com/developit/microbundle/blob/edcd777cfaedfdb436c62b5dcb3cff6291268e4c/src/index.js#L483-L484

In my use case I'd _not_ want the existence of `pkg.types` to activate that plugin, but I **do** get why it's that way. 🤔 If there was a way to prevent it then no one would have to attempt to trick TypeScript to do the right thing (which is often quite fraught in my experience).

**Comment by rdmurphy** [comment]
It'll take me a moment to check myself but it's possible that #830 fixed this, if anyone else wants to give `0.13.1` a shot.

**Comment by ehaynes99** [comment]
Looks like the option to disable is actually `--no-generateTypes` rather than `--no-generate-types`. The inconsistency of the casing of options seems likely to lead to confusion. Perhaps it's worth considering converting them all internally, which would allow using dot notation everywhere, but allow for either casing to preserve backwards compatibility.

```javascript
opts = Object.keys(opts).reduce((result, name) => {
	const camelized = name.replace(/-([a-z])/g, g => g[1].toUpperCase());
	result[camelized] = opts[name];
	return result;
}, {});
```

**Comment by rschristian** [comment]
This is working as intended, though it does have a rough edge or two: if your entry is written in TS (`.ts` or `.tsx` ext) OR you have `"types"` or `"typings"` in your `package.json`, Microbundle will generate types for you. If this is not the behavior you want, you can use `--no-generateTypes` to disable type generation. It was misquoted above as `--no-generate-types`.

We do have a couple of inconsistencies in the flags to work out, but we don't need this issue open to track it.
