### ISSUE TITLE
How to bundle other node_modules code in the dist file?

### ISSUE THREAD

**Issue by zhanyuzhang** [developit/microbundle#772]
for example , I import react lib in my demo:
```
import react from 'react';
console.log(react);
```

after I build the demo , there are no react's code in the dist files.  If I want to include all react code in the dist code, what should I do ?

**Comment by developit** [comment]
Unless you're bundling an entire application, there are very few cases where you'd want to bundle react into your library. 

If you're sure this is what you want to do, there is a complete guide here:
https://github.com/developit/microbundle/wiki/How-Microbundle-decides-which-dependencies-to-bundle
