### ISSUE TITLE
preact not getting bundled?

### ISSUE THREAD

**Issue by Pomax** [developit/microbundle#774]
I'm running the following command:

```
> microbundle -i ./src/react-app/ui.js -o ./public/preact-ui.js --format=esm
```

with the following test code from the Preact website:

```js
import { h, render } from 'preact';

render((
    <div id="foo">
        <span>Hello, world!</span>
        <button onClick={ e => alert("hi!") }>Click Me</button>
    </div>
), document.body);
```

but the resulting bundle doesn't actually contain preact and tries to import in a way that doesn't work on the web:

```js
import{render as o,h as l}from"preact";o(l("div",{id:"foo"},l("span",null,"Hello, world!"),l("button",{onClick:function(o){return alert("hi!")}},"Click Me")),document.body);
```

this would have to at the very least be `import{render as o,h as l}from"preact.js"` to work on the web (also, it's funny that `h` gets renamed to `l`, given that `h` is already a single letter) but really this shouldn't even be an import but a bundle inclusion of the (tiny) preact code. Not very micro"bundle" without bundling =)

**Comment by developit** [comment]
Hiya - this is because Microbundle uses your package.json to infer whether dependencies should be bundled or not. Bundling Preact into npm dependencies breaks, since folks end up with 2+ copies of Preact and that module is a singleton.

For your case, it sounds like you want the `--external none` option:

```js
microbundle -i ./src/react-app/ui.js -o ./public/preact-ui.js --format=esm --external none
```

**Comment by Pomax** [comment]
aah, perfect! thank you
