### ISSUE TITLE
SASS compiled prematurely

### ISSUE THREAD

**Issue by heyymarco** [developit/microbundle#787]
I created my react liblary like this:

```sass
@use "~@mylib/index.scss";

$color: blue;
.hello {
    .world {
        color: #{$color};
        background: red;
    }
}
```

after running npm run build, the compiled file is like this:
```
@use "~@mylib/index.scss";
._XD_im ._RvYsd {
  color: blue;
  background: red; }
```

It seem the bundle didn't recognize new sass syntax like @use, @forward (but @import recognized well).

Is there any configuration to compile sass with a new sass compiler?

**Comment by developit** [comment]
Hi @heyymarco - Microbundle doesn't actually support SASS. Any SASS syntax that happens to work is just because it's a superset of what PostCSS supports, which is what Microbundle uses.

**Comment by developit** [comment]
I'm going to close this out since we're actively moving towards reducing our CSS support.

**Comment by MartinDawson** [comment]
This library is so annoying. At first glance it seems great but then you end up not supporting scss, not supporting assets, not supporting web workers properly etc etc which makes it unbelievably useless and frustrating and not practical at all.

This library literally needs warnings at the top of it's readme as I now have to convert our library away from this.

**Comment by arielvieira** [comment]
@MartinDawson Do you mind sharing what are you using instead?

**Comment by MartinDawson** [comment]
@arielvieira Use parcel, it's way better.
