### ISSUE TITLE
css-modules--null doesn't work correctly

### ISSUE THREAD

**Issue by helsonxiao** [developit/microbundle#788]
Hi there! I'm using `microbundle-crl@0.13.11` from `create-react-library` template. Everything is OK except css files like `index.less` are bundled as css modules.

I've checked README.md and it said when `css-modules` is null, css modules only effect on `.module.css` files. Then I clone this repo, run all jest tests and found no errors.

I guess the problem is fixed in the master branch but the version is somehow `0.13.0` which can't be found on npm registry 😅. I have to downgrade `microbundle-crl` to `0.13.8` because I don't know if I can contribute now.

**Comment by developit** [comment]
Hi there! `microbundle-crl` is actually a fork, we don't have a way to update it from here. I think you could just swap to the official version of Microbundle: `npm rm microbundle-crl && npm i -D microbundle`.

**Comment by developit** [comment]
(closing - feel free to re-open if that doesn't work)

**Comment by helsonxiao** [comment]
Thanks! Then `microbundle-crl` should correct their homepage [here](https://www.npmjs.com/package/microbundle-crl).
