### ISSUE TITLE
Building for node and standalone bundle to be included in web app script tag

### ISSUE THREAD

**Issue by aratcliffe** [developit/microbundle#790]
Hi, I have a library I'm building that will either be required as a dependency in a node project or included as a standalone bundle by script tag in a web app. Is the best way to handle this to use 2 separate build targets as shown in my config below?

```
{
  "name": "mylib",
  "version": "1.0.0",
  "main": "dist/mylib.js",
  "umd:main": "dist/mylib.umd.js",
  "scripts": {
    "build:web": "microbundle -f umd --external none",
    "build:node": "microbundle -f cjs"
  },
  "license": "MIT",
  "dependencies": {
    "cross-fetch": "^3.0.6"
  },
  "devDependencies": {
    "microbundle": "^0.13.0"
  }
}
```

**Comment by developit** [comment]
Hi @aratcliffe! You're exactly right, that is how you'd do this in Microbundle. The reason two builds are required is because the `--external` option is global, and you likely don't want to inline all dependencies into the Node version.

Cheers!
