### ISSUE TITLE
Example for using —define flag

### ISSUE THREAD

**Issue by sammdec** [developit/microbundle#791]
It’s a little unclear how to use the —define flag. Particularly when it comes to adding the constant in the actual code. Is it exposed through process.env or is there some other way I’m missing?

**Comment by marvinhagemeister** [comment]
Check out the [defining constants section in the README](https://github.com/developit/microbundle#defining-build-time-constants). It's essentially a simple string replacement and they are exposed on the global scope by default.

```bash
microbundle --define FOO=123,process.env.NODE="development"
```

```js
console.log(FOO) // Logs 123
console.log(process.env.NODE) // Logs "development"
```

**Comment by sammdec** [comment]
Won’t FOO in your example be flagged as undefined?

**Comment by marvinhagemeister** [comment]
TS will flag any global variable it doesn't know about as `undefined` unless you [tell TS about it](https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html#global-variables).
