### ISSUE TITLE
Node-Standalone: Packaging everything into a single file?

### ISSUE THREAD

**Issue by ArminEberle** [developit/microbundle#792]
Hi there,

we do have a monorepo using the yarn workspace feature. 
This has the effect that in our own packages, most installed node_modules are 'hoisted' to the repository root.

In our application, we are running node also on the server side as the backend.
So after our 'node build' (compiling typescript etc.), we package the server side node packages into docker images.
And this is where our problems start:
1. Each server side package needs the node_modules folder (containing also file links to our own packages) from the package root in order to be node-runnable. Otherwise the referenced modules from the packages there would be missing.
2. We can of course put the whole repository into each docker-image, but that extremely increases the container-size (1G vs. estimated 'really required' 30MB per docker image). This is because the repository root node_modules folder has all required modules of all our monorepo packages.

At the moment, we're handling this by asking dependency-tree to for all required dependencies of each of our packages and copy the required dependency-packages to the target folders. However this fails in some circumstances as dependency-tree is not catching everything - and it is slow as well.

I've been trying with webpack to achieve a node-standalone build that results in a single index.js file that includes also _all_ recursively required modules in it. However, there is strange behaviour in some libraries we're using because of browser-detection mechanisms that check if there is a __webpack_require__ global variable available for example.

So I'm wondering if microbundle has a switch that effects that from my source, a single, all-dependency-containing target file is created?

I tried with 
```
  "source": "src/ts/index.ts",
  "main": "dist/index.js",
```

in my package.json and `microbundle --target node` on the command line, but this seems to create an index.js file that still requires files from the node_modules folder(s).

Thanks in advance for any help or hint,

Armin

**Comment by marvinhagemeister** [comment]
Sounds like you're looking for the `--external` flag as documented in the [README](https://github.com/developit/microbundle#all-cli-options-):

```bash
--external         Specify external dependencies, or 'none' (default peerDependencies and dependencies in package.json)
```

Usage:

```bash
microbundle --external none
```
