### ISSUE TITLE
Remove PostCSS inject option

### ISSUE THREAD

**Issue by faessler** [developit/microbundle#796]
First of all thanks for developing and maintaining this package, it's very neat! 🤩

I noticed that `inject` is set to `false` and was wondering why?
https://github.com/developit/microbundle/blob/eb5cfd91ce92aa260c74e267ca1285fd0a24e3e3/src/index.js#L447

Is there a use case where you don't want to inject the styles when you're building with `--css inline`?
If there is no real use case I would propose to remove this option and let the default behaviour of PostCSS do it's work.
| extract | inject |
| --- | --- |
| `false` | will be  `true` |
| `true` | will be `false` |

Source: https://github.com/egoist/rollup-plugin-postcss#inject

**Comment by developit** [comment]
I believe we have this disabled because it's quite limited: there are many ways to inject CSS (CSSOM, Constructible Stylesheet, Shadow DOM, inline styles, etc), and there are many cases where the timing of when CSS gets injected is more specific than "when the module is imported".

I wonder if we could solve this by showing a recipe for simple css injection in the docs instead?

**Comment by faessler** [comment]
Agreed, I started using styled-components for now.

Would it maybe make sense to provide this behaviour as an opt-in option? For cases where injection "when the module is imported" is good enough, provided there are no further limitations...
For example like this: `--css inline-inject`

The "recipe for simple css injection in the docs" idea sounds great. I think this could help a lot of people and would probably resolve this issue.

**Comment by developit** [comment]
I realized after posting - we can't actually do "inject" because we don't have a valid URL for the CSS file. Only inline could work, and I think we can do a nice little example that would offer folks more control.

**Comment by faessler** [comment]
Yes, "inject" would only work with "inline" => [Inject CSS into `<head>`, it's always `false` when `extract: true`](https://github.com/egoist/rollup-plugin-postcss#inject)

Alright then, looking forward for the recipe/examples. 😁 👍
hmu if I can help with anything.
