### ISSUE TITLE
[Transpiling] Rest parameters doesn't work with non-arrow function closures

### ISSUE THREAD

**Issue by gdorsi** [developit/microbundle#797]
Hello there!

I've encountered a bug with the transpiling of the rest parameters.

Pratically the transpiler with something like this:
```js
export function brokenArgsRest(fn, ...args) {
  return function () {
    fn(...args);
  };
}
```

Will treat the arguments object in the wrong way:
```js
function brokenArgsRest(fn) {
  return function () {
    fn.apply(void 0, [].slice.call(arguments, 1));
  };
}
```

I've created a minimal repro here --> https://github.com/gdorsi/microbundle-args-rest-issue

**Comment by developit** [comment]
Ahhh good catch. I'll need to update the transform to use an intermediary variable to hold args.
