### ISSUE TITLE
Throws an error if no name is set in package.json

### ISSUE THREAD

**Issue by hph** [developit/microbundle#8]
The title probably says everything, but my problem was that I tried microbundle in a local package without a name field in the package.json file. This currently throws an internal error when `replace` is called on `undefined` (`pkg.name`).

I'd be happy to open a PR to fix this if you'd like, but I wasn't sure how you'd want to handle it (warn and exit? something else?).

Anyway, thanks for building this, it looks like a very useful tool!

**Comment by developit** [comment]
I just ran into this so I fixed it!

**Comment by hph** [comment]
Nice, thanks!
