### ISSUE TITLE
Error compiling TypeScript  4.1 Template Literals Type

### ISSUE THREAD

**Issue by yaldram** [developit/microbundle#804]
### Issue
Hello Community, I am using `microbundle-crl` for compiling my React TypeScript Project, compiling the code fails when I am using TypeScript Template Types like ```export type SpaceThemeProps = `$${keyof typeof theme['space']}` | (string & {})```

### Error
I get the following error when  I run  microbundle-crl --no-compress --format modern,cjs - 
`semantic error TS2305: Module '"../../../../stitches.config"' has no exported member 'SpaceThemeProps'.`

### WorkArounds
I tried adding the following, in my package.json but it did not work - 
```javascript
"resolutions": {
    "**/typescript": "^4.1.5",
    "**/@typescript-eslint/eslint-plugin": "^4.15.1",
    "**/@typescript-eslint/parser": "^4.15.1"
  }
```

### Files
My tsconfig.json is as follows : - 
```javascript
{
  "compilerOptions": {
    "outDir": "dist",
    "module": "esnext",
    "lib": ["dom", "esnext"],
    "moduleResolution": "node",
    "jsx": "react",
    "sourceMap": true,
    "declaration": true,
    "esModuleInterop": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "allowSyntheticDefaultImports": true,
    "target": "es5",
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true
  },
  "include": ["src"],
  "exclude": ["node_modules", "dist", "example", "**/*.stories.tsx"]
}

```

**Comment by marvinhagemeister** [comment]
`microbundle-crl` is a different project that someone forked from microbundle a while back. It's not maintained or supported by us. Better to reach out to the maintainers of `microbundle-ctl` directly.
