### ISSUE TITLE
[Feature request] publishConfig overriding support

### ISSUE THREAD

**Issue by cometkim** [developit/microbundle#805]
Hi :wave: 

I recently replaced my own rollup configuration with a microbundle and it's much simpler and just works!

However, there is a part that is not supported in the config I used frequently
In the previous config, I was using this in the `package.json`.

```json
  "main": "./src/index.ts",
  "publishConfig": {
    "main": "./lib/index.js",
    "module": "./lib/index.mjs",
    "browser": "./lib/index.umd.js",
    "types": "./lib/index.d.ts",
    "access": "public"
  },
```

This pattern is helpful for monorepo tooling. For example, when I run all test suites for an entire package, this helps the test runner resolve monorepo dependency without an additional build step.

**Comment by developit** [comment]
I might be misunderstanding - how is this different than the existing package.json main/module/browser/unpkg fields we support?

**Comment by cometkim** [comment]
When using monorepo, with tools like TypeScript, Jest, and whatever else

```
core
lib -> core
```

Suppose I have a newly downloaded repository or run `git clean -fdx` to do a fresh install.

Then, TypeScript cannot resolve the `core` package when working on `lib` because the local dependency has not yet been built, and it also fails when running test.

Using the source file in the `main` field and overriding it in `publishConfig` can provide a smart separation of local development and publish environments, so can be useful for some monorepo configurations.

I've learned this pattern from https://github.com/yarnpkg/berry

**Comment by cometkim** [comment]
Obviously, this is optional. And I believe it will not break existing configs.

Can I make a patch for it?

**Comment by developit** [comment]
Sure, Seems reasonable.
