### ISSUE TITLE
Add @rollup/plugin-run plugin

### ISSUE THREAD

**Issue by CallMeLaNN** [developit/microbundle#812]
I wanted to use microbundle seems it quite suitable for modern node project.

Since the Rollup plugins is not configurable, I just [fork](https://github.com/CallMeLaNN/microbundle/tree/node) to add `@rollup/plugin-run`.

I wanted to serve the output together with `microbundle watch` because it is faster than `nodemon`. The plugin only activated on `options.watch` is true.

Would you mind to have the plugin here?

The only thing left is to make sure it only activated for node entry point or opt-in by switch.

**Comment by wardpeet** [comment]
Hey,

@rollup/plugin-run seems nice but you might need to pass some extra parameters to it if you have a special setup. For now we'll stick with nodemon. Thanks for asking!
