### ISSUE TITLE
Unable to get dependencies and styles bundled in single file

### ISSUE THREAD

**Issue by billdami** [developit/microbundle#817]
I'm attempting to have microbundle include all my dependencies (notably, `preact`, `classnames`) and all my styles (i use SASS-based CSS modules) included in a single output bundle, but I can't seem to get that happen no matter what build options I try. I've tried moving all my dependencies into `devDependencies` in package.json, using `--external none` and combinations of both.

Here is a link to the test repo in question (I've committed the `dist/` from one of my attempts, so its easier to see what my current output looks like):

https://github.com/billdami/preact-ts-widget

The build command I've been trying is:
```
microbundle build -o dist/bundle.js --no-pkg-main -f umd --external none --css inline --no-compress
```

**Comment by rschristian** [comment]
Might've been solved here: https://github.com/rschristian/preact-ts-widget/ ?

Let me know if you're still having issues, happy to continue to work through it with you.

**Comment by rschristian** [comment]
Closing as I believe should be solved in this thread: https://github.com/preactjs/preact-cli/issues/1258
