### ISSUE TITLE
Typescript debug and bundle size relation

### ISSUE THREAD

**Issue by eroldmrclk** [developit/microbundle#821]
I created a project with microbundle. 

My problem is that I want to debug typescript in the **dev** environment, but when my package size is **around 120kb**, I started to debug from the **index.js** file automatically. I was able to debug the typescript again when I dropped the bundle size by not exporting a few files. 

How can I solve this problem?

**Comment by developit** [comment]
Can you describe what the actual issue is? Are you debugging in Node? What about the 120kb matters here?

**Comment by eroldmrclk** [comment]
@developit 
I give an example when the bundle size is 90kb, I can debug typescript without any problem, but when the bundlesize is 120kb, I can only debug in the index.js file instead of the .ts extension files.

**Comment by developit** [comment]
Is this an issue with your debugger? Please provide the details I asked for.

**Comment by rschristian** [comment]
Closing due to no response.
