### ISSUE TITLE
Code will not build when using CSS Modules + TypeScript

### ISSUE THREAD

**Issue by nickrttn** [developit/microbundle#822]
# Summary

I'm trying to bundle a React component library. I'm using Typescript and CSS Modules. When I try to build (or watch for that matter), I receive the error:

```sh
(rpt2 plugin) Error: ..../project/src/component.tsx(1,20): semantic error TS2307: Cannot find module './component.module.css' or its corresponding type declarations.
```

I can reproduce this in a reduced test case: https://github.com/nickrttn/microbundle-ts-css-modules

With the types added in the test case as documented in #740 I would have expected this to build. I've also tried to add https://github.com/mrmckeb/typescript-plugin-css-modules instead, with the same results. Strangely, VS Code does pick up on both of these changes.

# Expected result

`yarn build` should work. I've taken the custom `tsconfig.json` and types from #740.

# Actual result

This error during building or watching:

```sh
(rpt2 plugin) Error: ..../project/src/component.tsx(1,20): semantic error TS2307: Cannot find module './component.module.css' or its corresponding type declarations.
```

**Comment by rschristian** [comment]
Your issue is with this line: https://github.com/nickrttn/microbundle-ts-css-modules/blob/232190ee2f4e9cf80c5ec60aae9d92fae70c821b/package.json#L10

The invalid path breaks things

**Comment by nickrttn** [comment]
Yep, that is a strange error in response to that typo. Just removing the key completely fixes it as well. 

I did expect not to have to add the types manually after the fix for #740 was merged, but that seems to be due to the ambient types not being included on npm?

**Comment by rschristian** [comment]
Yeah, I'll get that fixed.

**Comment by rschristian** [comment]
Just had #823 merged in, should ensure those types are accessible to end users.

As for the error message, I believe that's upstream in `rollup-plugin-typescript2`, though what you wrote would be an error when using `tsc` all the same. We extrapolate the declaration dir from your `types`, which in this case would be the project root. That seems to break `tsc`, which in turn, I'm guessing, throws off rpt2. Not entirely sure why TSC can't handle that, but it can't.

**Comment by rschristian** [comment]
Closing as the path is invalid in other environments, so this isn't a Microbundle issue.
