### ISSUE TITLE
Pattern for separate dev/prod CJS files?

### ISSUE THREAD

**Issue by markerikson** [developit/microbundle#824]
We've been using TSDX for Redux Toolkit, which currently generates 3 CommonJS files: `index.js`, `redux-toolkit.cjs.development.js`, and `redux-toolkit.cjs.production.js`.

The `index.js` file looks like:

```js
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./redux-toolkit.cjs.production.min.js')
} else {
  module.exports = require('./redux-toolkit.cjs.development.js')
}
```

In `package.json`, we've got `main: ./dist/index.js` pointing to that file.

I'm playing around with Microbundle for the first time, and it looks like it isn't really set up to do that kind of pattern.  So, questions:

- _Is_ there a way to get Microbundle to output both dev and prod CJS builds like that?
- Is that "build both, import the right one at runtime" approach even something we would want?

Curious for any info folks can provide on how to set things up the right way here.

**Comment by artalar** [comment]
Hi, I'm interested in this topic too.
As I understand we may modify a babel config by `babel.config.js` at the root of a package (and add `babel-plugin-dev-expression`), but I did not found how to generate separate builds with different suffixes.

Also, I don't get why the runtime check tests the NODE_ENV for 'production' if the user builds an app without passed NODE_ENV we will exports the development build which is not correct imho. It should looks like `NODE_ENV === 'dev' ? dev : prod`

**Comment by developit** [comment]
This is not supported in Microbundle because it only works in CommonJS and has a terrible default behavior of including both variants. Relying on magic Node globals in a browser context doesn't make sense.

**Comment by amannn** [comment]
> create two sets of bundles for development and production, and use aliases to import them

Does this mean the consumer of the library has to create an alias? I'm currently looking for a way for popular bundlers to pick up the right build automatically while providing an ESM build but I can't seem to find one.

So far I've been using the CJS way that @markerikson has mentioned above.

**Comment by rschristian** [comment]
> Does this mean the consumer of the library has to create an alias?

Yes, they would.
