### ISSUE TITLE
--sourcemap false is not working

### ISSUE THREAD

**Issue by AdrianMrn** [developit/microbundle#837]
The Readme mentions `--sourcemap` as a parameter, but setting it to `false` does nothing. `--no-sourcemap` does what I expect here.

I'll have a look at the source & submit a PR to change this when I have some time.

**Comment by rschristian** [comment]
Cheers, thanks for pointing this out!

**Comment by AdrianMrn** [comment]
Should have searched before posting this 🙈  thanks!

**Comment by rschristian** [comment]
Hey I even created a PR before realizing it had already been fixed 😅
