### ISSUE TITLE
Document usage of "-d" flag

### ISSUE THREAD

**Issue by pm0u** [developit/microbundle#861]
While running into some tree-shaking issues, I came across issue https://github.com/developit/microbundle/issues/457 which recommends using the `-d` flag to split output and use multiple input files.

I cannot find this flag/feature documented anywhere. How does this work and what is it's intended purpose?

**Comment by pm0u** [comment]
I see, it appears this is an alias of "--output" ? https://github.com/developit/microbundle/blob/master/src/prog.js#L92

if correct, feel free to close.. documentation would be nice though.

**Comment by rschristian** [comment]
Yep, that's all it is. Just kept around to ensure nothing breaks. 

Do you think a notice on this comment https://github.com/developit/microbundle/issues/457#issuecomment-516116065 that `-d` is just an alias would be helpful?

**Comment by pm0u** [comment]
@rschristian I think that wouldn't hurt, or including it in the main CLI documentation in the README (the first place I went to)

**Comment by rschristian** [comment]
I don't think we want to document aliases which (as far as I can tell) exist only for legacy purposes. 

I'll add a note to that comment, hopefully that might catch future issues.
