### ISSUE TITLE
File size much lower when using require vs import

### ISSUE THREAD

**Issue by alanaasmaa** [developit/microbundle#87]
Hello,

Im importin external npm package.
When im using `const parse = require('form-parse');` my file size is much lower than using `import parse from 'form-parse';`

```
require =>
Wrote 884 B: index.umd.js
Wrote 818 B: index.js
Wrote 821 B: index.m.js

import =>
Wrote 2.6 kB: index.js
Wrote 2.65 kB: index.umd.js
Wrote 2.6 kB: index.m.js
```

Im writing a module for babel that converts to browser script.

Why size is so different and wich one should i use ?

**Comment by olstenlarck** [comment]
Probably resolving of the external packages not works correctly. See your bundle to see if it actually has `form-parse` code in it.

I was thinking about while looking over the code before one week. Order of `commonjs` and `node-resolve` are not correct. Both plugins should be at the top of the list of plugins.

**Comment by alanaasmaa** [comment]
@olstenlarck Yes it is inside and its working in project where im using int. 

But the size does not change almost at all where im using my package. `788.59kb vs 789.23kb`

**Comment by olstenlarck** [comment]
Strange.. ;/

**Comment by developit** [comment]
Two copies of a library won't affect gzipped size much.

If you use `require()`, you're opting out of bundling of that package entirely. Microbundle only bundles ES Modules imports in source.

Is `form-parse` listed in your `package.json` under `"dependencies"`?  That's how microbundle knows whether to mark it as external (linked but not bundled) or inline it.

**Comment by alanaasmaa** [comment]
@developit yes it is in package.json

I have tried to read about this topic and difference between require and import but no glue till now.

**Comment by developit** [comment]
If you're looking to produce a single file that contains your whole library, the larger of the two outputs is the one you want.  If you switch to ES Modules, you can also exclude modules using `--exclude`.
