### ISSUE TITLE
Switch to @rollup/plugin-typescript from rollup-plugin-typescript2

### ISSUE THREAD

**Issue by pravi** [developit/microbundle#878]
Similar to https://github.com/weiran-zsd/tsdx/issues/2

**Comment by rschristian** [comment]
I'm going to close this out as it's not an actual issue.

There may be beneficial reasons to switch, I have no idea, but with the only provided justification being the following:

> as it is maintained by rollup community directly has better chance of long term maintenance.

...I don't see that as being particularly compelling. `rollup-plugin-typescript2` does (mostly) fills our needs and is still being actively maintained.
