### ISSUE TITLE
.cjs extension in `main` package.json field causes imported CSS file output to be overwritten

### ISSUE THREAD

**Issue by lokimckay** [developit/microbundle#883]
Using a `.cjs` extension in the `main` field of `package.json` (e.g. `"main": "./dist/foo.cjs"`) as per README causes microbundle to swallow any .css or .scss files imported

## Reproduction steps

Repo: https://github.com/lokimckay-references/microbundle-883

1. `npm init -y`
1. `npm install microbundle --save-dev`
1. add `styles.css` and `index.js` files
1. `import "./styles.css"` within `index.js`
1. copy source/exports/main/module/unpkg fields into `package.json` as per README
    ```
    {
      "name": "foo",                     // your package name
      "type": "module",
      "source": "src/foo.js",            // your source code
      "exports": "./dist/foo.modern.js", // where to generate the modern bundle (see below)
      "main": "./dist/foo.cjs",          // where to generate the CommonJS bundle
      "module": "./dist/foo.module.js",  // where to generate the ESM bundle
      "unpkg": "./dist/foo.umd.js",      // where to generate the UMD bundle (also aliased as "umd:main")
      "scripts": {
        "build": "microbundle",          // compiles "source" to "main"/"module"/"unpkg"
        "dev": "microbundle watch"       // re-build when source files change
      }
    }
    ```
1. update `source` field to point to `index.js`
1. `npm run build`

## Actual output

- All compiled formats of index.js
- Below error message

```
The emitted file "foo.cjs" overwrites a previously emitted file of the same name.
```

![image](https://user-images.githubusercontent.com/14341953/130428371-1dcaa1dd-214b-4943-af85-7ea01ea6ec9b.png)

## Expected output

- All compiled formats of index.js
- **styles.css**
- No error message

## Workaround

Change the file extension of the `main` field from `./dist/foo.cjs` -> `./dist/foo.js`
= achieves expected output

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/147050147-e02f896a-95b9-46b4-9eb9-a69f9adfe7dc.png)

**Comment by rschristian** [comment]
Sorry about that, was missing `.cjs` from the regex. Should be fixed when #919 is merged and released.

**Comment by leohxj** [comment]
microbundle: 0.14.2 see the same error, does it published ??

**Comment by rschristian** [comment]
No, that has not yet been published.

**Comment by leohxj** [comment]
thanks @rschristian  , when will publish it? is there a estimate time?

**Comment by rschristian** [comment]
There's no ETA, no. You can use something like [`patch-package`](https://npm.im/patch-package) to copy over the diff from #919 in the meantime.

**Comment by rschristian** [comment]
@leohxj Just wanted to update you that v0.15 was just published containing this fix.

**Comment by leohxj** [comment]
@rschristian thanks bro
