### ISSUE TITLE
`generateTypes=false` does not work for umd

### ISSUE THREAD

**Issue by zhaoyao91** [developit/microbundle#890]
I have a build cmd below:

`microbundle build -f umd --external=none --generateTypes=false --sourcemap=false`

However, it still generate types file to the dist dir

**Comment by rschristian** [comment]
Are you using TS? If so, this is a duplicate of #863 

If not, can you provide a reproduction?

**Comment by zhaoyao91** [comment]
well, it's TS project. I'll close this to prefer #863
