### ISSUE TITLE
[...NodeList] will translate to [].concat(NodeList), Error

### ISSUE THREAD

**Issue by lizy0329** [developit/microbundle#894]
```javascript
const scripts = document.querySelectorAll('script');
    if ([...scripts].some(item => item.src.indexOf(source) > 0)) {
       // item is a NodeList[script,script]
        if (callback) {
            callback();
        }
        return;
    }
```

expect item is script, actually is NodeList[script,script]

**Comment by kamilic** [comment]
Same issues.

**Comment by developit** [comment]
This is because Microbundle uses Babel's "loose mode" output, which is done intentionally to optimize for size.
As a workaround, I would recommend using `Array.from(NodeList)` or `[].slice.call(NodeList)`.

**Comment by kamilic** [comment]
@developit Can we provide an option for changing loose mode to default mode?

**Comment by lizy0329** [comment]
I don't think developit would do that for optimize bundle size, but I think it would be better to create FAQ or Limitations section in Readme.md

**Comment by developit** [comment]
Correct - using microbundle to compile in non-loose-mode kindof defeats the purpose of microbundle in the first place. Better to write a rollup config at that point.

FWIW these are not issues in the modern output, which preserves `[...x]` as-is.
