### ISSUE TITLE
How to configure microbundle for a submodule structure

### ISSUE THREAD

**Issue by Josema** [developit/microbundle#90]
I have a structure very similar to lodash.
```js
import module1 from 'project/module1'
import module1 from 'project/module2'
import module1 from 'project/module3'
...
```

My entry point looks like (index.js):
```js
module.exports = {
    module1: require('./module1'),
    module2: require('./module2'),
}
```

Is it possible that microbundle creates a file for each module separately? Because I'm getting `index.m.js` and `index.umd.js`

**Comment by developit** [comment]
Hi there - use ES Module imports instead of `require()` for your `index.js`.

**Comment by Josema** [comment]
Hi there! Not sure how to do this actually because my requirements are a little specific.

- This is a npm package
- I want to give ES6/Webpack support
- I want to give cdn support (via unpkg or jsdelivr)

Final usage for the user with ES6/webpack might be:
```js
import module1 from 'project/module1' // this will load only the submodule
import { module1 } from 'project' // this will load all the project
```

With unpkg (always the umd version here)
```html
<script src="https://unpkg.com/package@1.0.0/module1"></script>
```
or
```html
<script src="https://unpkg.com/package@1.0.0"></script>
```
This is optional because make it everything very complex.

Not sure if is possible to achieve this or if I should use my custom setup with webpack.

**Comment by developit** [comment]
Your requirements should all be satisfied by microbundle's default output, you'll just need to run `microbundle` a couple times to get the multi-file output:

```js
microbundle
microbundle project/module1.js -o module1/x.js
microbundle project/module2.js -o module2/x.js
microbundle project/module3.js -o module3/x.js
```

You can use a `package.json` in the output directories to control umd/cjs/esm files. I'd like to add that as an option to Microbundle when we support multiple lib output, but right now it's manual.

**Comment by Josema** [comment]
- Only the umd version must be Uglify
- Also the module2 and module3 import a node_modules libraries but only module2 must include this library into the umd version.

I'm sorry but I didn't realize that my setup is rare until now. I will go for rollup this time, but in the future microbundle is the way to go in most of the cases.

Thank you for the help and for all your libraries, big fan of preact here :)
