### ISSUE TITLE
How to consume different bundles from package.json

### ISSUE THREAD

**Issue by Kikobeats** [developit/microbundle#91]
Hey,

I'm intereted in know how to define correctly each bundle at `package.json`.

For example, I know `cjs` bundle is the property `main`.

What happens with the rest? Could be a great resource to put into the readme 🙂

**Comment by developit** [comment]
Definitely worth adding to the readme, yup.

```js
"main": "dist/foo.js",          // CJS bundle
"umd:main": "dist/foo.umd.js",  // UMD bundle
"module": "dist/foo.m.js",      // ES Modules bundle
"source": "src/foo.js",         // custom entry module (same as 1st arg to microbundle)
```

**Comment by oskarrough** [comment]
Thank you for this.

I'm wondering where the `umd:main` property comes from?  
Which bundlers use it? A search didn't get me far… And what about the `browser` field?

**Comment by linonetwo** [comment]
Seems it is a specification from microbuldle and not offical? https://github.com/stereobooster/package.json#microbundle

**Comment by Kikobeats** [comment]
Already on docs 👌
