### ISSUE TITLE
how to config compress options

### ISSUE THREAD

**Issue by bluelovers** [developit/microbundle#918]
how to config compress options, if i want
- keep fn/class name

**Comment by developit** [comment]
@bluelovers add a `mangle.json` file and define `minify.compress` using any of the [available compress options from Terser](https://github.com/terser/terser#compress-options). Here's an example from Preact:

https://github.com/preactjs/preact/blob/2af05f533ca7a11afcf08d8914df261e2fbec52e/mangle.json#L20-L23
