### ISSUE TITLE
The compressed variables in the output commonjs format file will be rewritten $

### ISSUE THREAD

**Issue by Jokul518** [developit/microbundle#920]
After the packed file compresses the variable name, it will use $, causing the $of jQuery to be overwritten
![image](https://user-images.githubusercontent.com/45039114/147646511-db589471-9d54-450b-aceb-bda3f1268002.png)

**Comment by developit** [comment]
This is working as intended. CommonJS modules are executed within a wrapper function (`(function(module,exports,require){ /* code */ })()`, so those variables are scoped and should not be overwriting anything.

It sounds like you're running the CommonJS bundle _without_ actually using a CommonJS loader, which won't work. I would recommend using the `umd`, `iife` or `es` module types instead.
