### ISSUE TITLE
How to handle declaration files for pure javascript libraries?

### ISSUE THREAD

**Issue by arthurfiorette** [developit/microbundle#925]
For really small projects, like single-file ones, using typescript is overkill. So what I usually do is just manually write my own declaration files. The result of a simple example is something like this:

```
├── src
│   ├── index.d.ts
│   └── index.js
```

If I use `types` in my package.json, microbundle will replace that with what it could generate based on the jsdoc from the `index.js` file. I also tried with `/// triple slash directives`, didn't work.

Is there a way that I can tell microbundle to get that declaration file and use it?

**Comment by rschristian** [comment]
You can use the `--generateTypes` flag:

```
$ microbundle build --generateTypes=false
```

It won't copy your types to your output directory, so if you only distribute `dist/`, you'll need to do a post-build copy yourself.

**Comment by developit** [comment]
Yep! I stick them in the repo root too, to ease publishing.
