### ISSUE TITLE
How to disable css soucemap?

### ISSUE THREAD

**Issue by MinJieLiu** [developit/microbundle#944]
https://github.com/developit/microbundle/blob/master/src/index.js#L489

css should not need sourcemap. It will have warnings on various scaffolding.

![image](https://user-images.githubusercontent.com/6167727/162227217-e367d65c-7c31-46ea-89b2-21fb9be0d608.png)

If it is enabled, it means that I must publish the src directory to npm, otherwise the source information in it cannot be found.

![image](https://user-images.githubusercontent.com/29157700/161938821-0892015b-f90f-4ce4-8083-1c5a1271c3c3.png)

[https://github.com/MinJieLiu/react-photo-view](https://github.com/MinJieLiu/react-photo-view)

**Comment by MinJieLiu** [comment]
> --no-sourcemap

But this will also close the sourcemap of js 😥.

I just want to disable sourcemap in css.

**Comment by rschristian** [comment]
Not sure I follow. If your issue is that you don't ship the source so sourcemaps are ineffective, how are the JS sourcemaps of any use?

I think this is best solved by using a simple post-build script:

> post-build.mjs

```js
import { promises as fs } from 'node:fs';

let css = await fs.readFile('./dist/index.css', 'utf-8');
css = css.replace(/\r?\n.*/g, '');
await fs.writeFile('./dist/index.css', css);
await fs.rm('./dist/index.css.map');
```

```
$ microbundle && node post-build.mjs
```
