### ISSUE TITLE
Packages with `npm:` are copied into dist even if they are described in `dependencies`.

### ISSUE THREAD

**Issue by arthurfiorette** [developit/microbundle#955]
If, in my code, I use `import {} from 'package'`, and in my package.json I use `"npm:package"` instead of `"package"`, `package` is copied into bundle, the same way as if it was described inside `devDependencies`.

**Comment by rschristian** [comment]
Can you provide an example?

> `package` is copied into bundle, the same way as if it was described inside `devDependencies`.

Do you mean the module is inlined? I cannot reproduce.

**Comment by arthurfiorette** [comment]
Exactly, the module gets inlined

**Comment by rschristian** [comment]
Are you writing the following?

```json
{
    "dependencies": {
        "npm:foo": "latest"
    }
}
```

If so, why?

**Comment by arthurfiorette** [comment]
I'm working with a very unique setup...

I'm writing nom:dependency because it is inside a monorepo and I need to install the version from NPM instead of the local one.

I can't give you a reproductive example right now, but it is a OSS repository.

https://github.com/arthurfiorette/tinylibs/commits/main/packages/axios-cache-hooks

By writing npm:object-code it is going to fetch the npm version instead of the local one, but it will inline it too.

**Comment by rschristian** [comment]
I'm pretty sure what you want to be writing is this:

```json
{
    "dependencies": {
        "foo": "npm:foo"
    }
}
```

I see 0 information or support around `npm:pkg` as a valid key for dependencies. It looks to just be ignored.

**Comment by arthurfiorette** [comment]
Hey, You're right! 

The _"correct"_ usage should be `"foo": "npm:foo"`. Thanks for your super fast help!!!
