### ISSUE TITLE
Add Vue.js support

### ISSUE THREAD

**Issue by alexjoverm** [developit/microbundle#96]
I've recently built a [Vue.js component](https://github.com/alexjoverm/v-lazy-image) for lazy loading images and wanted to use microbundle for its setup, but couldn't make it work.

What's required to have Vue.js support?

**Comment by developit** [comment]
Hmm - I'm not sure of a way to support compiling .vue files, since the vue compiler is typically used from a Webpack build process, right?

**Comment by alexjoverm** [comment]
Originally yes, but nowadays there are also plugins for Parcel and Rollup. I see that [rollit](https://github.com/posva/rollit/blob/master/package.json) is using [rollup-plugin-vue](https://github.com/vuejs/rollup-plugin-vue). So, I assume is a matter of adding the plugin?

**Comment by Andarist** [comment]
I believe it would be a matter of detecting that your project is using `.vue` files and adding mentioned plugin conditionally.

**Comment by wcastand** [comment]
I started to work on this.
I'm not super familiar with VueJs but the example that @alexjoverm gave is not using .vue extensions so maybe it would be better if we use something like --jsx option for adding vue support ?

**Comment by Chersquwn** [comment]
Is there any progress now?

**Comment by wcastand** [comment]
Sorry, my bad i completely forgot about this. Like i said, not a vue user so never needed it, which is probably why i forgot about it.

Sorry about that, not sure why i stopped though, might have been waiting for confirmation. If you want to take that on, feel free to go for it. i probably won't have time to jump on it soon.
