### ISSUE TITLE
Error: 'default' is not exported by ../node_modules/prop-types/index.js

### ISSUE THREAD

**Issue by FezVrasta** [developit/microbundle#97]
I'm trying to compile a quite simple app.

```
// @flow
// index.js
import { h, render } from 'preact';
import App from './components/App.js';

const appElement = document.querySelector('#app');

appElement && render(<App />, appElement);
```

```
// components/App.js
// @flow
import { h } from 'preact';
import styled from 'preact-emotion';

const Container = styled('main')`
  color: red;
`;

export default function App() {
  return <Container>Red</Container>;
}
```

But I get:

```
Error: 'default' is not exported by ../node_modules/prop-types/index.js
```

This is my babelrc:

```
{
  "plugins": [["transform-react-jsx", { "pragma": "h" }], "emotion"]
}
```

It looks like the error happens when I import `preact-emotion`

**Comment by FezVrasta** [comment]
If I add `prop-types` to the dependencies it works just fine 🤷‍♂️

**Comment by Andarist** [comment]
Could you try swapping `commonjs` plugin with `nodeResolve` (both should still be there, just `nodeResolve` should be before `commonjs`)? Ofc remove `prop-types` from ur dependencies first to recreate the buggy situation.

**Comment by FezVrasta** [comment]
I don't think I follow sorry 😓

**Comment by Andarist** [comment]
You'd hav to dive into your `node_modules`. Unfortunately `microbundle` gets shipped minified at the moment, so it won't be that easy - then just discard my idea. Could u prepare a sample repository with the issue reproduced so I could debug it myself?

**Comment by FezVrasta** [comment]
[repro.zip](https://github.com/developit/microbundle/files/1771578/repro.zip)

I can't exactly reproduce the same error for some reason, but I get something similar:

```
'prop-types' is imported by node_modules/create-emotion-styled/dist/index.es.js, but could not be resolved – treating it as an externaldependency
Error: Could not load prop-types (imported by /private/tmp/repro/node_modules/create-emotion-styled/dist/index.es.js): ENOENT: no such file or directory, open 'prop-types'
```

I guess it's strictly related.

**Comment by developit** [comment]
Is `preact-emotion` installed as a dependency, or `peerDependency`?

**Comment by FezVrasta** [comment]
dependency, with `--external all` it seems to work.

**Comment by Andarist** [comment]
So this has kinda surprised me. IMHO reasonable default would be to:
- make `--external all` a default
- at the same time treat only peerDeps as external for UMD bundles
- override described default behaviour when explicit `external` option gets used

@developit WDYT?

**Comment by developit** [comment]
I'm a bit afraid of bundling differing child libs depending on module type.  For @FezVrasta's issue, it seems like his module should be referencing preact-emotion as a `peerDependency`.
