### ISSUE TITLE
Unable to render useState, useEffect hooks in library

### ISSUE THREAD

**Issue by Dev-Phani** [developit/microbundle#974]
Hi I am trying to create a sample library using react 18.2.0 and Although library built successfully but when it is consumed in the app im getting the below error in console log
![Capture](https://user-images.githubusercontent.com/51257709/178314740-b669b683-02be-4fb4-bd04-72518a42ec88.PNG)

below is my library code 

**App.js** 

```
import './App.css';
import Dropdown from "./components/Dropdown";

function App() {
   
  let dropdown_data = ['Item 1', 'Item 2', 'Item 3'];

    return (
      <div className="dropdown">
         <Dropdown jsonData={dropdown_data} />
      </div>
  )
}

export default App;
```

**Created components folder under that created Dropdown.js**

```
import React from "react";
import {useEffect, useState} from 'react';

export const Dropdown = (props) => {
    const [dropdown, setDropdown] = useState([]);
    useEffect(() => {
        loadData();
    }, []);
    const loadData = () => {
        setDropdown(props.jsonData);
    }
    return (
        <div className="dropdown">
            <select> {
                dropdown.map((item, index) => (
                    <option key={index}>
                        {item}</option>
                ))
            } </select>
        </div>
    )

}


```
**in the src folder created the lib.package.js**
`export { Dropdown } from "./components/Dropdown.js";`

**below is my package.json**
```

{
  "name": "libtestone",
  "version": "0.1.0",
  "private": true,
  "main": "./dist/lib.umd.js",
	"module": "./dist/lib.module.js",
	"source": "src/lib.package.js",
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "build:lib": "microbundle --jsx React.createElement --jsxFragment React.Fragment --jsxImportSource react"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "microbundle": "^0.15.0"
  }
}

```

**Below is my client app where i am consuming the  package**

**App.js**

```

import './App.css';
import {Dropdown} from "libtestone";

function App() {
  return (
    <div>
      <Dropdown />
    </div>
  );
}

export default App;
```

 @[developit](https://github.com/developit) @rschristian

**Comment by rschristian** [comment]
Please provide a repo that I can just clone containing both the lib and your app, piecing this together from a few files isn't really effective.

Something that does standout though is the mixing of JSX transforms. You probably don't want to be doing that, and might lead to an issue like this. Choose one or the other for your lib.

**Comment by Dev-Phani** [comment]
> Please provide a repo that I can just clone containing both the lib and your app. I spent some time trying to piece this together but I could not reproduce the issue.
> 
> Something that stands out is the mixing of JSX transforms; there's no good reason to do this and I imagine it could lead to issues. Choose one or other for your lib, not both.
> 
> You're also mixing and matching default & named exports. Not sure if this was just a byproduct of pasting into this issue, but it certainly doesn't work if someone copy/pasted your code directly.

@rschristian please find the url [https://github.com/Dev-Phani/reac-lib](url) and in the zip there are 2 folder 1.consume which is a client app and 2. lib application

**Comment by rschristian** [comment]
It looks like you're trying to bundle a web app with Microbundle? Your lib should have nothing related to CRA. That's probably the problem. Rip it all out, export & expose nothing but your component.

**Comment by rschristian** [comment]
1) Don't mix and match JSX transforms. Pick either the classic or runtime. This means removing `--jsxImportSource` or the pragma / pragma frag options.

2) If you're embedding into a React app, you don't want `--external none`. This bundles React in with your component, essentially duplicating React within your app. Only use that if you're embedding into a page where React is no available.

There's nothing wrong with Microbundle here, so I'm going to close this out.

**Comment by rschristian** [comment]
Created an example repo for you here: https://github.com/rschristian/dev-phani-react-lib-example

Also, use something like [yalc](https://github.com/wclr/yalc) when testing libs locally. It's a lot more robust, and linking locally (as you have) is incredibly error prone in just about every package manager. Most of the time doing that will break your lib, causing duplicate bundles and the like.
