### ISSUE TITLE
[Question] Build for both client side and server side

### ISSUE THREAD

**Issue by multivoltage** [developit/microbundle#980]
I built a library which is a wrapper of some api. So my lib uses axios (included in bundle).
I want to delivery something that work for example:
- in react so basically in a client side (now it works)
- in next js inside lamba files (folder under pages/api) for example.

In the second case call to lambda from a page throw: XMLHttpRequest is not defined.
There is a possibility to do that?
Thanks

**Comment by multivoltage** [comment]
Yes I know but using target = node produce same file with same extension. So is impossible to have both js for both environment. Maybe I forgot somethings?

**Comment by rschristian** [comment]
> using target = node produce same file with same extension

If you're just referring to the naming collision, there's plenty of options there, from renaming to nesting.

```json
{
  // package.json
  "scripts": {
    "build:web": "microbundle -o dist/web",
    "build:node": "microbundle -o dist/node --target node"
  }
}
```

**Comment by multivoltage** [comment]
Thanks @rschristian . So how describe package json in this case?

```js
  "exports": {
    "require": "./dist/node/a.cjs",
    "default": "./dist/node/a-modern.js"
  },
  "main": "./dist/node/a.cjs",
  "module": "./dist/node/a.module.js",
```
Sorry but I cannot undestand where put /web :)

**Comment by rschristian** [comment]
Depends a bit on what tools you want to support. Generally, `"module"` or `"browser"` work pretty well:

```json
{
  "exports": {
    "module": "./dist/web/...",
    ...
  }
}
```

You might want to browse [Webpack's package exports docs](https://webpack.js.org/guides/package-exports/#reference-syntax). It contains info for a bunch of different tools, not just Webpack.
