### ISSUE TITLE
Uncaught TypeError: React__default.default is undefined when importing React in my source files

### ISSUE THREAD

**Issue by bhch** [developit/microbundle#983]
When I use `import React from 'react'` in my source files, the umd build file shows this error in the browser:

```javascript
Uncaught TypeError: React__default.default is undefined
```

If I remove the `import` statements, the error is gone and everything works perfectly.

#### Reproduce error

Clone this repo: https://github.com/bhch/react-microbundle-test/

#### Version info

 - Microbundle: 0.15.0 (also tested with 0.13.2)
 - Node: 18.6.0 (also tested with 12.19.0)

**Comment by bhch** [comment]
Hi, can I please get some pointers to resolve this? It's been driving me mad for past four days.

**Comment by rschristian** [comment]
You're relying on globals but not telling Microbundle about them.

```diff
// package.json
{
  ...
  "scripts": {
-    "build": "microbundle --jsx React.createElement",
+    "build": "microbundle --jsx React.createElement --globals react=React,react-dom=ReactDOM",
    "dev": "microbundle watch --no-compress --sourcemap false --jsx React.createElement"
  }
}
```

**Comment by bhch** [comment]
Thank you. This has solves the issue.

However, can you please explain why we need to declare `--globals`? Shouldn't microbundle automatically infer this for variables imported from dependencies?

**Comment by rschristian** [comment]
This might be more clear if you run a build with & without `--globals` (toss the result into a diff tool).

Microbundle gives a good shot at assuming names for each, using `global.react` and `global.reactDom`. However, using the official React bundles, these of course are instead supplied as `global.React` and `global.ReactDOM`. They could just as easily be supplied as `global.foo` and `global.bar` though. There's no way of knowing how a package import might connect to globals.
