### ISSUE TITLE
microbundle config file (for define aliases)

### ISSUE THREAD

**Issue by alimsadeghi1** [developit/microbundle#986]
I have alias in my project and I rather define them in a file and not cli. Is there any way for doing this?

**Comment by rschristian** [comment]
Microbundle does offer a programmatic API which should fit your needs, but that's in place of the CLI.

```js
const microbundle = require('microbundle');

(async function () {
    await microbundle({ ... });
})();
```

**Comment by alimsadeghi1** [comment]
Is there any best practice or example for that?

**Comment by rschristian** [comment]
Using it programmatically? Not that I know of, it's pretty uncommon use I think.

If you provide the format of your config file I can write up a more specific example, but likely will look something like:

```js
// build.js
const microbundle = require('microbundle');
const fs = require('fs/promises');

(async function () {
    const alias = fs.readFile('aliases.txt', 'utf-8');
    await microbundle({
        cwd: '.',
        input: './src/index.js',
        output: './dist/index.js',
        format: 'cjs,esm',
        alias,
    });
})();
```

How many aliases are we talking about here? If it's just a few, then adding a layer of indirection with a custom build script really doesn't make much sense.

**Comment by alimsadeghi1** [comment]
Thank you for responding so quickly. I actually want to have something like this:
`@components: ./src/components
`

**Comment by rschristian** [comment]
```
// aliases.txt
@components: ./src/components
@routes: ./src/routes
```

```js
// build.js
const microbundle = require('microbundle');
const fs = require('fs/promises');

(async function () {
    let alias = await fs.readFile('aliases.txt', 'utf-8');
    alias = alias.replace(/:\s/g, '=').replace(/\n/g, ',');
    await microbundle({
        cwd: '.',
        input: './src/index.js',
        output: './dist/index.js',
        format: 'cjs,esm',
        alias,
    });
})();
```

This should do the trick.

It simply reads your alias file, replaces the semi-colon and proceeding space with an equals sign, then converts all new lines into commas so you have a list of comma-separated entries.

**Comment by alimsadeghi1** [comment]
Thank you very much. it works.
but I think it would be great if microbundle could read aliases from `tsconfig` using `--tsconfig`.

**Comment by alimsadeghi1** [comment]
Thank you very much. it works.
but I think it would be great if microbundle could read aliases from `tsconfig` using `--tsconfig`.

**Comment by rschristian** [comment]
Type aliases aren't always module aliases. Doing so would cause more issues that's it's worth, IMO.
