### ISSUE TITLE
Failed to resolve the module node:*

### ISSUE THREAD

**Issue by ahmadnassri** [developit/microbundle#989]
node core modules can imported with [`node:` prefix](https://nodejs.org/api/modules.html#core-modules), e.g. `require('node:fs')` don't seem to work.

![image](https://user-images.githubusercontent.com/183195/184065945-0e14f5ba-db78-46ca-9f34-377ec675b7a8.png)

**Comment by rschristian** [comment]
Just a warning, and already resolved by #956

**Comment by rschristian** [comment]
Just release `0.15.1` so this should be corrected.

Thanks

**Comment by ahmadnassri** [comment]
Thank you @rschristian

**Comment by donmccurdy** [comment]
I'm compiling a library that runs in both Node.js and a browser, and the library contains dynamic imports for node built-ins like 'fs', executed only in Node.js. The target for Microbundle is not necessarily Node.js.

When importing `fs` I can add the following to my `package.json` and everything works fine:

```
"browser": {
  "fs": false,
  "path": false
},
```

However, using `node:fs`, the same thing does not work, and warnings continue to appear with:

```
"browser": {
  "node:fs": false,
  "node:path": false
},
```

Is this intended, and (if not) should I file a separate issue for it?

**Comment by rschristian** [comment]
@donmccurdy Separate issue please, if you can
