### ISSUE TITLE
[Probable user error] UMD builds no longer loading external dependency correctly 

### ISSUE THREAD

**Issue by aholachek** [developit/microbundle#995]
Hi, thank you very much for this incredibly useful tool.

I use it to build my animation library [react-flip-toolkit](https://github.com/aholachek/react-flip-toolkit), but I believe I am doing something incorrect regarding UMD builds, and I was hoping I could get some guidance here.

### The problem

Other than React libs, `react-flip-toolkit` depends on a single external library called `Rematrix`. 

I've been using [this codepen](https://codepen.io/aholachek/pen/ERRpEj) to verify that umd builds are working (clicking on the text should show an animation if everything is correct), however, at some point the external dependency `Rematrix` stopped loading correctly:

![Screen Shot 2022-09-03 at 11 22 23 AM](https://user-images.githubusercontent.com/3680488/188277298-2007cfcb-e808-47db-a530-84f86351fa58.png).

This configuration of script loading **used** to work for the pen:
![Screen Shot 2022-09-03 at 11 23 58 AM](https://user-images.githubusercontent.com/3680488/188277366-9d2f34ef-9e28-41ea-b386-e1ccf4232ce6.png)

## Calls to Microbundle 

I call microbundle [here](https://github.com/aholachek/react-flip-toolkit/blob/master/packages/react-flip-toolkit/package.json#L28) (for bundling `react-flip-tooklit`) as well as [here ](https://github.com/aholachek/react-flip-toolkit/blob/master/packages/flip-toolkit/package.json#L26)(for bundling the underlying utility `flip-toolkit`).

Can you see anything I am doing wrong?

**Comment by rschristian** [comment]
You missing `--globals rematrix=Rematrix` in `flip-toolkit`.

Setting that in `react-flip-toolkit` doesn't do any good as it doesn't rely on `rematrix`. Instead it's `flip-toolkit` that relies on it and will need to be bundled aware that it's available as `Rematrix`, not `rematrix`, in a UMD environment.

**Comment by aholachek** [comment]
Thank you so much for the help, I just published a new version with your updates and indeed everything is working well now.

**Comment by rschristian** [comment]
Glad to hear it!
