### ISSUE TITLE
ts file does not get compiled and I get Duplicate declaration error

### ISSUE THREAD

**Issue by RocKing1001** [developit/microbundle#996]
I also get the error `Generated an empty chunk: "index"`
![image](https://user-images.githubusercontent.com/44892832/188493129-0b641751-6e0d-4092-931d-efc85a7fe9b9.png)

this in `./dist/index.d.ts`
![image](https://user-images.githubusercontent.com/44892832/188493226-06fadd1a-cd6e-4857-8b2c-7e010e89abbe.png)

`./dist/client.js`
![image](https://user-images.githubusercontent.com/44892832/188493241-f81e58bc-a8cf-4081-ad88-245b72966fde.png)

**Comment by rschristian** [comment]
Please provide a reproduction. This usually means you have no input.

**Comment by RocKing1001** [comment]
I realised the issue, I had removed the export at some point when reformatting my code. Thanks for your help and sorry for the trouble
